### PR TITLE
MF-673 - Fix offset calculation after deleting thing or channel

### LINKED ISSUE #673: Deleting last channel  doesn't remove it from list
**BUG REPORT**

1. What were you trying to achieve?
Delete channel when you have one channel

2. What are the expected results?
Deleting channel and removing it from list of channels

3. What are the received results?
Deleting channel on server but not removing it from the list

4. What are the steps to reproduce the issue?

- Create only one channel
- Remove it
- It's still in the list

5. In what environment did you encounter the issue?

Local enviroment, Mainflux in docker, `env.url = " url = "http://localhost:80/"`

6. Additional information you deem important:
Check if same bug exists for things list

### PR DESCRIPTION
**Pull request by blokovi**
Signed-off-by: Ivan Milošević <iva@blokovi.com>

### What does this do?
Fix offset calculation after deleting thing/channel, not to go to negative offset after deleting last thing/channel

### Which issue(s) does this PR fix/relate to?
Resolves #673

### CODE REVIEW

**Review by drasko — APPROVED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]

File: ui/src/Helpers.elm [hunk 1]
```diff
@@ -85,7 +85,7 @@ offsetToPage offset limit =
 validateOffset : Int -> Int -> Int -> Int
 validateOffset offset total limit =
     if offset >= (total - 1) then
-        (total - 1) - limit
+        Basics.max ((total - 1) - limit) 0
```
Comment (darkodraskovic) [inline ui/src/Helpers.elm:88]: Forgot to take into account 0 :)

LGTM
