### PR TITLE
MF-380 - Fix topic to channel parsing

### LINKED ISSUE #380: Posibble wrong routing in mqtt
**BUG REPORT**

1. What were you trying to achieve?
Publish messages on a mqtt topic and receive messages on the same topic

2. What are the expected results?
Only messages with topic channels/1/messages get routed to that specific topic

3. What are the received results?
Messages with topic <anything>/1/<anything> get routed to channels/1/messages

4. What are the steps to reproduce the issue?
Use mosquitto client, listen on topic channels/1/messages and using another client publish on anything/1/anything

5. In what environment did you encounter the issue?
Typical mainflux docker-compose setup

6. Additional information you deem important:

### PR DESCRIPTION
**Pull request by ghost**
This pull request resolves #380 

**Summary:**

- Fix topic to channel parsing

### CODE REVIEW

**Review by drasko — DISMISSED** [review]
LGTM

File: mqtt/mqtt.js [hunk 1]
```diff
@@ -72,8 +72,14 @@ nats.subscribe('channel.*', function (msg) {
 
 aedes.authorizePublish = function (client, packet, publish) {
     // Topics are in the form `channels/<channel_id>/messages`
-    var channel = packet.topic.split('/')[1],
-        accessReq = {
+    var channel = /^channels\/(\d+)\/messages$/.exec(packet.topic);
```
Comment (anovakovic01) [inline mqtt/mqtt.js]: Don't use `\d`, use id as string. It can change and probably will, so make this as independent as possible.

File: mqtt/mqtt.js [hunk 2]
```diff
@@ -72,8 +72,14 @@ nats.subscribe('channel.*', function (msg) {
...
+    if (channel == null) {
+        logger.warn('unknown topic');
+        publish(4); // Bad username or password
+        return;
+    }
+    channel = channel[1];
+    var accessReq = {
             token: client.password,
             chanID: Number(channel)
         },
```
Comment (anovakovic01) [inline mqtt/mqtt.js]: Fix indentation.

File: mqtt/mqtt.js [hunk 3]
```diff
@@ -72,8 +72,14 @@ nats.subscribe('channel.*', function (msg) {
 
 aedes.authorizePublish = function (client, packet, publish) {
     // Topics are in the form `channels/<channel_id>/messages`
-    var channel = packet.topic.split('/')[1],
-        accessReq = {
+    var channel = /^channels\/(\d+)\/messages$/.exec(packet.topic);
+    if (channel == null) {
```
Comment (anovakovic01) [inline mqtt/mqtt.js]: In JS you usually check this stuff like `!channel`.

**Review by anovakovic01 — CHANGES_REQUESTED** [review]

File: mqtt/mqtt.js (hunk 2 above)
Comment (ghost) [reply mqtt/mqtt.js]: are you sure it needs to be fixed? ;)

Comment (anovakovic01) [reply mqtt/mqtt.js]: Sorry, didn't see code below `,`.

File: mqtt/mqtt.js (hunk 3 above)
Comment (ghost) [reply mqtt/mqtt.js]: done

File: mqtt/mqtt.js (hunk 1 above)
Comment (ghost) [reply mqtt/mqtt.js]: done

File: mqtt/mqtt.js [hunk 4]
```diff
@@ -72,8 +72,14 @@ nats.subscribe('channel.*', function (msg) {
...
     // Topics are in the form `channels/<channel_id>/messages`
-    var channel = packet.topic.split('/')[1],
-        accessReq = {
+    var channel = /^channels\/(.+?)\/messages$/.exec(packet.topic);
+    if (!channel) {
+        logger.warn('unknown topic');
+        publish(4); // Bad username or password
+        return;
+    }
+    channel = channel[1];
```
Comment (anovakovic01) [inline mqtt/mqtt.js]: Please create new variable for this (e.g. `channelId`).

**Review by anovakovic01 — CHANGES_REQUESTED** [review]

File: mqtt/mqtt.js (hunk 4 above)
Comment (ghost) [reply mqtt/mqtt.js]: done

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Review by drasko — APPROVED** [review]
LGTM

**Comment by drasko** [comment]
Merged! Thanks!
