### PR TITLE
MG-2026 - Fix JSON page response key from `groups` to `channels`

### LINKED ISSUE #2026: Fix JSON page response key from `groups` to `channels`
Following request should change
- `GET /groups/{groupID}/channels`   
- `GET /channels`
- `GET /users/{userID}/channels`

### PR DESCRIPTION
**Pull request by JeffMboya**
# What type of PR is this?
This is a refactor

## What does this do?
This PR fixes the JSON Page response  key from `groups` to `channels` for the following endpoints:
- `GET /groups/{groupID}/channels`
- `GET /channels`
- `GET /users/{userID}/channels`

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #2026

## Have you included tests for your changes?
Manually tested endpoints

## Did you document any new/modified feature?
No

### CODE REVIEW

File: internal/groups/api/responses.go [hunk 1]
```diff
@@ -82,7 +82,7 @@ func (res createGroupRes) Empty() bool {
 
 type groupPageRes struct {
 	pageRes
-	Groups []viewGroupRes `json:"groups"`
+	Groups []viewGroupRes `json:"channels"`
```
Comment (dborovcanin) [inline internal/groups/api/responses.go]: Why do we use channel terminology for groups? I.e. no all groups are channels.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]

**Review by dborovcanin — CHANGES_REQUESTED** [review]
@JeffMboya Please fix the CI.

File: internal/groups/api/endpoints.go [hunk 2]
```diff
@@ -284,3 +294,25 @@ func buildGroupsResponse(gp groups.Page, filterByID bool) groupPageRes {
...
+		Channels: []viewGroupRes{},
+	}
+
+	for _, channel := range cp.Groups {
+		view := viewGroupRes{
+			Group: channel,
+		}
+		if filterByID && channel.Level == 0 {
+			continue
+		}
```
Comment (dborovcanin) [inline internal/groups/api/endpoints.go:311]: Move this to the top (to avoid unnecessary allocations) or use `if !filterByID && channel.Level != nil {...}`

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
