### PR TITLE
SMQ-2842 - Fix client telemetry handling in journal service

### LINKED ISSUE #2842: Bug:  Journal service could not consume new events
### What were you trying to achieve?

View the Audit log of a entity

### What are the expected results?

No Audit logs

### What are the received results?

Audit logs

### Steps To Reproduce

Run the SuperMQ + Magistrala 
Then sent lot of messages 

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

Journal service failed to handle message and the failed messages are not acknoweldged by NAST Handler 
So again these messages are queue backed to NATS consumer - `events__-jorunal`

```
{"time":"2025-04-29T14:17:23.054395618Z","level":"WARN","msg":"Save journal failed","duration":"3.453307ms","request_id":"","journal":{"occurred_at":"2025-04-28T14:17:43.625060352Z","operation":"messaging.client_publish"},"error":{"error":"","message":"entity not found"}}
{"time":"2025-04-29T14:17:23.054482056Z","level":"WARN","msg":"Failed to handle SuperMQ message: failed to handle nats event: entity not found"}
{"time":"2025-04-29T14:17:23.058153203Z","level":"WARN","msg":"Save journal failed","duration":"3.549231ms","request_id":"","journal":{"occurred_at":"2025-04-28T14:17:43.625101824Z","operation":"messaging.client_publish"},"error":{"error":"","message":"entity not found"}}
{"time":"2025-04-29T14:17:23.058894671Z","level":"WARN","msg":"Failed to handle SuperMQ message: failed to handle nats event: entity not found"}
```

Journal service could not able to process the events , 
One of the example events:
```
{"occurred_at":1745938409291330344,"operation":"group.role.list_available_actions"}
```

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #2842 

## What does this do?
This pr:
- Improves handling of client telemetry in repository
- Fixes bugs in client removal in clients telemetry
- Fixes issue with publishing of `messaging.client_publish` events

## Which issue(s) does this PR fix/relate to?

- Related Issue #2842
- Resolves #2842

## Have you included tests for your changes?
No, tested manually

## Did you document any new/modified feature?
No

### Notes
none

### CODE REVIEW

File: journal/postgres/telemetry.go [hunk 1]
```diff
@@ -38,14 +38,11 @@ func (repo *repository) DeleteClientTelemetry(ctx context.Context, clientID, dom
...
-
-	result, err := repo.db.NamedExecContext(ctx, q, dbct)
+	_, err := repo.db.NamedExecContext(ctx, q, dbct)
 	if err != nil {
 		return postgres.HandleError(repoerr.ErrRemoveEntity, err)
 	}
-	if rows, _ := result.RowsAffected(); rows == 0 {
-		return repoerr.ErrNotFound
-	}
+
```
Comment (arvindh123) [inline journal/postgres/telemetry.go:49]: Could we handle error `repoerr.ErrNotFound` in service layer? 
May be this information might be use full for logging in service layer.

File: journal/postgres/telemetry.go [hunk 2]
```diff
@@ -144,15 +141,11 @@ func (repo *repository) IncrementInboundMessages(ctx context.Context, clientID s
 		return errors.Wrap(repoerr.ErrUpdateEntity, err)
 	}
 
-	result, err := repo.db.NamedExecContext(ctx, q, dbct)
+	_, err = repo.db.NamedExecContext(ctx, q, dbct)
 	if err != nil {
 		return postgres.HandleError(repoerr.ErrUpdateEntity, err)
 	}
```
Comment (arvindh123) [inline journal/postgres/telemetry.go]: If inbound message is not found, Instead of skipping them why don't we create a new entry for these messages?

File: journal/service.go [hunk 3]
```diff
@@ -108,7 +108,7 @@ func (svc *service) handleTelemetry(ctx context.Context, journal Journal) error
 }
 
 func (svc *service) addClientTelemetry(ctx context.Context, journal Journal) error {
-	ce, err := toClientEvent(journal)
+	ce, err := toClientEvent(journal, true)
```
Comment (arvindh123) [inline journal/service.go:116]: What do you think about handing postgres error `entity already exists` here in `addClientTelementry` at service layer ?

File: cmd/mqtt/main.go [hunk 4]
```diff
@@ -148,13 +148,6 @@ func main() {
 	}
 	defer mpub.Close()
 
-	mpub, err = msgevents.NewPublisherMiddleware(ctx, mpub, cfg.ESURL)
```
Comment (arvindh123) [inline cmd/mqtt/main.go:151]: I agree with removal of this events middleware, Forward (consumer) no need to publish their events to NATS.

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: journal/service.go [hunk 5]
```diff
@@ -228,11 +227,13 @@ func toClientEvent(journal Journal) (clientEvent, error) {
...
-		if err != nil {
-			return clientEvent{}, fmt.Errorf("invalid created_at format")
+	if isCreate {
+		createdAtStr := journal.Attributes["created_at"].(string)
+		if createdAtStr != "" {
+			createdAt, err = time.Parse(time.RFC3339, createdAtStr)
+			if err != nil {
+				return clientEvent{}, fmt.Errorf("invalid created_at format")
+			}
 		}
```
Comment (arvindh123) [inline journal/service.go:249]: @felixgateru @dborovcanin 

What do you think about this approach
If we return error then it will again queue back. So we can log them or store in separate place 
```suggestion
	if isCreate {
		createdAtIf, ok := journal.Attributes["created_at"]
		if ok {
			createdAtStr, ok := createdAtIf.(string)
			if ok && createdAtStr != "" {
				createdAt, err = time.Parse(time.RFC3339, createdAtStr)
				if err != nil {
					log.Println("log error : invalid created_at format")
				}
			}
		}
```

File: journal/postgres/telemetry.go (hunk 2 above)
Comment (felixgateru) [reply journal/postgres/telemetry.go]: Initially I was of the idea, I could add it as a feature after we had added domainID to the internal message topic so that client telemetry can also be created on client_subscribe if it did not exist.
I can add for client_publish now and for the client_subscribe later.

File: journal/service.go (hunk 3 above)
Comment (felixgateru) [reply journal/service.go:116]: Do we just log the error?

Comment (arvindh123) [reply journal/service.go:116]: If we are returning error, then the message will again queued back , this will go into a loop

File: journal/service.go (hunk 5 above)
Comment (dborovcanin) [reply journal/service.go:249]: I don't mind having a trash to store unsuccessfully processed events.

Comment (arvindh123) [reply journal/service.go:249]: Yeah I agree, Can we do it in next PR ?

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Instead of logging errors directly in the service and returning nil, we should wrap the error with contextual information and propagate it. This allows us to decouple logging concerns from business logic and delegate error handling to the caller.

**Review by arvindh123 — DISMISSED** [review]

File: docker/addons/journal/docker-compose.yaml [hunk 6]
```diff
@@ -16,7 +16,6 @@ networks:
 volumes:
   supermq-journal-volume:
 
-
```
Comment (dborovcanin) [inline docker/addons/journal/docker-compose.yaml]: Keep this one. One empty line is for the value (empty), and the other isthe  separator for better readability.

File: journal/events/consumer.go [hunk 7]
```diff
@@ -35,22 +41,26 @@ func Handle(service journal.Service) handleFunc {
 
 		operation, ok := data["operation"].(string)
 		if !ok {
-			return errors.New("missing operation")
+			slog.Error(errMsg, "error", errMissingOperation)
```
Comment (dborovcanin) [inline journal/events/consumer.go:45]: Add a comment with an explanation for logging and replacing errors with nil.

File: journal/service.go (hunk 5 above)
Comment (dborovcanin) [reply journal/service.go:249]: Yes, this should be done in a separate PR. @felixgateru Please open a ticket for this.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: journal/service.go (hunk 5 above)
Comment (felixgateru) [reply journal/service.go:249]: Done :https://github.com/absmach/supermq/issues/2880

**Review by arvindh123 — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]
