### PR TITLE
SMQ-2435 - Allow resending rejected invitation

### LINKED ISSUE #2435: Bug: Invitation can not be resent to a user who rejected an invitation to the domain
### What were you trying to achieve?

Resend an invitation to a user who rejected an invitation.

### What are the expected results?

The invitation should be sent to the user to respond once more.

### What are the received results?

Conflict due to the primary key of the invitation. Hence the invitation can not be sent to the user.

### Steps To Reproduce

Send an invitation to a user
User rejects it
Send an invitation to the same user, to join the same domain.

### In what environment did you encounter the issue?

magistrala

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a refactor as it allows a rejected invitation to be resent

## What does this do?
This pr enables a rejected invitation to be resent and hence can be accepted.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2435
- Resolves #2435

## Have you included tests for your changes?
Yes, relevant tests have been updated.

## Did you document any new/modified feature?
No

### Notes
None

### CODE REVIEW

File: domains/service.go [hunk 1]
```diff
@@ -193,12 +193,38 @@ func (svc *service) SendInvitation(ctx context.Context, session authn.Session, i
...
+	inv, err := svc.repo.RetrieveInvitation(ctx, invitation.InviteeUserID, invitation.DomainID)
+	if err != nil {
+		return err
+	}
+	if !inv.ConfirmedAt.IsZero() {
+		return svcerr.ErrInvitationAlreadyAccepted
+	}
+	if !inv.RejectedAt.IsZero() {
+		invitation.RejectedAt = time.Time{}
+		invitation.UpdatedAt = time.Now()
```
Comment (dborovcanin) [inline domains/service.go]: Let's use time.Now().UTC() instead. We're slowly switching to UTC for all time values.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
