### PR TITLE
MG-53 - Remove precondition check : User exists in Domain only for Super admin in add policies

### LINKED ISSUE #53: Auth: Preconditions checks prevents super admin to create things ,groups ,channels
**BUG REPORT**

1. What were you trying to achieve?

2. What are the expected results?

3. What are the received results?

4. What are the steps to reproduce the issue?

5. In what environment did you encounter the issue?

6. Additional information you deem important:

### PR DESCRIPTION
**Pull request by arvindh123**
Pull request title should be `MG-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/absmach/magistrala/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Super Admin could not create entitles, This PR fix this bug 

### Which issue(s) does this PR fix/relate to?
Put here `Resolves #XXX` to auto-close the issue that your PR fixes (if such)
Resolves #53

### CODE REVIEW

File: auth/spicedb/policies.go [hunk 1]
```diff
@@ -520,7 +544,7 @@ func userThingPreConditions(pr auth.PolicyReq) ([]*v1.Precondition, error) {
 	return preconds, nil
 }
 
-func groupPreConditions(pr auth.PolicyReq) ([]*v1.Precondition, error) {
+func (pa *policyAgent) groupPreConditions(ctx context.Context, pr auth.PolicyReq) ([]*v1.Precondition, error) {
```
Comment (dborovcanin) [inline auth/spicedb/policies.go:547]: No need to attach it to `policyAgent`.

File: auth/spicedb/policies.go [hunk 2]
```diff
@@ -587,7 +611,7 @@ func groupPreConditions(pr auth.PolicyReq) ([]*v1.Precondition, error) {
 	return precond, nil
 }
 
-func channelThingPreCondition(pr auth.PolicyReq) ([]*v1.Precondition, error) {
+func (pa *policyAgent) channelThingPreCondition(ctx context.Context, pr auth.PolicyReq) ([]*v1.Precondition, error) {
```
Comment (dborovcanin) [inline auth/spicedb/policies.go:614]: Same here.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
