### PR TITLE
SMQ-2706 - Add domain id to message topic

### LINKED ISSUE #2706: Add Domain ID to message topic
Current Message format in `channels/<channel_id>/messages/<sub_topic>/...`
We need something like `<domain_id>/channels/<channel_id>/message/<sub_topic>/...`

Additional authorization we need to add in all protocol adapters, if `<domain_id>` is not enabled , then authorization should fail

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a feature because it adds domain id to message topic.

## What does this do?
- Adds domain id to message topic.
- Refactors message topic from `/c/<channel_id>/m/<optional_subtopic>` to `m/<domain_id>/c/<channel_id>/<optional_subtopic>`
- Updates tests for the above change
- Adds check for domain status on channel authorization.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2706
- Resolves #2706

## Have you included tests for your changes?
Yes, tests have been updated.

## Did you document any new/modified feature?
Yes, in code documentation has been updated.

### Notes
None

### CODE REVIEW

File: channels/private/service.go [hunk 1]
```diff
@@ -25,15 +29,23 @@ type service struct {
...
 }
 
 func (svc service) Authorize(ctx context.Context, req channels.AuthzReq) error {
+	d, err := svc.domains.RetrieveEntity(ctx, req.DomainID)
+	if err != nil {
+		return errors.Wrap(svcerr.ErrAuthorization, err)
+	}
+	if d.Status != dom.EnabledStatus {
+		return errors.Wrap(svcerr.ErrAuthorization, errDisabledDomain)
+	}
```
Comment (arvindh123) [inline channels/private/service.go:47]: If `req.ClientType` is `policies.UserType`, then we might need to check user is present in domain or not. 
I'm not sure about  this , but i need to test this case. 
Steps to replicate : 
- We need to add member to domain role 
- Add access to channel
- Remove member from domain role
- then test reading value of message via reader. 

On removal of member from domain role and if member is not removed from other entities and removed only from domains, then even after removal of member will still have access to channels. 


User removal PR will solve this case.

**Review by arvindh123 — COMMENTED** [review]
All looks good, except i have one comment which need testing, I will create issue for this comment

File: channels/private/service.go (hunk 1 above)
Comment (arvindh123) [reply channels/private/service.go:47]: I have created ticket here https://github.com/absmach/supermq/issues/2767

**Review by arvindh123 — DISMISSED** [review]

**Comment by dborovcanin** [comment]
@arvindh123 Please review this one.

**Review by nyagamunene — APPROVED** [review]
LGTM

**Review by arvindh123 — APPROVED** [review]
LGT

File: coap/adapter.go [hunk 2]
```diff
@@ -29,12 +29,12 @@ type Service interface {
...
 	// service map of subscriptions under given ID.
-	Subscribe(ctx context.Context, key, chanID, subtopic string, c Client) error
+	Subscribe(ctx context.Context, key, domainID, chanID, subtopic string, c Client) error
 
 	// Unsubscribe method is used to stop observing resource.
-	Unsubscribe(ctx context.Context, key, chanID, subptopic, token string) error
+	Unsubscribe(ctx context.Context, key, domainID, chanID, subptopic, token string) error
 
 	// DisconnectHandler method is used to disconnected the client
 	DisconnectHandler(ctx context.Context, chanID, subptopic, token string) error
```
Comment (arvindh123) [inline coap/adapter.go:40]: Please add domain id to disconnect handler

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Comment by dborovcanin** [comment]
@felixgateru please address comments so we can re-review.

**Review by dborovcanin — APPROVED** [review]
