### PR TITLE
SMQ-2719 - Update list domain invitations endpoint

### LINKED ISSUE #2719: Bug: Invitations could not be filter by domain_id by invitee
### What were you trying to achieve?

As an invitee user, tried retrieve the received invitation by domain_id 

### What are the expected results?

Response with applied filter `domain_id`

### What are the received results?

Authorization error

### Steps To Reproduce

1.) Create new domain 
2.) Send invitation to another user 
3.) Login as another user to which you have sent invitation
4.) List the invitations with `domain_id` filter
```bash
curl --location 'http://localhost/invitations?domain_id=<domain_id>' \
--header 'Authorization: Bearer <TOKEN>'
```

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

At present we have single domain service function `ListInvitation` , So we could not allow invitee to filter by domain_id, 
We need to have different domain service function and repo function `ListInviteeInvitations` ,  which should list only the invitee user received invitations. Then we can able to apply filter in repo.

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a refactor as it enables dedicated invitee invitation listing by adding `ListInviteeInvitations`

## What does this do?
This pr:
- Adds ability for users to list domain invitations specifically addressed to them using `ListDomainInvitations`
- Updates the authorization check for this

## Which issue(s) does this PR fix/relate to?

- Related Issue #2719
- Resolves #2719 

## Have you included tests for your changes?
Yes, tests have been included

## Did you document any new/modified feature?
Yes, in code documentation is included

### CODE REVIEW

File: domains/middleware/authorization.go [hunk 1]
```diff
@@ -253,6 +253,21 @@ func (am *authorizationMiddleware) ListInvitations(ctx context.Context, session
 	return am.svc.ListInvitations(ctx, session, page)
 }
 
+func (am *authorizationMiddleware) ListInviteeInvitations(ctx context.Context, session authn.Session, page domains.InvitationPageMeta) (invs domains.InvitationPage, err error) {
```
Comment (arvindh123) [inline domains/middleware/authorization.go]: I think we can have two function , 
`ListInvitations` and `ListDomainInvitations`

- `ListInvitations` list invitee invitations 
- `ListDomainInvitations` list all the invitations sent on domain 

No need for `CheckAdmin` because SuperAdmin inherently get the permission

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — CHANGES_REQUESTED** [review]
I could not see like this in `domainID: chi.URLParam(r, "domainID"),` in decoder requests of  SendDomainInvitations, ListDomainInvitation

**Comment by felixgateru** [comment]
> I could not see like this in `domainID: chi.URLParam(r, "domainID"),` in decoder requests of SendDomainInvitations, ListDomainInvitation

They are obtained from the session since it already fetches them from the url

File: domains/api/http/endpoint.go [hunk 2]
```diff
@@ -236,7 +236,7 @@ func listDomainInvitationsEndpoint(svc domains.Service) endpoint.Endpoint {
 		}
 		req.InvitationPageMeta.DomainID = session.DomainID
```
Comment (arvindh123) [inline domains/api/http/endpoint.go]: Please move this logic to service layer

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — CHANGES_REQUESTED** [review]
https://github.com/absmach/supermq/blob/f3c11ef4eaeacdf1115ac9b82158d3f253240c00/domains/api/http/endpoint.go#L261
This might not be needed , Please verify this one

File: domains/events/events.go [hunk 3]
```diff
@@ -378,6 +380,37 @@ func (lie listInvitationsEvent) Encode() (map[string]interface{}, error) {
...
+		"token_type":      lie.session.Type.String(),
+		"super_admin":     lie.session.SuperAdmin,
+	}
+
+	if lie.InvitedBy != "" {
+		val["invited_by"] = lie.InvitedBy
+	}
+	if lie.DomainID != "" {
+		val["domain_id"] = lie.DomainID
+	}
```
Comment (arvindh123) [inline domains/events/events.go]: Domain ID is mandatory, It could not be optional 

in `listInvitationsEvent` super admin is not required , instead we can have  requested user id

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — DISMISSED** [review]

File: domains/events/events.go [hunk 4]
```diff
@@ -351,10 +353,43 @@ type listInvitationsEvent struct {
...
+	if lie.RoleID != "" {
+		val["role_id"] = lie.RoleID
+	}
+	if lie.State.String() != "" {
+		val["state"] = lie.State.String()
+	}
```
Comment (dborovcanin) [inline domains/events/events.go]: This will never be true. Please check `State`.

**Review by dborovcanin — CHANGES_REQUESTED** [review]
