### PR TITLE
SMQ-2743 - Update group description to nullable string

### LINKED ISSUE #2743: Bug: Unable to update group description to an empty string
### What were you trying to achieve?

Updating a group's description to an empty string.

### What are the expected results?

A user should be able to update description to an empty string.

### What are the received results?

It defaults back to the previously set description. This means that once a user updates the description, they can never revert to having no description.  The same issue applies to metadata. 

### Steps To Reproduce

1. Create a group with a description
2. Try updating the description to an empty string

### In what environment did you encounter the issue?

Latest magistrala

### Additional information you deem important

https://jam.dev/c/f6a6867d-d291-4b5d-9807-6fa998a5ea66

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #2743 

## What does this do?
- It updates the group description to pointer to allow the setting of description to an empty string.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2743
- Resolves #2743

## Have you included tests for your changes?
Yes

## Did you document any new/modified feature?
No

### CODE REVIEW

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Use `internal/nullable` instead. Move it to the `pkg` if needed.

File: groups/service.go [hunk 1]
```diff
@@ -60,6 +60,8 @@ func (svc service) CreateGroup(ctx context.Context, session smqauthn.Session, g
 	g.CreatedAt = time.Now().UTC()
 	g.Domain = session.DomainID
 
+	fmt.Printf("am here and g is %+v\n", g)
+
```
Comment (dborovcanin) [inline groups/service.go]: Remove debug code.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: groups/groups.go [hunk 2]
```diff
@@ -29,7 +30,7 @@ type Group struct {
 	Domain                    string                    `json:"domain_id,omitempty"`
 	Parent                    string                    `json:"parent_id,omitempty"`
 	Name                      string                    `json:"name"`
-	Description               string                    `json:"description,omitempty"`
+	Description               nullable.Value[string]    `json:"description,omitempty"`
```
Comment (arvindh123) [inline groups/groups.go:33]: Please revert back to string

File: groups/api/http/requests.go [hunk 3]
```diff
@@ -24,7 +25,7 @@ func (req createGroupReq) validate() error {
 type updateGroupReq struct {
 	id          string
 	Name        string                 `json:"name,omitempty"`
-	Description string                 `json:"description,omitempty"`
+	Description nullable.Value[string] `json:"description,omitempty"`
```
Comment (arvindh123) [inline groups/api/http/requests.go:28]: Please revert back to string

File: groups/postgres/groups.go [hunk 4]
```diff
@@ -1183,12 +1184,16 @@ func toDBGroup(g groups.Group) (dbGroup, error) {
 	if g.UpdatedBy != "" {
 		updatedBy = &g.UpdatedBy
 	}
+	var desc sql.NullString
+	if g.Description.Set {
```
Comment (arvindh123) [inline groups/postgres/groups.go]: Please change logic like given below 
```suggestion
	if g.Description != "" {
		desc = sql.NullString{String: g.Description.Value, Valid: true}
	}
```

File: groups/postgres/groups.go [hunk 5]
```diff
@@ -1230,12 +1235,20 @@ func toGroup(g dbGroup) (groups.Group, error) {
 		}
 	}
 
+	var desc nullable.Value[string]
+	var err error
+	if g.Description.Valid {
+		if desc, err = nullable.ParseString(g.Description.String); err != nil {
+			return groups.Group{}, errors.Wrap(errors.ErrMalformedEntity, err)
+		}
+	}
```
Comment (arvindh123) [inline groups/postgres/groups.go]: We can have code like this 
```suggestion
	var desc string
	if g.Description.Valid {
		desc = g.Description.String
	}
```

File: pkg/groups/events/consumer/decode.go [hunk 6]
```diff
@@ -81,7 +82,11 @@ func ToGroups(data map[string]interface{}) (groups.Group, error) {
 
 	desc, ok := data["description"].(string)
 	if ok {
-		g.Description = desc
+		res, err := nullable.ParseString(desc)
```
Comment (arvindh123) [inline pkg/groups/events/consumer/decode.go]: This can be reverted if the previous changes are implemented

File: pkg/sdk/groups_test.go [hunk 7]
```diff
@@ -75,6 +76,10 @@ func TestCreateGroup(t *testing.T) {
 	uGroup.Metadata = groups.Metadata{
 		"key": make(chan int),
 	}
+
+	desc, err := nullable.ParseString(description)
```
Comment (arvindh123) [inline pkg/sdk/groups_test.go]: This can be revert able if the previous mentioned changes are implemented

File: pkg/sdk/setup_test.go [hunk 8]
```diff
@@ -106,13 +107,20 @@ func convertGroup(g sdk.Group) groups.Group {
 	if err != nil {
 		return groups.Group{}
 	}
+	var desc nullable.Value[string]
+	if g.Description != "" {
```
Comment (arvindh123) [inline pkg/sdk/setup_test.go:111]: Same here

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: groups/postgres/groups.go [hunk 9]
```diff
@@ -1230,12 +1235,20 @@ func toGroup(g dbGroup) (groups.Group, error) {
 		}
 	}
 
+	var desc nullable.Value[string]
+	var err error
+	if g.Description.Valid {
+		if desc, err = nullable.ParseString(g.Description.String); err != nil {
```
Comment (arvindh123) [inline groups/postgres/groups.go]: I think no need for parse 
you can simple have like below
```go
desc : nulllable.Value{Set: g.Descritpion.String, Valid: g.Description.Valid}
```

File: pkg/groups/events/consumer/decode.go [hunk 10]
```diff
@@ -81,7 +82,11 @@ func ToGroups(data map[string]interface{}) (groups.Group, error) {
...
+		if err != nil {
```
Comment (arvindh123) [inline pkg/groups/events/consumer/decode.go]: I think error can be omitted for ParseString

File: pkg/sdk/groups_test.go [hunk 11]
```diff
@@ -75,6 +76,10 @@ func TestCreateGroup(t *testing.T) {
...
+	assert.Nil(t, err)
```
Comment (arvindh123) [inline pkg/sdk/groups_test.go]: Same here

File: pkg/sdk/setup_test.go [hunk 12]
```diff
@@ -106,13 +107,20 @@ func convertGroup(g sdk.Group) groups.Group {
...
+		desc, err = nullable.ParseString(g.Description)
```
Comment (arvindh123) [inline pkg/sdk/setup_test.go]: Same here

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: pkg/sdk/groups_test.go [hunk 13]
```diff
@@ -677,6 +681,9 @@ func TestUpdateGroup(t *testing.T) {
 
 	group.ID = generateUUID(t)
 
+	updatedDesc, err := nullable.ParseString(updatedDescription)
```
Comment (arvindh123) [inline pkg/sdk/groups_test.go]: Here also the same, Can we have another function in nullable which convert normal string to nullable string like below 

```go
func String(s string) (Value[string]) {
    return Value[string]{Set: True, Value: s}
}
```

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: pkg/sdk/groups_test.go (hunk 13 above)
Comment (dborovcanin) [reply pkg/sdk/groups_test.go]: No need for function, we can directly use `Value[string]{Set: True, Value: updatedDescription}`

File: groups/api/http/decode_test.go [hunk 14]
```diff
@@ -14,10 +14,13 @@ import (
 	api "github.com/absmach/supermq/api/http"
 	apiutil "github.com/absmach/supermq/api/http/util"
 	"github.com/absmach/supermq/groups"
+	"github.com/absmach/supermq/internal/nullable"
 	"github.com/absmach/supermq/pkg/errors"
 	"github.com/stretchr/testify/assert"
 )
 
+var description = "random"
```
Comment (arvindh123) [inline groups/api/http/decode_test.go]: Description is already defined in `endpoints_test.go` Why we could not reuse the same in this file ?

File: groups/postgres/groups.go [hunk 15]
```diff
@@ -1183,12 +1184,16 @@ func toDBGroup(g groups.Group) (dbGroup, error) {
...
+	if g.Description.Set {
+		desc = sql.NullString{String: g.Description.Value, Valid: true}
+	}
 	return dbGroup{
 		ID:          g.ID,
 		Name:        g.Name,
 		ParentID:    parentID,
 		DomainID:    g.Domain,
-		Description: g.Description,
+		Description: desc,
```
Comment (arvindh123) [inline groups/postgres/groups.go]:
```suggestion
		Description: sql.NullString{String: g.Description.Value, Valid: g.Description.Set},
```

File: groups/postgres/groups.go [hunk 16]
```diff
@@ -1230,12 +1235,17 @@ func toGroup(g dbGroup) (groups.Group, error) {
...
+		desc = nullable.Value[string]{Value: g.Description.String, Set: g.Description.Valid}
+	}
+
 	return groups.Group{
 		ID:                        g.ID,
 		Name:                      g.Name,
 		Parent:                    parentID,
 		Domain:                    g.DomainID,
-		Description:               g.Description,
+		Description:               desc,
```
Comment (arvindh123) [inline groups/postgres/groups.go]:
```suggestion
		Description:               nullable.Value[string]{Value: g.Description.String, Set: g.Description.Valid},
```

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: pkg/groups/events/consumer/decode.go [hunk 17]
```diff
@@ -81,7 +82,8 @@ func ToGroups(data map[string]interface{}) (groups.Group, error) {
 
 	desc, ok := data["description"].(string)
 	if ok {
-		g.Description = desc
+		res := nullable.Value[string]{Set: true, Value: desc}
+		g.Description = res
```
Comment (arvindh123) [inline pkg/groups/events/consumer/decode.go]:
```suggestion
		g.Description = nullable.Value[string]{Set: true, Value: desc}
```

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — DISMISSED** [review]

**Review by arvindh123 — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]
