### PR TITLE
MG-2354 - Fix Update Bootstrap Config State

### LINKED ISSUE #2354: Bug: Update Bootstrap Config State Updates all Configs States
### What were you trying to achieve?

Update the state of a boostrap config

### What are the expected results?

When I update the state of a bootstrap config it only updates the state of the config with the  specified thingId

### What are the received results?

When I update the state of a bootstrap config it updates the state of all the bootstrap configs present
https://jam.dev/c/5f24773b-0d3e-43ac-a21e-6bd78bce2cf9

### Steps To Reproduce

1. In the latest magistrala, have a domain present, with multiple things and multiple bootstrap configs
2. Create a token with the domain
3. Fetch the list of boostrapConfigs and note the state
4. Change the state of a bootstrap config
5. list the configs again and check the state.

### In what environment did you encounter the issue?

Latest magistrala environment

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?
This is a bug fix because it fixes the following issue: absmach/supermq#2354 

## What does this do?
It changes how the `ConnectThing` and `DisconnectThing` in repo makes the query. It ensure that not all rows are updated

## Which issue(s) does this PR fix/relate to?
- Related Issue absmach/supermq#2354 
- Resolves absmach/supermq#2354 

## Have you included tests for your changes?
Yes, I have included tests for my changes.

## Did you document any new/modified feature?
N/A

### CODE REVIEW

**Comment by JeffMboya** [comment]
@nyagamunene why is method `changeState` removed?

**Comment by dborovcanin** [comment]
Changing state does not make much sense anymore from the Bootstrap perspective. I.e. we have a manual option to change Things' state now, and the state has nothing to do with BS configuration. @arvindh123 Please review.

**Comment by nyagamunene** [comment]
> @nyagamunene why is method `changeState` removed?

The reason was that the `ConnectThingHandler` and the `DisconnectThingHandler` methods consume events from things and when there is a change it updates the repo accordingly hence no need for `changeState` which makes it redundant.

File: bootstrap/service.go [hunk 1]
```diff
@@ -146,6 +146,23 @@ func (bs bootstrapService) Add(ctx context.Context, token string, cfg Config) (C
...
+		if err != nil {
+			return Config{}, errors.Wrap(svcerr.ErrMalformedEntity, err)
+		}
+		for _, thing := range tp.Things {
+			if thing.ID == cfg.ThingID {
+				state = Active
+				break
+			}
+		}
+	}
```
Comment (JeffMboya) [inline bootstrap/service.go]: @nyagamunene this will be resolve through a separate endpoint here: https://github.com/absmach/magistrala/issues/2301. @arvindh123  please confirm

**Comment by arvindh123** [comment]
From the below logs we can see on bootstrap state change , bootstrap service sends connect/disconnect from channel to things service. 
Then things service emit the connect/disconnect event, which is again consumed by bootstrap service 
```
{"time":"2024-07-25T09:21:48.15854206Z","level":"INFO","msg":"Disconnect thing handler completed successfully","duration":"8.397523ms","channel_id":"6edf5552-dd76-4d9c-ad4f-f62481ad4c58","thing_id":"7af3a95c-a1fa-4379-8f0b-fc7e8a5af3a3"}
```
```
{"time":"2024-07-25T09:21:48.182582857Z","level":"INFO","msg":"Change thing state completed successfully","duration":"130.098491ms","id":"7af3a95c-a1fa-4379-8f0b-fc7e8a5af3a3","state":0}
```

The problem happen exactly at Disconnect and Connect handlers in repo where there is wrong query 
 ```sql 
 UPDATE configs SET state = $1 WHERE EXISTS ( SELECT 1 FROM connections WHERE config_id = $2 AND channel_id = $3)
 ```
This query always update all the columns in bootstrap service.

**Review by arvindh123 — APPROVED** [review]
LGTM

**Review by JeffMboya — APPROVED** [review]

**Review by ianmuchyri — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]
