### PR TITLE
SMQ-3016 - Fix false positive http logging

### LINKED ISSUE #3016: Bug: Http messaging returning false positive logs
### What were you trying to achieve?

Send message with invalid client key

### What are the expected results?

Log that publish has failed

### What are the received results?

Image

### Steps To Reproduce

_No response_

### In what environment did you encounter the issue?

Docker environment, running latest

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a bug fix because it fixes the following issue:#3016

## What does this do?
This pr:
- refactors handle logging middleware to fix false positive logs and align with rest of code.
- changes logging level of MQTT successful disconnect from `Error` to `Info`

## Which issue(s) does this PR fix/relate to?

- Resolves #3016 

## Have you included tests for your changes?
No, code covered by tests

## Did you document any new/modified feature?
No

### CODE REVIEW

File: pkg/messaging/handler/logging.go [hunk 1]
```diff
@@ -20,71 +20,141 @@ type loggingMiddleware struct {
...
 	return lm.svc.AuthConnect(ctx)
 }
 
 // AuthPublish implements session.Handler.
 func (lm *loggingMiddleware) AuthPublish(ctx context.Context, topic *string, payload *[]byte) (err error) {
-	defer lm.logAction("AuthPublish", &[]string{*topic}, time.Now(), err)
+	defer func(begin time.Time) {
+		args := []any{
+			slog.String("duration", time.Since(begin).String()),
+			slog.String("topic", *topic),
```
Comment (dborovcanin) [inline pkg/messaging/handler/logging.go]: Add a nil check just in case the `topic` is nil (for whatever reason, probably an error elsewhere).

File: pkg/messaging/handler/logging.go [hunk 2]
```diff
@@ -20,71 +20,141 @@ type loggingMiddleware struct {
...
 	return lm.svc.AuthPublish(ctx, topic, payload)
 }
 
 // AuthSubscribe implements session.Handler.
 func (lm *loggingMiddleware) AuthSubscribe(ctx context.Context, topics *[]string) (err error) {
-	defer lm.logAction("AuthSubscribe", topics, time.Now(), err)
+	defer func(begin time.Time) {
+		args := []any{
+			slog.String("duration", time.Since(begin).String()),
+			slog.Any("topics", *topics),
```
Comment (dborovcanin) [inline pkg/messaging/handler/logging.go]: The same.

File: pkg/messaging/handler/logging.go [hunk 3]
```diff
@@ -20,71 +20,141 @@ type loggingMiddleware struct {
...
 }
 
 // Publish logs the publish request. It logs the time it took to complete the request.
 // If the request fails, it logs the error.
 func (lm *loggingMiddleware) Publish(ctx context.Context, topic *string, payload *[]byte) (err error) {
-	defer lm.logAction("Publish", &[]string{*topic}, time.Now(), err)
+	defer func(begin time.Time) {
+		args := []any{
+			slog.String("duration", time.Since(begin).String()),
+			slog.String("topic", *topic),
```
Comment (dborovcanin) [inline pkg/messaging/handler/logging.go]: And here.

File: pkg/messaging/handler/logging.go [hunk 4]
```diff
@@ -20,71 +20,141 @@ type loggingMiddleware struct {
...
 	return lm.svc.Subscribe(ctx, topics)
 }
 
 // Unsubscribe implements session.Handler.
 func (lm *loggingMiddleware) Unsubscribe(ctx context.Context, topics *[]string) (err error) {
-	defer lm.logAction("Unsubscribe", topics, time.Now(), err)
+	defer func(begin time.Time) {
+		args := []any{
+			slog.String("duration", time.Since(begin).String()),
+			slog.Any("topics", topics),
```
Comment (dborovcanin) [inline pkg/messaging/handler/logging.go]: Use `slog.String("topics", strings.Join(topics, ", ")`.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
