### PR TITLE
MF-1681 - Failed to reconnect to NATS

### LINKED ISSUE #1681: Failed to reconnect to NATS
**BUG REPORT**

1. What were you trying to achieve?
Publishing of message from MQTT to NATS

2. What are the expected results?
Publishing of message from MQTT to NATS

3. What are the received results?
 Message not published ,got the error message `Error publishing to Mainflux nats: connection closed`
 
4. What are the steps to reproduce the issue?
Kill the NATS connection and wait for some time, 
Then try to publish via MQTT. The same goes for HTTP and other adapters. Nats auto-reconnect gets exhausted and the connection is permanently closed.

5. In what environment did you encounter the issue?
Docker 20.10.21, Docker Compose 2.14.1, Linux, Latest Mainflux version

6. Additional information you deem important:
Nats reconnect param can be configured to keep trying to re-establish connection indefinitely.

### PR DESCRIPTION
**Pull request by dborovcanin**
Signed-off-by: dusanb94 <dusan.borovcanin@mainflux.com>

### What does this do?
Currently, connection to NATS defaults to a max of 60 reconnect attempts before giving up and leaving the connection permanently closed. This approach causes the problem in case the service has been disconnected from the NATS server for whatever reasons.
This pull request makes a connection to NATS to never give up on trying to reconnect.

### Which issue(s) does this PR fix/relate to?
This pull request fixes #1681.

### List any changes that modify/break current functionality
There are no such changes.

### Have you included tests for your changes?
N/A

### Did you document any new/modified functionality?
N/A

### Notes
N/A

### CODE REVIEW

File: pkg/messaging/nats/publisher.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ type publisher struct {
 
 // NewPublisher returns NATS message Publisher.
 func NewPublisher(url string) (messaging.Publisher, error) {
-	conn, err := broker.Connect(url)
+	conn, err := broker.Connect(url, broker.MaxReconnects(-1))
```
Comment (drasko) [inline pkg/messaging/nats/publisher.go]: I would define this constant somewhere and give it a self-documenting name, like `tryForever`, or you can leave a comment what this `-1` means (for someone reading the code for the first time)

**Review by drasko — CHANGES_REQUESTED** [review]

**Review by drasko — APPROVED** [review]
LGTM
