### PR TITLE
MF-1801 - Improve error value returned for invalid thing

### LINKED ISSUE #1801: Improve error response for invalid thing_id on bootstaping
**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   The current response to an invalid thing_id is the same as a failed configuration creation on Bootstrap.
   https://github.com/mainflux/mainflux/blob/7cc1dd9f891628608b004dd99932f070e36b3f40/bootstrap/service.go#L144
   https://github.com/mainflux/mainflux/blob/7cc1dd9f891628608b004dd99932f070e36b3f40/bootstrap/service.go#L159
   The response for an invalid thing can be different to improve error identification

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
Should have

### PR DESCRIPTION
**Pull request by SammyOina**
Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
Improves error returned when a thing does not exist during bootstrapping.

### Which issue(s) does this PR fix/relate to?
Resolves #1801 

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### CODE REVIEW

File: bootstrap/service.go [hunk 1]
```diff
@@ -40,6 +40,7 @@ var (
 	errDisconnectThing    = errors.New("failed to disconnect thing")
 	errCheckChannels      = errors.New("failed to check if channels exists")
 	errConnectionChannels = errors.New("failed to check channels connections")
+	errThingNotExist      = errors.New("failed to find thing")
```
Comment (dborovcanin) [inline bootstrap/service.go]: Rename to `errThingNotFound`.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM
