### PR TITLE
NOISSUE - Fix publisher id on message published by user

### LINKED ISSUE #3311: Bug: Publisher on message sent by non domain admin has domain id in publisher
### What were you trying to achieve?

View channel messages

### What are the expected results?

The publisher for a message sent via http by a non admin user should have the userID only as the publisher

### What are the received results?

The publisher is the userID concatenated with the domainID

### Steps To Reproduce

1. Send message via HTTP with a non admin user
2. Use readers to view messages

### In what environment did you encounter the issue?

Local docker compose deployment

### Additional information you deem important

Image

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #3311

## What does this do?
This pr fixes the issue with the publisher having the domain id

## Which issue(s) does this PR fix/relate to?

- Resolves #3311

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
No

### CODE REVIEW

File: http/handler.go [hunk 1]
```diff
@@ -258,29 +258,29 @@ func (h *handler) authAccess(ctx context.Context, username, password, domainID,
 	return id, nil
 }
 
-func (h *handler) authenticate(ctx context.Context, authType, token, domainID string) (string, error) {
+func (h *handler) authenticate(ctx context.Context, authType, token, domainID string) (string, string, error) {
```
Comment (dborovcanin) [inline http/handler.go:261]: This looks a bit obscure now. Let's keep a logic clear - this method returns an ID or error rather than 3 values. Construct subject in the caller method if needed.
```go
id, err := h.authenticate
...
if clientType == policies.UserType {
id = policies.EncodeDomainUserID(domainID, authnSession.UserID)
}
....
```

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: http/handler.go (hunk 1 above)
Comment (felixgateru) [reply http/handler.go:261]: the subject for authorization depends on whether the client of UserType is an admin or not an admin, that is why i proposed the 3 values. Otherwise we would need to return the role from the session to construct the subject in the caller

Comment (dborovcanin) [reply http/handler.go:261]: Let's not return role. Can we always return subject from here in that case?

Comment (dborovcanin) [reply http/handler.go:261]: I.e. does that make any difference for health check (where ID is used)?

Comment (felixgateru) [reply http/handler.go:261]: it makes a difference in the publisher field for the message payload. If we always return the subject we get something like this:
image

**Review by dborovcanin — APPROVED** [review]
