### PR TITLE
MF-579 Things & Channels returns 404 when not found or ID is malformed, not 500

### LINKED ISSUE #579: Invalid ID format results in Internal Server Error
**BUG REPORT**

1. What were you trying to achieve?
I'm trying to fetch a Thing by sending an ID in the wrong format.

2. What are the expected results?
I expect to receive 404 or 400. I'd prefer 404 since the Thing with the given ID does not exist. 

3. What are the received results?
I get 500, Internal Server Error.

4. What are the steps to reproduce the issue?
    - Create the user and log in.
    - Try to fetch a Thing (or Channel) by sending an invalid formatted ID (not in UUID format).

5. In what environment did you encounter the issue?
I run Mainflux version 0.7.0 on my local machine.

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Vladimir Starcevic <vstarcevic@gmail.com>

### What does this do?
Retrieving things or channels by Id, returns 404 when not found or id is malformed, not 500
### Which issue(s) does this PR fix/relate to?
Resolves #579
### List any changes that modify/break current functionality
NA
### Have you included tests for your changes?
Yes
### Did you document any new/modified functionality?
NA

### CODE REVIEW

**Comment by manuio** [comment]
@vstarcevic this is the expected behavior. `404` is `not found ` `500` is I`nternal server error`

File: .gitignore [hunk 1]
```diff
@@ -2,3 +2,5 @@ build
 
 site/
 
+# editor specific
+.vscode
```
Comment (anovakovic01) [inline .gitignore]: You should add this to your local `.gitignore`. I think that we don't need it on remote repository.

File: things/postgres/things.go [hunk 2]
```diff
@@ -89,10 +89,7 @@ func (tr thingRepository) RetrieveByID(owner, id string) (things.Thing, error) {
 
 	if err != nil {
 		empty := things.Thing{}
-		if err == sql.ErrNoRows {
-			return empty, things.ErrNotFound
-		}
-		return empty, err
+		return empty, things.ErrNotFound
```
Comment (anovakovic01) [inline things/postgres/things.go]: If we do this, we will ignore every other error (like connection errors). I think that this removed `if` should stay. Maybe problem isn't in this part of code.

**Review by anovakovic01 — CHANGES_REQUESTED** [review]

**Review by manuio — DISMISSED** [review]
LGTM

File: things/postgres/things.go (hunk 2 above)
Comment (dborovcanin) [inline things/postgres/things.go]: @vstarcevic This way, all read errors will cause the same NotFound error, which is not what we want. I'd prefer to extract error info from SQL error and check if it's invalid ID format error. Something similar to this: https://github.com/mainflux/mainflux/blob/33008140268cc3d9f5edd3394dce8cbc37f31956/things/postgres/things.go#L64

This is far from perfect because in this case, you extract semantics from the error message string, but it's better than shadowing all the errors with NotFound. Also, there is a way to check if the string is a valid UUID without trying to access a database, which is a more efficient way. Maybe adding something like `Validate()` method to IdentityProvider interface (https://github.com/mainflux/mainflux/blob/master/things/uuid/idp.go)...

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by manuio — DISMISSED** [review]

File: things/postgres/channels_test.go [hunk 3]
```diff
@@ -157,6 +157,11 @@ func TestSingleChannelRetrieval(t *testing.T) {
 			ID:    c.ID,
 			err:   things.ErrNotFound,
 		},
+		"retrieve thing with malformed ID": {
```
Comment (dborovcanin) [inline things/postgres/channels_test.go]: Channel, not Thing.

Comment (ghost) [reply things/postgres/channels_test.go]: Fixed!

**Review by manuio — APPROVED** [review]

**Review by anovakovic01 — APPROVED** [review]
LGTM!

**Review by dborovcanin — APPROVED** [review]
