### PR TITLE
MG-149 - Fix leaking database errors

### LINKED ISSUE #149: Bug: Leaking Database Errors
### What were you trying to achieve?

Update user while metadata contains a Unicode character
```bash
curl -iX PATCH -H "Authorization: Bearer $USER_TOKEN" -H 'Content-Type: application/json' -d '{"metadata": {"": "\u0000"}, "name": ""}' http://localhost:9002/users/00000000-0000-1000-8000-000000000000
```

### What are the expected results?

Failed to update if unsuccessful

### What are the received results?

```bash
HTTP/1.1 500 Internal Server Error
Content-Type: application/json
Date: Wed, 13 Dec 2023 09:28:06 GMT
Content-Length: 105

{"error":"ERROR: unsupported Unicode escape sequence (SQLSTATE 22P05)","message":"update entity failed"}
```

### Steps To Reproduce

1. Run magistrala
2. Create a user
3. Update the use using curl command
```
curl -iX PATCH -H "Authorization: Bearer $USER_TOKEN" -H 'Content-Type: application/json' -d '{"metadata": {"": "\u0000"}, "name": ""}' http://localhost:9002/users/$USER_ID
```

### In what environment did you encounter the issue?

Main branch after commit - `4d038c633aa7c5f499d9590a8ca5cc75f7665654`
Linux

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by 1998-felix**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #149

## What does this do?
Handles errors in the service layer to prevent database errors from leaking to the end user.

## Which issue(s) does this PR fix/relate to?

- Resolves #149

## Have you included tests for your changes?
No,

## Did you document any new/modified feature?
No, since this is a bug fix.

### CODE REVIEW

File: auth/service.go [hunk 1]
```diff
@@ -728,7 +756,11 @@ func (svc service) addDomainPolicies(ctx context.Context, domainID, relation str
 			}
 		}
 	}()
-	return svc.domains.SavePolicies(ctx, pcs...)
+	err = svc.domains.SavePolicies(ctx, pcs...)
+	if err != nil {
+		return errors.Wrap(errAddPolicies, err)
+	}
+	return err
```
Comment (dborovcanin) [inline auth/service.go:763]: Inline:
```go
if err := svc.domains.SavePolicies; err != nil {
    return errors.Wrap
}
return nil
```

File: auth/service.go [hunk 2]
```diff
@@ -670,8 +691,11 @@ func (svc service) UnassignUsers(ctx context.Context, token, id string, userIds
 	}); err != nil {
 		return err
 	}
-
-	return svc.removeDomainPolicies(ctx, id, relation, userIds...)
+	err := svc.removeDomainPolicies(ctx, id, relation, userIds...)
```
Comment (dborovcanin) [inline auth/service.go:694]: Inline.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
