### PR TITLE
SMQ-2865 - Fix listing indirect groups and group related listing of channels and clients

### LINKED ISSUE #2865: Bug: List channels and clients of child group with indirect access returns duplicate entities
### What were you trying to achieve?

List channels and clients of a group which the user has access to via the parent group

### What are the expected results?

List channels and clients associated with the child group

### What are the received results?

Duplicate entries of channels and clients

### Steps To Reproduce

1. Create user1, create domain1, create group1 and group2
2. Make group2 child of group1
3. Create user2 and invite user2 to domain1
4. As user2 create group3 and client1 in domain1
5. Assign group3 as parent group of client1
6. Assign group2 as parent group of group3
7. With user1 list clients of group3

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by felixgateru**
…ents

# What type of PR is this?
This is a bug fix because it fixes the following issue:#2865

## What does this do?
This pr:
- refactors the indirect groups listing query to only include distinct groups on group id

## Which issue(s) does this PR fix/relate to?

- Resolves #2865

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
No

### CODE REVIEW

File: clients/postgres/clients.go [hunk 1]
```diff
@@ -729,8 +729,8 @@ func (repo *clientRepo) userClientBaseQuery(domainID, userID string) string {
 			gr.entity_id, grm.member_id, gr.id, gr."name", g."path", g.id
 	),
 	indirect_child_groups AS (
-		SELECT
-			DISTINCT indirect_child_groups.id as child_id,
+		SELECT DISTINCT ON (indirect_child_groups.id)
+			indirect_child_groups.id AS child_id,
 			indirect_child_groups.*,
```
Comment (arvindh123) [inline clients/postgres/clients.go]: An alternative is replace `direct_groups_with_subgroup` with following 
```sql
	direct_groups_with_subgroup AS (
		SELECT
			g.*,
			gr.entity_id AS entity_id,
			grm.member_id AS member_id,
			gr.id AS role_id,
			gr."name" AS role_name,
			array_agg(DISTINCT all_actions."action") AS actions
		FROM
			groups_role_members grm
		JOIN
			groups_role_actions gra ON gra.role_id = grm.role_id
		JOIN
			groups_roles gr ON gr.id = grm.role_id
		JOIN
			"groups" g ON g.id = gr.entity_id
		JOIN
			groups_role_actions all_actions ON all_actions.role_id = grm.role_id
		LEFT JOIN "groups" g2
			ON g2.path <@ g.path AND nlevel(g2.path) = nlevel(g.path) + 1
		WHERE
			g2.path IS NULL
			AND grm.member_id = '%s'
			AND g.domain_id = '%s'
			AND gra."action" LIKE 'subgroup_client%%'
		GROUP BY
			gr.entity_id, grm.member_id, gr.id, gr."name", g."path", g.id
	),
    ````

**Review by arvindh123 — CHANGES_REQUESTED** [review]
The SQL need to modify

File: clients/postgres/clients.go (hunk 1 above)
Comment (felixgateru) [reply clients/postgres/clients.go]: With this addition, i am not able to list my indirect child groups, only direct groups to the user

Comment (arvindh123) [reply clients/postgres/clients.go]:
```sql
            ON g2.path @> g.path AND nlevel(g.path) = nlevel(g2.path) + 1
```

Does this will works ?

```
ltree @> ltree → boolean
         Is left argument an ancestor of right (or equal)?
```

Comment (felixgateru) [reply clients/postgres/clients.go]: > ```sql
>             ON g2.path @> g.path AND nlevel(g.path) = nlevel(g2.path) + 1
> ```
> 
> Does this will works ?
> 
> ```
> ltree @> ltree → boolean
>          Is left argument an ancestor of right (or equal)?
> ```

This works as well as the original, I have seen on my end it was an issue with ordering of the string variables, i have corrected and am now testing

File: channels/postgres/channels.go [hunk 2]
```diff
@@ -696,8 +696,11 @@ direct_groups_with_subgroup AS (
...
 	JOIN
 		groups_role_actions all_actions ON all_actions.role_id = grm.role_id
+	LEFT JOIN "groups" g2
+		ON g2.path <@ g.path AND nlevel(g2.path) = nlevel(g.path) + 1
 	WHERE
-		grm.member_id = '%s'
+		g2.path IS NULL
+		AND grm.member_id = '%s'
 		AND g.domain_id = '%s'
 		AND gra."action" LIKE 'subgroup_channel%%'
```
Comment (arvindh123) [inline channels/postgres/channels.go]: Please move `g2.path IS NULL` to last in in `WHERE`
```suggestion
	LEFT JOIN "groups" g2
		ON g2.path <@ g.path AND nlevel(g2.path) = nlevel(g.path) + 1
	WHERE
		grm.member_id = '%s'
		AND g.domain_id = '%s'
		AND gra."action" LIKE 'subgroup_channel%%'
		AND g2.path IS NULL
```

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — APPROVED** [review]
