### PR TITLE
MF-1582 - Fix lora-adapter MQTT client

### LINKED ISSUE #1582: Fix lora-adapter MQTT client
**BUG REPORT**

1. What were you trying to achieve?
Fix the lora-adapter MQTT client implementation to subscribe properly to the lora server.
2. What are the expected results?
lora-adapter subscribing and forwarding properly lora messages
3. What are the received results?
lora-adapter not handling properly messages.
4. What are the steps to reproduce the issue?
Configure properly lora-adapter to subscribe to a Lora Server MQTT broker.
5. In what environment did you encounter the issue?
Linux
6. Additional information you deem important:
The bug was introduced in the https://github.com/mainflux/mainflux/pull/1318 PR because the MQTT client handler is using Mainflux message format instead of Lora message.

### PR DESCRIPTION
**Pull request by manuio**
Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

### What does this do?
Fix the lora-adapter MQTT client
### Which issue(s) does this PR fix/relate to?
Resolves #1582

### CODE REVIEW

**Review by mteodor — DISMISSED** [review]

File: cmd/lora/main.go [hunk 1]
```diff
@@ -33,7 +32,10 @@ const (
 	defLogLevel       = "error"
 	defHTTPPort       = "8180"
 	defLoraMsgURL     = "tcp://localhost:1883"
-	defSubTimeout     = "30s" // 30 seconds
+	defLoraMsgTopic   = "application/+/device/+/event/up"
+	defLoraMsgUser    = ""
+	defLoraMsgPass    = ""
+	defLoraMsgTimeout = "30s" // 30 seconds
```
Comment (drasko) [inline cmd/lora/main.go]: Consider removing this comment, it is obvious what `30s` means if the variable is called `...Timeout`

**Review by drasko — CHANGES_REQUESTED** [review]

File: lora/mqtt/sub.go [hunk 2]
```diff
@@ -0,0 +1,56 @@
...
+		svc:    svc,
+		client: client,
+		logger: log,
+	}
+}
+
+// Subscribe subscribes to the Lora MQTT message broker
+func (b broker) Subscribe(subject string) error {
+	s := b.client.Subscribe(subject, 0, b.handleMsg)
+	if err := s.Error(); s.Wait() && err != nil {
```
Comment (dborovcanin) [inline lora/mqtt/sub.go]: I would suggest using `WaitTimeout` to prevent infinite wait.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by mteodor — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]
