### PR TITLE
MF-1099 - Add email subdomain validator

### LINKED ISSUE #1099: Can't create user with sub-domain email address.
**BUG REPORT**

1. What were you trying to achieve?
  I try to create user with email in format of 2nd or more sub domain, example: john.doe@123.123.com or john.doe@abc.xyz.com. I got fail on both mainflux-cli and HTTP.

mainflux-cli provision test -- success
mainflux-cli users create john.doe@mail.com -- success
mainflux-cli users create john.doe@123.com -- success
mainflux-cli users create john.doe@123.123.com -- failed: invalid argument passed

curl -s -S -i --cacert docker/ssl/certs/ca.crt -X POST -H "Content-Type: application/json" https://localhost/users -d '{"email":"john.doe@xyz.com", "password":"12345678"}' -- success

curl -s -S -i --cacert docker/ssl/certs/ca.crt -X POST -H "Content-Type: application/json" https://localhost/users -d '{"email":"john.doe@abc.xyz.com", "password":"12345678"}' -- failed: malformed entity specification'

2. What are the expected results?
 It should be able to create user with the usual email format. 

3. What are the received results?

 Error when create user using mainflux-cli:
`invalid argument passed`

 Error when create user via HTTP:

 HTTP/2 400
server: nginx/1.16.0
date: Sun, 05 Apr 2020 14:14:13 GMT
content-type: application/json
content-length: 43

{"error":"malformed entity specification"}

 Server log:
`mainflux-users     | {"level":"warn","message":"Failed to decode user credentials: malformed entity specification","ts":"2020-04-05T14:24:52.056427158Z"}`

4. What are the steps to reproduce the issue?
 
5. In what environment did you encounter the issue?
 Mainflux 0.10.1 on Debian 9.11

6. Additional information you deem important:
  I intend to install the IoT platform for use in my faculty to teach students and do research. This system is a closed service. All members use the email created by the university as the user. Our university email format is user@rmuti.ac.th, which has more than 1 domain level.

### PR DESCRIPTION
**Pull request by manuio**
Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

Resolves #1099

### CODE REVIEW

File: users/users.go [hunk 1]
```diff
@@ -80,11 +81,21 @@ func isEmail(email string) bool {
...
 
 	hs := strings.Split(host, dotSeparator)
-	if len(hs) != 2 {
+	if len(hs) < 2 {
 		return false
 	}
 	domain, ext := hs[0], hs[1]
 
+	// Check subdomain and validate
+	if len(hs) == 3 {
```
Comment (drasko) [inline users/users.go]: Why 3? Can there be multiple subdomains (I do not know, but theorethically stere can be sub-subdomain)?

**Review by drasko — CHANGES_REQUESTED** [review]

**Review by drasko — DISMISSED** [review]
LGTM

**Review by blokovi — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]
