### PR TITLE
MG-2330 - Fix non admins search with identity

### LINKED ISSUE #2330: Users are able to search other users via identity
### What were you trying to achieve?

I am searching users as a non-admin user.

### What are the expected results?

I use  URL in form of `http://localhost:{{users_port}}/users?identity=absmach` and I am able to see a single user. Since user identity is actually users' emails, this means that we leak that information. While I can't see the full address, I still can use it as filter criteria.

### What are the received results?

I receive a limited user scope response, but still can filter users by the criteria.

### Steps To Reproduce

Run composition and provision a couple of users. Try to do search in the form provided above.

### In what environment did you encounter the issue?

I'm using the latest MG and the latest Docker.

### Additional information you deem important

N/A

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #2330 

## What does this do?
It restricts normal users from searching with `identity`.

## Which issue(s) does this PR fix/relate to?
- Related Issue #2330
- Resolves #2330

## Have you included tests for your changes?
No.

## Did you document any new/modified feature?
No

### CODE REVIEW

File: pkg/clients/postgres/clients.go [hunk 1]
```diff
@@ -482,7 +482,7 @@ func PageQuery(pm clients.Page) (string, error) {
 	if pm.Name != "" {
 		query = append(query, "name ILIKE '%' || :name || '%'")
 	}
-	if pm.Identity != "" {
+	if pm.Identity != "" && pm.Role == clients.AdminRole {
```
Comment (arvindh123) [inline pkg/clients/postgres/clients.go]: Instead of chaning here in service layer, If  request user is not user admin , then create new pagemeta with limited (required) fields like only with id, name or may be you can add  tag

image

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: pkg/clients/postgres/clients.go (hunk 1 above)
Comment (nyagamunene) [reply pkg/clients/postgres/clients.go]: I have implemented as per your suggestion but the superadmin role is not set to `all` anywhere so I have left that line of code.

File: users/service.go [hunk 2]
```diff
@@ -189,7 +189,21 @@ func (svc service) ListClients(ctx context.Context, token string, pm mgclients.P
 		return pg, err
 	}
 
-	pg, err := svc.clients.SearchClients(ctx, pm)
+	// Return empty page if user is not super admin
+	// And search criteria by identity
+	if pm.Identity != "" {
+		return mgclients.ClientsPage{}, nil
+	}
+
```
Comment (arvindh123) [inline users/service.go]: We can remove this lines, since we are creating new page in below line with omitting the identity from actual page request 
```suggestion
```

**Review by arvindh123 — CHANGES_REQUESTED** [review]
Please test the suggestion and let us know

File: users/service.go (hunk 2 above)
Comment (nyagamunene) [reply users/service.go]: By removing that line the result is not an empty `clientspage` since it is as if we are passing a search query with empty parameters which returns all the clients.

Comment (arvindh123) [reply users/service.go]: Then we should check for other query params like `tag` and `metadata`
So code becomes like

```go
// Return empty page if user is not super admin
// And search criteria by identity
if pm.Identity != "" {
	return mgclients.ClientsPage{}, nil
}

// Return empty page if user is not super admin
// And search criteria by identity
if pm.Tag != "" { 
    return mgclients.ClientsPage{}, nil
}

// Return empty page if user is not super admin
// And search criteria by identity

if pm.Metadata != "" { 
    return mgclients.ClientsPage{}, nil
}
``` 
This will looks like validation of input. 

So @dborovcanin how we can proceed ? 

At present known options 
- Validation of inputs in service for non-admins.
- Having seperate serach endpoint.

If you have any other idea , please let us know here

Comment (dborovcanin) [reply users/service.go]: Let's switch to the search endpoint.

File: users/api/requests.go [hunk 3]
```diff
@@ -89,6 +89,29 @@ func (req listClientsReq) validate() error {
 	return nil
 }
 
+type searchClientsReq struct {
+	token    string
+	Offset   uint64
+	Limit    uint64
+	Identity string
+	Name     string
```
Comment (arvindh123) [inline users/api/requests.go]: `Identity` is not required

File: users/service.go [hunk 4]
```diff
@@ -189,7 +189,15 @@ func (svc service) ListClients(ctx context.Context, token string, pm mgclients.P
...
 	}
 
-	pg, err := svc.clients.SearchClients(ctx, pm)
+	page := mgclients.Page{
+		Offset: pm.Offset,
+		Limit:  pm.Limit,
+		Name:   pm.Name,
+		Id:     pm.Id,
+		Role:   mgclients.UserRole,
+	}
```
Comment (arvindh123) [inline users/service.go]: If user is non super admin then don't allow to list the users

File: users/service.go [hunk 5]
```diff
@@ -200,6 +208,31 @@ func (svc service) ListClients(ctx context.Context, token string, pm mgclients.P
...
+	if err != nil {
+		return mgclients.ClientsPage{}, err
+	}
+	if err := svc.checkSuperAdmin(ctx, userID); err == nil {
+		pg, err := svc.clients.SearchClients(ctx, pm)
+		if err != nil {
+			return mgclients.ClientsPage{}, errors.Wrap(svcerr.ErrViewEntity, err)
+		}
+		return pg, err
+	}
```
Comment (arvindh123) [inline users/service.go]: No need for super admin check here 
we can support only search by `Name` i.e `Username` or `ID` and we should not support search by `Identity`.

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by dborovcanin — COMMENTED** [review]
@arvindh123 Please review.

File: users/service.go [hunk 6]
```diff
@@ -180,24 +180,38 @@ func (svc service) ListClients(ctx context.Context, token string, pm mgclients.P
...
-	if err := svc.checkSuperAdmin(ctx, userID); err == nil {
-		pm.Role = mgclients.AllRole
-		pg, err := svc.clients.RetrieveAll(ctx, pm)
-		if err != nil {
-			return mgclients.ClientsPage{}, errors.Wrap(svcerr.ErrViewEntity, err)
-		}
-		return pg, err
+	if err := svc.checkSuperAdmin(ctx, userID); err != nil {
+		return mgclients.ClientsPage{}, errors.Wrap(svcerr.ErrViewEntity, err)
 	}
```
Comment (arvindh123) [inline users/service.go:185]: `svc.checkSuperAdmin` have already wrapped with service error 
No need for wrap with error again here.
```suggestion
		return mgclients.ClientsPage{}, err
```

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — COMMENTED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]
