### PR TITLE
MF-1864 - CLI: Could not able to read messages from reader 

### LINKED ISSUE #1864: CLI Could not able to read messages from reader
**BUG REPORT**

1. What were you trying to achieve?

Trying to Read messages from reader with CLI 

2. What are the expected results?

Response with Messages 

```
{
  "limit": 10,
  "messages": [
    {
      "channel": "4761708f-3ad4-4728-9a83-882425131512",
      "name": "urn:dev:demo:10001BCD:energy",
      "protocol": "mqtt",
      "publisher": "7fe66411-69f1-443d-95e4-a8a36a5ca75e",
      "subtopic": "test.runid_1_4694",
      "time": 1689925033.454468,
      "unit": "kwh",
      "value": 1689935023
    },
... ,
... ,
... ,
... ,
    {
      "channel": "4761708f-3ad4-4728-9a83-882425131512",
      "name": "urn:dev:demo:10001BCD:humidity",
      "protocol": "http",
      "publisher": "e108a3b8-db74-442a-ae45-02c330680c52",
      "subtopic": "test.runid_1_4694",
      "time": 1689925023.454468,
      "unit": "V",
      "value": 68.8
    }
  ],
  "offset": 0,
  "total": 14
}
````

3. What are the received results?

Response with No Messages , `Total 0`

```json
{
  "limit": 10,
  "messages": [ ],
  "offset": 0,
  "total": 0 
}
```
4. What are the steps to reproduce the issue?

Send Message via cli 

```bash
cli messages send $channel_id.subtopic1.subtopic2 $message_jsom $token -R http://localhost:9009
```

Wait for few minutes and run the below command 

```bash
cli messages read $channel_id.subtopic1.subtopic2 $token -R http://localhost:9007
```

5. In what environment did you encounter the issue?

6. Additional information you deem important:

### PR DESCRIPTION
**Pull request by arvindh123**
Pull request title should be `MF-XXX - description` or `NOISSUE - description` where XXX is ID of issue that this PR relate to.
Please review the [CONTRIBUTING.md](https://github.com/mainflux/mainflux/blob/master/CONTRIBUTING.md) file for detailed contributing guidelines.

### What does this do?
- Fixes CLI could not able to  read messages from reader 
- Fixes CLI send messages topic path

### Which issue(s) does this PR fix/relate to?
Resolves #1864 

### List any changes that modify/break current functionality
NA

### Have you included tests for your changes?
Yes 

### Did you document any new/modified functionality?
NA

### CODE REVIEW

File: pkg/sdk/go/message.go [hunk 1]
```diff
@@ -22,7 +22,7 @@ func (sdk mfSDK) SendMessage(chanName, msg, key string) errors.SDKError {
 		subtopicPart = fmt.Sprintf("/%s", strings.Replace(chanNameParts[1], ".", "/", -1))
 	}
 
-	url := fmt.Sprintf("%s/channels/%s/messages/%s", sdk.httpAdapterURL, chanID, subtopicPart)
+	url := fmt.Sprintf("%s/channels/%s/messages%s", sdk.httpAdapterURL, chanID, subtopicPart)
```
Comment (arvindh123) [inline pkg/sdk/go/message.go:25]: In `Line#22`  leading `/` is added to subtopic ,So removed here

### Why removing here and not in `Line#22` ? 
If there is no subtopic , then ending `/` is no needed here, So better to have leading `/` in subtopics and  not in main topic

**Review by ianmuchyri — APPROVED** [review]

File: pkg/sdk/go/message.go [hunk 2]
```diff
@@ -34,7 +34,7 @@ func (sdk mfSDK) ReadMessages(chanName, token string) (MessagesPage, errors.SDKE
 	chanID := chanNameParts[0]
 	subtopicPart := ""
 	if len(chanNameParts) == channelParts {
-		subtopicPart = fmt.Sprintf("?subtopic=%s", strings.Replace(chanNameParts[1], ".", "/", -1))
+		subtopicPart = fmt.Sprintf("?subtopic=%s", chanNameParts[1])
```
Comment (drasko) [inline pkg/sdk/go/message.go:37]: Why do we remove this replacement, which I think comes from differences in NATS and in MQTT how they split the topics?

**Review by drasko — CHANGES_REQUESTED** [review]

File: pkg/sdk/go/message.go (hunk 2 above)
Comment (arvindh123) [reply pkg/sdk/go/message.go:37]: @drasko,

`/` seperater in published topics of MQTT are replaced with `.` and published into NATS

According to Mainflux CLI help,
To read messages `usage: read <channel_id.subtopic> <user_token>`

`mainflux-cli message read` command calls SDK.ReadMessages function to get data from Readers.

I have published a message via mqtt with Topics `channels/bb01ec9e-9c2c-429c-b0c6-de329da5c20e/messages/test/subtopic1/subtopic2`, 
In readers SubTopic are stored with like `test.subtopic1.subtopic2`

And CLI send message also have same `.` spereator to publish messages 
mainflux-cli message send `usage: send <channel_id.subtopic> <JSON_string> <thing_key>`
I have published a message via `mainflux-cli message send` command with this topic `bb01ec9e-9c2c-429c-b0c6-de329da5c20e.test.subtopic1.subtopic2`, 
Messages are sucessfully published and written to database

So, I decied, here replacement of `.` with `/` is not required.

Comment (drasko) [reply pkg/sdk/go/message.go:37]: Did you test by being subscribed also at MQTT topic at the same time? Do you receive messages in the RT on MQTT subscriber, and not only on Writer (which is NATS subscriber)?

Comment (arvindh123) [reply pkg/sdk/go/message.go:37]: Yes @drasko ,Tested,  
Subscribed to MQTT topics and after subscribe receives successfully,  then reads from reader

**Review by SammyOina — APPROVED** [review]

File: pkg/sdk/go/message.go (hunk 2 above)
Comment (drasko) [reply pkg/sdk/go/message.go:37]: @arvindh123 this does not look good to me, because `url` below will have mix of `/` (in the main topic) and `.` in (subtopic)

**Review by drasko — CHANGES_REQUESTED** [review]

File: pkg/sdk/go/message.go (hunk 2 above)
Comment (arvindh123) [reply pkg/sdk/go/message.go:37]: @drasko , At present in CLI we can't able to read messages , 

A MQTT message is published 
`mosquitto_pub -u b639aacc-023d-4837-b3bd-f2016b2d93c5 -P 6a6f92e8-0997-4069-ba99-01b0d7d1427d -t "channels/ace3e631-8d9a-4825-bf0b-1a270297e76e/messages/test/subtopic1/subtopic2" -m <messageconent> `

These message pickup by writer and stored them in DB as shown below 

|id |channel                      |subtopic|publisher                                    |protocol|name                             |unit|value|string_value|bool_value|data_value|sum|time             |update_time|
|---|-----------------------------|--------|---------------------------------------------|--------|---------------------------------|----|-----|------------|----------|----------|---|-----------------|-----------|
|9391e57c-c0c7-492d-b64d-31d7e76e96e8|ace3e631-8d9a-4825-bf0b-1a270297e76e|test.subtopic1.subtopic2|6a6f92e8-0997-4069-ba99-01b0d7d1427d         |http    |urn:dev:demo:10001BCD:temperature|C   |28.4 |            |          |          |   |1690527291.310878|0.0        |
|539ac63b-bd1c-4c2e-ba12-bad7cdf91b14|ace3e631-8d9a-4825-bf0b-1a270297e76e|test.subtopic1.subtopic2|6a6f92e8-0997-4069-ba99-01b0d7d1427d         |http    |urn:dev:demo:10001BCD:humidity   |V   |68.4 |            |          |          |   |1690527291.310878|0.0        |

if you see in the above table 
Subtopics are store in readerlike this  `test.subtopic1.subtopic2`, which is different from topic sent from mqtt, in mqtt topics are sent with separate `/`  

To read these message from reader , We need  http api with subtopic filter like this  `http://localhost/reader?subtopic=test.subtopic1.subtopic2`

And In CLI , we need to send command like this `mainflux-cli messages read  `ace3e631-8d9a-4825-bf0b-1a270297e76e.test.subtopic1.subtopic2 `
 
 Since in present code `.` got replace by `/` in readers SDK
The request sent to reader is like this  `http://localhost/reader?subtopic=test/subtopic1/subtopic2`
Because of this request we are not getting any response.

**Review by drasko — APPROVED** [review]
LGTM
