### PR TITLE
MG-2363 - Fix users with member relation are able to list things

### LINKED ISSUE #2363: Bug: Users with member relation are able to list things that they have not created
### What were you trying to achieve?

Listing things as a member. If the member has not created the thing by the member or shared by the member I should not be able to see them.

### What are the expected results?

Expected an empty things page.

### What are the received results?

Got a list of things.

### Steps To Reproduce

1. Create a user.
2. Assign user to domain as a member.
3. Then list thing.

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #2363 

## What does this do?
It change how `listClients` method work. It checks IDs that are authorized for view for a user.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2363 
- Resolves #2363 

## Have you included tests for your changes?
Yes

## Did you document any new/modified feature?
N/A

### CODE REVIEW

File: things/service.go [hunk 1]
```diff
@@ -180,6 +180,9 @@ func (svc service) ListClients(ctx context.Context, token, reqUserID string, pm
 	}
 
 	pm.IDs = ids
+	if len(pm.IDs) == 0 && pm.Domain == "" {
```
Comment (dborovcanin) [inline things/service.go]: Move assignment `pm.IDs = ids` below this condition.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
