### PR TITLE
MF-1096 - Fix AuthN and Things Auth ENVARS

### LINKED ISSUE #921: Fix MF_THINGS_AUTH_GRPC_PORT ENV var in protocol adapters' READMEs
**BUG REPORT**

1. What were you trying to achieve?

2. What are the expected results?

README files of protocol adapter services should contain info about [MF_THINGS_AUTH_GRPC_PORT](https://github.com/mainflux/mainflux/blob/da4fc624400d5a5172b2bf91a06369e7ed3d5176/.env#L58) and not the `MF_THINGS_URL` which was replaced (additionaly, port was changed from `8181` to `8183`).

[This](https://github.com/mainflux/mainflux/blob/da4fc624400d5a5172b2bf91a06369e7ed3d5176/docker/docker-compose.yml#L209) also should be fixed as well as [default URL](https://github.com/mainflux/mainflux/blob/da4fc624400d5a5172b2bf91a06369e7ed3d5176/cmd/http/main.go#L40) to Things service for auth.

3. What are the received results?

4. What are the steps to reproduce the issue?

5. In what environment did you encounter the issue?

6. Additional information you deem important:

### LINKED ISSUE #1041: MF_AUTH_URL vs MF_AUTHN_URL
1. I was trying to run mainflux/cli provision test against newly pulled images for 0.10.0 and an older docker-compose.yaml file

2. I was expecting the user and 2 things to be created

3. Instead I kept receiving unauthorized access (`provision test` does not tell which step fails)

4. I had MF_AUTHN_URL in my things section of the docker-compose.yaml file instead of MF_AUTH_URL *without* N

5. My environment: docker for windows 19.03.5

To locate this issue, I started with ngninx logs, then things logs and finally authn which would not show a trace upon things creation. That lead me to check the URL until I noticed the missing N. This variable is missing from the things microservice README.md page.

### LINKED ISSUE #1089: Duplicate variable in entrypoint of nginx?
In the script `entrypoint.sh` of nginx (Here: https://github.com/mainflux/mainflux/blob/70955d1937759a634df1b2f00f301bd7637b0563/docker/nginx/entrypoint.sh#L15), is it normal that variable `${MF_THINGS_HTTP_PORT}` is indicated twice?

### LINKED ISSUE #1096: Fix AuthN and Things Auth ENVARS

### PR DESCRIPTION
**Pull request by manuio**
Signed-off-by: Manuel Imperiale <manuel.imperiale@gmail.com>

* Replace MF_AUTHN_URL, MF_AUTH_URL and MF_USERS_URL by MF_AUTHN_GRPC_URL.
* Replace MF_THINGS_URL by MF_THINGS_AUTH_GRPC_URL.
* Fix MF_THINGS_AUTH_GRPC_URL default values.
* Fix README and docker-compose.yml

Resolves #921 
Resolves #1041 
Resolves #1089 
Resolves #1096

### CODE REVIEW

File: cmd/users/main.go [hunk 1]
```diff
@@ -70,6 +63,11 @@ const (
 
 	defTokenResetEndpoint = "/reset-request" // URL where user lands after click on the reset link from email
 
+	defAuthnTLS     = "false"
+	defAuthnCACerts = ""
```
Comment (golangcibot) [inline cmd/users/main.go:67]: `defAuthnCACerts` is unused (from `varcheck`)

File: cmd/users/main.go [hunk 2]
```diff
@@ -103,23 +94,26 @@ const (
 	envEmailTemplate    = "MF_EMAIL_TEMPLATE"
 
 	envTokenResetEndpoint = "MF_TOKEN_RESET_ENDPOINT"
+
+	envAuthnTLS     = "MF_AUTHN_CLIENT_TLS"
+	envAuthnCACerts = "MF_AUTHN_CA_CERTS"
```
Comment (golangcibot) [inline cmd/users/main.go:99]: `envAuthnCACerts` is unused (from `varcheck`)

File: cmd/postgres-reader/main.go [hunk 3]
```diff
@@ -34,50 +34,51 @@ const (
...
+	defDBName            = "messages"
+	defDBSSLMode         = "disable"
+	defDBSSLCert         = ""
+	defDBSSLKey          = ""
+	defDBSSLRootCert     = ""
+	defJaegerURL         = ""
+	defThingsAuthURL     = mainflux.DefThingsAuthURL
+	defThingsAuthTimeout = "1" // in seconds
+
+	envThingsURL         = "MF_THINGS_AUTH_GRPC_URL"
```
Comment (golangcibot) [inline cmd/postgres-reader/main.go]: `envThingsURL` is unused (from `varcheck`)

File: cmd/postgres-reader/main.go [hunk 4]
```diff
@@ -34,50 +34,51 @@ const (
...
+	envLogLevel          = "MF_POSTGRES_READER_LOG_LEVEL"
+	envPort              = "MF_POSTGRES_READER_PORT"
+	envClientTLS         = "MF_POSTGRES_READER_CLIENT_TLS"
```
Comment (golangcibot) [inline cmd/postgres-reader/main.go:56]: `envClientTLS` is unused (from `varcheck`)

File: cmd/postgres-reader/main.go [hunk 5]
```diff
@@ -34,50 +34,51 @@ const (
...
-	envDBSSLMode     = "MF_POSTGRES_READER_DB_SSL_MODE"
-	envDBSSLCert     = "MF_POSTGRES_READER_DB_SSL_CERT"
-	envDBSSLKey      = "MF_POSTGRES_READER_DB_SSL_KEY"
-	envDBSSLRootCert = "MF_POSTGRES_READER_DB_SSL_ROOT_CERT"
-	envJaegerURL     = "MF_JAEGER_URL"
-	envThingsTimeout = "MF_POSTGRES_READER_THINGS_TIMEOUT"
+	defLogLevel          = "debug"
+	defPort              = "9204"
+	defClientTLS         = "false"
+	defCACerts           = ""
```
Comment (golangcibot) [inline cmd/postgres-reader/main.go:40]: `defCACerts` is unused (from `varcheck`)

File: cmd/postgres-reader/main.go [hunk 6]
```diff
@@ -34,50 +34,51 @@ const (
...
+	defDBSSLRootCert     = ""
+	defJaegerURL         = ""
+	defThingsAuthURL     = mainflux.DefThingsAuthURL
+	defThingsAuthTimeout = "1" // in seconds
+
+	envThingsURL         = "MF_THINGS_AUTH_GRPC_URL"
+	envLogLevel          = "MF_POSTGRES_READER_LOG_LEVEL"
+	envPort              = "MF_POSTGRES_READER_PORT"
+	envClientTLS         = "MF_POSTGRES_READER_CLIENT_TLS"
+	envCACerts           = "MF_POSTGRES_READER_CA_CERTS"
```
Comment (golangcibot) [inline cmd/postgres-reader/main.go:57]: `envCACerts` is unused (from `varcheck`)

File: cmd/postgres-reader/main.go [hunk 7]
```diff
@@ -34,50 +34,51 @@ const (
...
-	envDBName        = "MF_POSTGRES_READER_DB_NAME"
-	envDBSSLMode     = "MF_POSTGRES_READER_DB_SSL_MODE"
-	envDBSSLCert     = "MF_POSTGRES_READER_DB_SSL_CERT"
-	envDBSSLKey      = "MF_POSTGRES_READER_DB_SSL_KEY"
-	envDBSSLRootCert = "MF_POSTGRES_READER_DB_SSL_ROOT_CERT"
-	envJaegerURL     = "MF_JAEGER_URL"
-	envThingsTimeout = "MF_POSTGRES_READER_THINGS_TIMEOUT"
+	defLogLevel          = "debug"
+	defPort              = "9204"
+	defClientTLS         = "false"
```
Comment (golangcibot) [inline cmd/postgres-reader/main.go:39]: `defClientTLS` is unused (from `varcheck`)

**Review by drasko — DISMISSED** [review]
LGTM

**Comment by drasko** [comment]
@manuio is this still WIP? Can it be reviewed and merged?

**Comment by manuio** [comment]
@drasko We want to merge this one after the next release to avoid issues with the config

**Review by drasko — DISMISSED** [review]
If this one does not break us, nothing will ;)

**Review by drasko — DISMISSED** [review]
LGTM

File: .env [hunk 8]
```diff
@@ -96,7 +100,7 @@ MF_BOOTSTRAP_PORT=8202
 MF_BOOTSTRAP_DB_PORT=5432
 MF_BOOTSTRAP_DB_USER=mainflux
 MF_BOOTSTRAP_DB_PASS=mainflux
-MF_BOOTSTRAP_DB=bootstrap
+MF_BOOTSTRAP_DB_NAME=bootstrap
```
Comment (dborovcanin) [inline .env]: Following this, we should use `_DB_NAME` for `THINGS_BD`, `AUTHN_DB`, `USERS_DB`... So, either revert everything back to the `..._DB`, or change everything to `..._DB_NAME`. The first option is simpler and introduces fewer changes. I find both options equally unambiguous, so I'm leaning towards the first one.

File: env.go [hunk 9]
```diff
@@ -10,8 +10,86 @@ import (
 )
 
 const (
-	// DefNatsURL default NATS message broker URL
+	// DefNatsURL NATS broker URL
```
Comment (dborovcanin) [inline env.go]: I don't like the idea of having service-specific env vars in the root.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by mteodor — DISMISSED** [review]

**Review by drasko — APPROVED** [review]
LGTM

**Review by drasko — CHANGES_REQUESTED** [review]
Whoops.. I just saw that consts are used in env.go. I will not approve this :)

File: authn/README.md [hunk 10]
```diff
@@ -38,7 +38,7 @@ default values.
 | MF_AUTHN_DB_SSL_CERT      | Path to the PEM encoded certificate file                                |                |
 | MF_AUTHN_DB_SSL_KEY       | Path to the PEM encoded key file                                        |                |
 | MF_AUTHN_DB_SSL_ROOT_CERT | Path to the PEM encoded root certificate file                           |                |
-| MF_AUTHN_HTTP_PORT        | Authn service HTTP port                                                 | 8180           |
+| MF_AUTHN_HTTP_PORT        | Authn service HTTP port                                                 | 8189           |
```
Comment (nmarcetic) [inline authn/README.md]: Didn't we have all HTTP ports 8180 and all gRPC ports 8181?

File: http/README.md [hunk 11]
```diff
@@ -8,16 +8,16 @@ The service is configured using the environment variables presented in the
...
-| MF_NATS_URL                    | NATS instance URL                              | nats://localhost:4222 |
-| MF_THINGS_URL                  | Things service URL                             | localhost:8181        |
-| MF_HTTP_ADAPTER_CLIENT_TLS     | Flag that indicates if TLS should be turned on | false                 |
-| MF_HTTP_ADAPTER_CA_CERTS       | Path to trusted CAs in PEM format              |                       |
-| MF_JAEGER_URL                  | Jaeger server URL                              | localhost:6831        |
-| MF_HTTP_ADAPTER_THINGS_TIMEOUT | Things gRPC request timeout in seconds         | 1                     |
+| Variable                       | Description                                         | Default               |
+|--------------------------------|-----------------------------------------------------|-----------------------|
+| MF_HTTP_ADAPTER_LOG_LEVEL      | Log level for the HTTP Adapter                      | error                 |
+| MF_HTTP_ADAPTER_PORT           | Service HTTP port                                   | 8185                  |
```
Comment (drasko) [inline http/README.md]: This is probably wrong

File: http/README.md [hunk 12]
```diff
@@ -31,15 +31,15 @@ services:
     image: mainflux/http:[version]
     container_name: [instance name]
     ports:
-      - [host machine port]:8180
+      - [host machine port]:8185
```
Comment (drasko) [inline http/README.md]: So is this

File: ws/README.md [hunk 13]
```diff
@@ -8,16 +8,16 @@ The service is configured using the environment variables presented in the
...
-| MF_NATS_URL                  | NATS instance URL                              | nats://localhost:4222 |
-| MF_THINGS_URL                | Things service URL                             | localhost:8181        |
-| MF_JAEGER_URL                | Jaeger server URL                              | localhost:6831        |
-| MF_WS_ADAPTER_THINGS_TIMEOUT | Things gRPC request timeout in seconds         | 1                     |
+| Variable                     | Description                                         | Default               |
+|------------------------------|-----------------------------------------------------|-----------------------|
+| MF_WS_ADAPTER_CLIENT_TLS     | Flag that indicates if TLS should be turned on      | false                 |
+| MF_WS_ADAPTER_CA_CERTS       | Path to trusted CAs in PEM format                   |                       |
+| MF_WS_ADAPTER_LOG_LEVEL      | Log level for the WS Adapter                        | error                 |
+| MF_WS_ADAPTER_PORT           | Service WS port                                     | 8186                  |
```
Comment (drasko) [inline ws/README.md]: Probably wrong

**Review by drasko — CHANGES_REQUESTED** [review]

File: things/README.md [hunk 14]
```diff
@@ -36,16 +36,16 @@ default values.
 | MF_THINGS_ES_URL            | Event store URL                                                        | localhost:6379 |
 | MF_THINGS_ES_PASS           | Event store password                                                   |                |
 | MF_THINGS_ES_DB             | Event store instance name                                              | 0              |
-| MF_THINGS_HTTP_PORT         | Things service HTTP port                                               | 8180           |
-| MF_THINGS_AUTH_HTTP_PORT    | Things service auth HTTP port                                          | 8989           |
-| MF_THINGS_AUTH_GRPC_PORT    | Things service auth gRPC port                                          | 8181           |
+| MF_THINGS_HTTP_PORT         | Things service HTTP port                                               | 8182           |
```
Comment (drasko) [inline things/README.md:39]: This is probably an error

File: things/README.md [hunk 15]
```diff
@@ -36,16 +36,16 @@ default values.
...
+| MF_THINGS_AUTH_HTTP_PORT    | Things service Auth HTTP port                                          | 8989           |
+| MF_THINGS_AUTH_GRPC_PORT    | Things service Auth gRPC port                                          | 8183           |
```
Comment (drasko) [inline things/README.md]: This also

File: writers/mongodb/README.md [hunk 16]
```diff
@@ -12,8 +12,8 @@ default values.
 |----------------------------------|---------------------------------------------|------------------------|
 | MF_NATS_URL                      | NATS instance URL                           | nats://localhost:4222  |
 | MF_MONGO_WRITER_LOG_LEVEL        | Log level for MongoDB writer                | error                  |
-| MF_MONGO_WRITER_PORT             | Service HTTP port                           | 8180                   |
-| MF_MONGO_WRITER_DB_NAME          | Default MongoDB database name               | mainflux               |
+| MF_MONGO_WRITER_PORT             | Service HTTP port                           | 8901                   |
```
Comment (drasko) [inline writers/mongodb/README.md]: Probably an error.

**Review by drasko — CHANGES_REQUESTED** [review]

File: things/README.md [hunk 17]
```diff
@@ -37,15 +37,15 @@ default values.
 | MF_THINGS_ES_PASS           | Event store password                                                   |                |
 | MF_THINGS_ES_DB             | Event store instance name                                              | 0              |
 | MF_THINGS_HTTP_PORT         | Things service HTTP port                                               | 8180           |
-| MF_THINGS_AUTH_HTTP_PORT    | Things service auth HTTP port                                          | 8989           |
-| MF_THINGS_AUTH_GRPC_PORT    | Things service auth gRPC port                                          | 8181           |
+| MF_THINGS_AUTH_HTTP_PORT    | Things service Auth HTTP port                                          | 8989           |
```
Comment (drasko) [inline things/README.md]: This is probably wrong.

**Review by drasko — CHANGES_REQUESTED** [review]

File: cmd/cassandra-reader/main.go [hunk 18]
```diff
@@ -34,48 +34,48 @@ import (
...
+	defServerKey         = ""
+	defJaegerURL         = ""
+	defThingsAuthURL     = "localhost:8181"
+	defThingsAuthTimeout = "1" // in seconds
+
+	envLogLevel          = "MF_CASSANDRA_READER_LOG_LEVEL"
+	envPort              = "MF_CASSANDRA_READER_PORT"
+	envCluster           = "MF_CASSANDRA_READER_DB_CLUSTER"
+	envKeyspace          = "MF_CASSANDRA_READER_DB_KEYSPACE"
+	envDBUser            = "MF_CASSANDRA_READER_DB_USERNAME"
```
Comment (dborovcanin) [inline cmd/cassandra-reader/main.go]: Please change to `MF_CASANDRA_READER_DB_USER` and `MF_CASANDRA_READER_DB_PASS`. Also, please don't forget to change README, `.env`, and compose.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: cmd/cassandra-reader/main.go (hunk 18 above)
Comment (manuio) [reply cmd/cassandra-reader/main.go]: Should I rename also `MF_CASSANDRA_WRITER_DB_KEYSPACE` -> `MF_CASSANDRA_WRITER_DB_NAME`?

Comment (dborovcanin) [reply cmd/cassandra-reader/main.go]: I would say no. I'm afraid it would be misleading and would only confuse the end-user.

**Review by blokovi — DISMISSED** [review]

File: cmd/cassandra-reader/main.go [hunk 19]
```diff
@@ -121,8 +121,8 @@ func loadConfig() config {
 	dbCfg := cassandra.DBConfig{
 		Hosts:    strings.Split(mainflux.Env(envCluster, defCluster), sep),
 		Keyspace: mainflux.Env(envKeyspace, defKeyspace),
-		Username: mainflux.Env(envDBUsername, defDBUsername),
-		Password: mainflux.Env(envDBPassword, defDBPassword),
+		Username: mainflux.Env(envDBUser, defDBUser),
+		Password: mainflux.Env(envDBPass, defDBPass),
```
Comment (dborovcanin) [inline cmd/cassandra-reader/main.go]: Maybe we should use `user` and `pass` here.

File: cmd/mongodb-reader/main.go [hunk 20]
```diff
@@ -33,46 +33,46 @@ import (
...
+	defCACerts           = ""
+	defServerCert        = ""
+	defServerKey         = ""
+	defJaegerURL         = ""
+	defThingsAuthURL     = "localhost:8181"
+	defThingsAuthTimeout = "1" // in seconds
+
+	envLogLevel          = "MF_MONGO_READER_LOG_LEVEL"
+	envPort              = "MF_MONGO_READER_PORT"
+	envDBName            = "MF_MONGO_READER_DB_NAME"
```
Comment (dborovcanin) [inline cmd/mongodb-reader/main.go]: If we're going to use `DB` instead of `DB_NAME` for database names, this should be applied to all the services, including all the readers and writers. Both `DB` and `DB_NAME` are OK, as long as we're consistent.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: cmd/cassandra-reader/main.go (hunk 19 above)
Comment (manuio) [reply cmd/cassandra-reader/main.go]: We can't because it comes from here: "github.com/influxdata/influxdb/client/v2"

**Review by drasko — DISMISSED** [review]
LGTM

File: .env [hunk 21]
```diff
@@ -141,18 +145,18 @@ MF_INFLUX_WRITER_PORT=8900
...
 MF_INFLUX_WRITER_GRAFANA_PORT=3001
 
 ### InfluxDB Reader
 MF_INFLUX_READER_LOG_LEVEL=debug
 MF_INFLUX_READER_PORT=8905
-MF_INFLUX_READER_DB_NAME=mainflux
 MF_INFLUX_READER_DB_PORT=8086
 MF_INFLUX_READER_DB_USER=mainflux
 MF_INFLUX_READER_DB_PASS=mainflux
+MF_INFLUX_READER_DB_NAME=mainflux
```
Comment (dborovcanin) [inline .env]: Same here.

File: .env [hunk 22]
```diff
@@ -141,18 +145,18 @@ MF_INFLUX_WRITER_PORT=8900
 MF_INFLUX_WRITER_BATCH_SIZE=5000
 MF_INFLUX_WRITER_BATCH_TIMEOUT=5
 MF_INFLUX_WRITER_DB_PORT=8086
-MF_INFLUX_WRITER_DB_NAME=mainflux
 MF_INFLUX_WRITER_DB_USER=mainflux
 MF_INFLUX_WRITER_DB_PASS=mainflux
+MF_INFLUX_WRITER_DB_NAME=mainflux
```
Comment (dborovcanin) [inline .env]: Should this be `DB`?

File: cmd/cassandra-reader/main.go (hunk 19 above)
Comment (dborovcanin) [reply cmd/cassandra-reader/main.go]: This is Cassandra config from `readers/cassandra/init.go`.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by drasko — DISMISSED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM
