### PR TITLE
MF-982 - Add error when connecting empty channels or things

### LINKED ISSUE #982: Connect endpoint doesn't return errror if request lists are empty
**BUG REPORT**

1. What were you trying to achieve?
Receive an error if /connect request lists of Things and Channels are empty 
2. What are the expected results?
Get an error
3. What are the received results?
Status Ok 
4. What are the steps to reproduce the issue?
Connect Things and Channels with empty lists

### PR DESCRIPTION
**Pull request by nwneisen**
Signed-off-by: nwneisen <nwneisen@gmail.com>

### What does this do?
Returns an error when trying to connect with empty channel or list IDs

### Which issue(s) does this PR fix/relate to?
Resolves #982 

### List any changes that modify/break current functionality
Providing empty lists will now return an error

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
NA

### CODE REVIEW

**Review by manuio — APPROVED** [review]
LGTM

File: things/api/things/http/endpoint_test.go [hunk 1]
```diff
@@ -1971,6 +1971,30 @@ func TestCreateConnections(t *testing.T) {
 			status:      http.StatusBadRequest,
 			body:        "{",
 		},
+		{
+			desc:        "Empty channelIDs",
```
Comment (manuio) [inline things/api/things/http/endpoint_test.go]: Can you please add a more detailed description

**Review by manuio — CHANGES_REQUESTED** [review]

File: things/api/things/http/endpoint_test.go [hunk 2]
```diff
@@ -1972,23 +1972,23 @@ func TestCreateConnections(t *testing.T) {
 			body:        "{",
 		},
 		{
-			desc:        "Empty channelIDs",
+			desc:        "Connect valid things with empty channelIDs",
```
Comment (manuio) [inline things/api/things/http/endpoint_test.go]: Sorry for the detail but please use lowercase for the first letter. Maybe also `channel IDs`. 
There are also 2 descriptions in this test that can be more detailed. It would be nice if you could do it in this PR.

**Review by manuio — CHANGES_REQUESTED** [review]

File: things/api/things/http/endpoint_test.go (hunk 2 above)
Comment (nwneisen) [reply things/api/things/http/endpoint_test.go]: I forgot Go prefers not to capitalize messages. Old habit. I'll change the ids so it doesn't read as matching the variable names.

I added connect to the other descriptions.

File: things/api/things/http/endpoint_test.go [hunk 3]
```diff
@@ -1957,20 +1957,44 @@ func TestCreateConnections(t *testing.T) {
...
 		{
-			desc:        "invalid JSON",
+			desc:        "connect with invalid JSON",
 			auth:        token,
 			contentType: contentType,
 			status:      http.StatusBadRequest,
 			body:        "{",
 		},
+		{
+			desc:        "connect valid things with empty channelIDs",
```
Comment (manuio) [inline things/api/things/http/endpoint_test.go]: Fix `channelIDs`

**Review by manuio — CHANGES_REQUESTED** [review]

**Review by manuio — APPROVED** [review]
LGTM

**Comment by manuio** [comment]
@nwneisen Thank you!

**Comment by nwneisen** [comment]
@manuio Glad to help!

**Review by drasko — APPROVED** [review]
LGTM
