### PR TITLE
SMQ-2742 - Add entity role check for optional members when adding role

### LINKED ISSUE #2742: Bug: When creating an entity role check optional members part of domain
### What were you trying to achieve?

Create a role for a group, channel or client

### What are the expected results?

We should not be able to create a role with optional members who are not part of the domain

### What are the received results?

When I create a role for a client , group or channel, I can be able to add users who are not part of the domain.
https://jam.dev/c/ece37b41-d48f-457f-a24f-a122b191c15a

### Steps To Reproduce

The steps are shown in the jam video below
https://jam.dev/c/ece37b41-d48f-457f-a24f-a122b191c15a

### In what environment did you encounter the issue?

Latest supermq

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #2742 

## What does this do?
It adds check for optional members when adding role

## Which issue(s) does this PR fix/relate to?

- Related Issue #2742 
- Resolves #2742 

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
No

### CODE REVIEW

File: pkg/roles/rolemanager/middleware/authorization.go [hunk 1]
```diff
@@ -64,6 +64,9 @@ func (ram RoleManagerAuthorizationMiddleware) AddRole(ctx context.Context, sessi
 	}); err != nil {
 		return roles.RoleProvision{}, err
 	}
+	if err := ram.authorizeMembers(ctx, session, optionalMembers); err != nil {
```
Comment (arvindh123) [inline pkg/roles/rolemanager/middleware/authorization.go]: Can we rename this to `validateMembers`

In that function we can return something message like 
`<Member ID> is not member of domain` for other entities
and 
`<Member ID> is not found` for domains

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]
