### PR TITLE
SMQ-2670 - Fix Unauthorized User IDs can be added to domain entity role members

### LINKED ISSUE #2670: Bug: Random unauthorized User IDs Can Be Added to domain entity role Members
### What were you trying to achieve?

Trying to add random user id to group, client and channel roles 

### What are the expected results?

Fail to add members to role

### What are the received results?

Random user added to the role as member

### Steps To Reproduce

_No response_

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #2670 

## What does this do?
It add a authorization check for every member provided.

## Which issue(s) does this PR fix/relate to?

- Related Issue #2670
- Resolves #2670

## Have you included tests for your changes?
No

## Did you document any new/modified feature?
No

### CODE REVIEW

**Comment by dborovcanin** [comment]
@arvindh123 Please review.

**Review by arvindh123 — CHANGES_REQUESTED** [review]
Please add the same check to the entity creation middleware, as the entity creation functions **CreateDomain, CreateGroup, CreateChannels, and CreateClients**  will call the roles.AddNewEntitiesRoles function, which also adds members to the entity. Therefore, we need the same check in the entity creation middleware.

File: channels/middleware/authorization.go [hunk 1]
```diff
@@ -97,6 +97,10 @@ func (am *authorizationMiddleware) CreateChannels(ctx context.Context, session a
 		}
 	}
 
+	if err := am.RoleManagerAuthorizationMiddleware.AuthorizeMembers(ctx, session, []string{session.UserID}); err != nil {
+		return []channels.Channel{}, []roles.RoleProvision{}, errors.Wrap(svcerr.ErrAuthorization, err)
```
Comment (arvindh123) [inline channels/middleware/authorization.go]: @nyagamunene 
I think this is not needed, Because during the authorization the requested user will be check user have access to domain as member.

File: clients/middleware/authorization.go [hunk 2]
```diff
@@ -89,6 +89,10 @@ func (am *authorizationMiddleware) CreateClients(ctx context.Context, session au
 		}
 	}
 
+	if err := am.RoleManagerAuthorizationMiddleware.AuthorizeMembers(ctx, session, []string{session.UserID}); err != nil {
+		return []clients.Client{}, []roles.RoleProvision{}, errors.Wrap(svcerr.ErrAuthorization, err)
```
Comment (arvindh123) [inline clients/middleware/authorization.go]: @nyagamunene 
I think this is not needed, Because during the authorization the requested user will be check user have access to domain as member.

File: domains/middleware/authorization.go [hunk 3]
```diff
@@ -48,6 +50,9 @@ func AuthorizationMiddleware(entityType string, svc domains.Service, authz smqau
 }
 
 func (am *authorizationMiddleware) CreateDomain(ctx context.Context, session authn.Session, d domains.Domain) (domains.Domain, []roles.RoleProvision, error) {
+	if err := am.RoleManagerAuthorizationMiddleware.AuthorizeMembers(ctx, session, []string{session.UserID}); err != nil {
```
Comment (arvindh123) [inline domains/middleware/authorization.go]: @nyagamunene 
same here, we can remove this logic

File: groups/middleware/authorization.go [hunk 4]
```diff
@@ -95,6 +95,11 @@ func (am *authorizationMiddleware) CreateGroup(ctx context.Context, session auth
 			return groups.Group{}, []roles.RoleProvision{}, errors.Wrap(svcerr.ErrUnauthorizedPAT, err)
 		}
 	}
+
+	if err := am.RoleManagerAuthorizationMiddleware.AuthorizeMembers(ctx, session, []string{session.UserID}); err != nil {
```
Comment (arvindh123) [inline groups/middleware/authorization.go]: @nyagamunene we can remove this logic

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — DISMISSED** [review]

File: pkg/roles/rolemanager/middleware/authoirzation.go [hunk 5]
```diff
@@ -9,6 +9,7 @@ import (
 	"github.com/absmach/supermq/pkg/authn"
 	smqauthz "github.com/absmach/supermq/pkg/authz"
 	"github.com/absmach/supermq/pkg/errors"
+	svcerr "github.com/absmach/supermq/pkg/errors/service"
```
Comment (dborovcanin) [inline pkg/roles/rolemanager/middleware/authoirzation.go:12]: Please fix the typo in the file name.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
