### PR TITLE
MF-1699 - Enrich SDK and CLI

### LINKED ISSUE #1699: Inconsistency Between API Documentation and Service Implementation
**BUG REPORT**

1. What were you trying to achieve?
Write the python SDK using the [API documentation ](https://api.mainflux.io/) and I found there is some incosistency in the API documentation and service implementation

2. What are the expected results?
API documentation to be consistent with service implmentation

3. What are the received results?

1. In the **auth** service

> There is no [api documentation](https://api.mainflux.io/?urls.primaryName=auth.yml) yet they are implemented for :

- unassign

> There is [documentation for share access rights](https://api.mainflux.io/?urls.primaryName=auth.yml#/auth/post_groups__userGroupID__share) but it is not implemented in the code

2. In the **users** service

> There is no [api documentation](https://api.mainflux.io/?urls.primaryName=users.yml#/) yet they are implemented for :

- view_user i.e `/users/:id`

5. What are the steps to reproduce the issue?
Goto [api docs](https://api.mainflux.io/)
Got to [master branch](https://github.com/mainflux/mainflux)

6. In what environment did you encounter the issue?
master branch

7. Additional information you deem important:

In the SDK for go we lack some features e.g
- Share access right
- Create policies
- Delete policies
- Retrieve managed bootstrap configs
- Update managed bootstrap connections
- Retrieves a list of certificates' serial IDs for a given thing ID.
- Search and retrieve things
- Share thing with user
- Update thing key
- Check access by key
- Check access by id

In the CLI for go we lack some features e.g
- Gets API key details for the given key.
- Updates Name, Description or Metadata of a group.
- Get group children
- Get group parents
- Share access right
- Create policies
- Delete policies
- Retrieve managed configs
- Update managed bootstrap connections
- Retrieves a list of certificates' serial IDs for a given thing ID.
- Search and retrieve things
- Share thing with user
- Update thing key
- Check access by key
- Check access by id

### PR DESCRIPTION
**Pull request by rodneyosodo**
### What does this do?
Enriches SDK and CLI. Also it updated the api docs swagger files.

### Which issue(s) does this PR fix/relate to?
Resolves #1699 
Duplicate of #1711 

### List any changes that modify/break current functionality
N/A

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
No

### Notes
N/A

### CODE REVIEW

**Review by dborovcanin — COMMENTED** [review]
Please update the PR.

File: pkg/sdk/go/things.go [hunk 1]
```diff
@@ -169,9 +237,65 @@ func (sdk mfSDK) Connect(connIDs ConnectionIDs, token string) errors.SDKError {
 	return sdkerr
 }
 
+func (sdk mfSDK) DisConnect(connIDs ConnectionIDs, token string) errors.SDKError {
```
Comment (drasko) [inline pkg/sdk/go/things.go]: Why not Disconnect?

**Review by drasko — CHANGES_REQUESTED** [review]

File: pkg/sdk/go/things.go (hunk 1 above)
Comment (rodneyosodo) [reply pkg/sdk/go/things.go]: Fixed

File: certs/certs.go [hunk 2]
```diff
@@ -30,3 +39,46 @@ type Repository interface {
 	// RetrieveBySerial retrieves a certificate for a given serial ID
 	RetrieveBySerial(ctx context.Context, ownerID, serialID string) (Cert, error)
 }
+
+func LoadCertificates(caPath, caKeyPath string) (tls.Certificate, *x509.Certificate, error) {
+	var tlsCert tls.Certificate
```
Comment (SammyOina) [inline certs/certs.go]: unnecessary initialization of tlsCert and caCert considering they're assigned in LoadX509KeyPair and ReadCert. Suggest removal

File: cli/consumers.go [hunk 3]
```diff
@@ -0,0 +1,100 @@
...
+			if err != nil {
+				logError(err)
+				return
+			}
+
+			logJSON(c)
+		},
+	},
+	{
+		Use:   "remove <thing_id> <user_auth_token>",
```
Comment (SammyOina) [inline cli/consumers.go]: did you mean remove <sub_id>

File: cli/consumers.go [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+		Use:   "create <topic> <contact> <user_auth_token>",
+		Short: "Create subscription",
+		Long:  `Create new subscription`,
+		Run: func(cmd *cobra.Command, args []string) {
+			if len(args) != 3 {
+				logUsage(cmd.Use)
+				return
+			}
+
+			id, err := sdk.CreateSubscription(args[0], args[1], args[2])
```
Comment (SammyOina) [inline cli/consumers.go:22]: probably best to name these args[i]  variables to more descriptive names for readability,

File: cli/policies.go
Comment (SammyOina) [inline cli/policies.go:1]: a lot of shared code between create and remove commands, consider refactoring

**Review by SammyOina — CHANGES_REQUESTED** [review]

File: certs/certs.go (hunk 2 above)
Comment (rodneyosodo) [reply certs/certs.go]: They are used before `LoadX509KeyPair`. When `caPath` and `caKeyPath` is `==` `""`

Comment (SammyOina) [reply certs/certs.go]: you can return an empty struct and nill, for that case

File: cli/consumers.go (hunk 3 above)
Comment (rodneyosodo) [reply cli/consumers.go]: Yes

File: cli/consumers.go (hunk 4 above)
Comment (rodneyosodo) [reply cli/consumers.go:22]: It is done that for all service. It seems intuitive to me

File: cli/policies.go
Comment (rodneyosodo) [reply cli/policies.go:1]: That would make it spaghetti code

File: certs/certs.go (hunk 2 above)
Comment (rodneyosodo) [reply certs/certs.go]: at `b, err := ioutil.ReadFile(caPath)` on error handling should we return an empty `tlsCert` yet is was created or not?

Comment (dborovcanin) [reply certs/certs.go]: I also prefer Sammy's approach. I find explicit `return tls.Certificate{}, nil, nil` in case of error just as fine and a bit more precise and efficient (when reading `return tlsCert, caCert, nil` you do not know what are actual values; but you also do not care). This is a matter of personal preference.

File: certs/certs.go [hunk 5]
```diff
@@ -30,3 +39,46 @@ type Repository interface {
...
+		return tlsCert, caCert, nil
+	}
+
+	if _, err := os.Stat(caPath); os.IsNotExist(err) {
+		return tlsCert, caCert, err
+	}
+
+	if _, err := os.Stat(caKeyPath); os.IsNotExist(err) {
+		return tlsCert, caCert, err
+	}
```
Comment (dborovcanin) [inline certs/certs.go]: Do we also care about other errors besides `NotExists`  (such as insufficient privilege)?

Comment (dborovcanin) [inline certs/certs.go]: Do we also care about other errors besides `NotExists`  (such as insufficient privilege)?

File: cli/consumers.go (hunk 4 above)
Comment (dborovcanin) [reply cli/consumers.go:22]: Not ideal, but it's acceptable.

File: certs/certs.go [hunk 6]
```diff
@@ -30,3 +39,46 @@ type Repository interface {
...
+
+	caCert, err = ReadCert(b)
+	if err != nil {
+		return tlsCert, caCert, errors.Wrap(err, err)
+	}
+
+	return tlsCert, caCert, nil
+}
+
+func ReadCert(b []byte) (*x509.Certificate, error) {
```
Comment (dborovcanin) [inline certs/certs.go:78]: Add tests.

File: certs/certs.go [hunk 7]
```diff
@@ -30,3 +39,46 @@ type Repository interface {
 	// RetrieveBySerial retrieves a certificate for a given serial ID
 	RetrieveBySerial(ctx context.Context, ownerID, serialID string) (Cert, error)
 }
+
+func LoadCertificates(caPath, caKeyPath string) (tls.Certificate, *x509.Certificate, error) {
```
Comment (dborovcanin) [inline certs/certs.go:45]: Write tests for this one.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: cli/bootstrap.go [hunk 8]
```diff
@@ -37,14 +37,31 @@ var cmdBootstrap = []cobra.Command{
...
+			}
+			if args[0] == "all" {
+				l, err := sdk.Bootstraps(pageMetadata, args[1])
+				if err != nil {
+					logError(err)
+					return
+				}
+				logJSON(l)
+				return
+			}
```
Comment (arvindh123) [inline cli/bootstrap.go:64]: `mainflux-cli bootstrap get all` this command will return with limit 10
How to view all things

File: pkg/sdk/go/bootstrap.go [hunk 9]
```diff
@@ -103,6 +126,7 @@ func (sdk mfSDK) UpdateBootstrap(cfg BootstrapConfig, token string) errors.SDKEr
 	_, _, sdkerr := sdk.processRequest(http.MethodPut, url, token, string(CTJSON), data, http.StatusOK)
 	return sdkerr
 }
+
```
Comment (arvindh123) [inline pkg/sdk/go/bootstrap.go:129]: In UpdateBootstrap config `BootstrapConfig.MFThing` is used, but in bootstrap api endpoint `configId` is required 
Does this will work ?

Bootstrap Add request have following struct 

```go
type addReq struct {
	token       string
	ThingID     string   `json:"thing_id"`
	ExternalID  string   `json:"external_id"`
	ExternalKey string   `json:"external_key"`
	Channels    []string `json:"channels"`
	Name        string   `json:"name"`
	Content     string   `json:"content"`
	ClientCert  string   `json:"client_cert"`
	ClientKey   string   `json:"client_key"`
	CACert      string   `json:"ca_cert"`
}
```

But in SDK bootstrap config we have 
```go
type BootstrapConfig struct {
	ThingID     string    `json:"thing_id,omitempty"`
	Channels    []string  `json:"channels,omitempty"`
	ExternalID  string    `json:"external_id,omitempty"`
	ExternalKey string    `json:"external_key,omitempty"`
	MFThing     string    `json:"mainflux_id,omitempty"`
	MFChannels  []Channel `json:"mainflux_channels,omitempty"`
	MFKey       string    `json:"mainflux_key,omitempty"`
	Name        string    `json:"name,omitempty"`
	ClientCert  string    `json:"client_cert,omitempty"`
	ClientKey   string    `json:"client_key,omitempty"`
	CACert      string    `json:"ca_cert,omitempty"`
	Content     string    `json:"content,omitempty"`
	State       int       `json:"state,omitempty"`
}
```
Do we need the below given fields 
```go
	MFThing     string    `json:"mainflux_id,omitempty"`
	MFChannels  []Channel `json:"mainflux_channels,omitempty"`
	MFKey       string    `json:"mainflux_key,omitempty"`
```

File: cli/bootstrap.go [hunk 10]
```diff
@@ -98,15 +146,25 @@ var cmdBootstrap = []cobra.Command{
 		},
 	},
 	{
```
Comment (arvindh123) [inline cli/bootstrap.go:148]: I tired to test the bootstrap 
But I got not found 

In CLI bootstrap url  is not configured http://localhost 
In nginx there is not route for bootstrap

File: cli/bootstrap.go (hunk 8 above)
Comment (rodneyosodo) [reply cli/bootstrap.go:64]: You increase using the `-l` or `-limit` flag

File: pkg/sdk/go/bootstrap.go (hunk 9 above)
Comment (rodneyosodo) [reply pkg/sdk/go/bootstrap.go:129]: Actually no. In `UpdateBootstrap` at API level we only use `MFThing`, `Name` and `Content` which are in the `BootstrapConfig` for SDK. For `AddBootstrap` in SDK the other values will be omitted.

The `BootstrapConfig` for SDK in general purpose to be used for all CRUD operations.

File: cli/bootstrap.go (hunk 10 above)
Comment (rodneyosodo) [reply cli/bootstrap.go:148]: The URL is provided by the `-bootstrap-url` or `-b` flag

Comment (SammyOina) [reply cli/bootstrap.go:148]: I think for the longer form of flags, they should have double dashes `--`

Comment (SammyOina) [reply cli/bootstrap.go:148]: I think for the longer form of flags, they should have double dashes `--`

Comment (dborovcanin) [reply cli/bootstrap.go:148]: Is this one resolved, @arvindh123 can you test and confirm?

File: cli/policies.go
Comment (SammyOina) [reply cli/policies.go:1]: perhaps with a modifier such as a flag, policy --create and --remove

File: cli/bootstrap.go (hunk 10 above)
Comment (arvindh123) [reply cli/bootstrap.go:148]: tested , It works perfect !!

File: pkg/sdk/go/bootstrap.go (hunk 9 above)
Comment (arvindh123) [reply pkg/sdk/go/bootstrap.go:129]: Okay now clear

**Review by arvindh123 — APPROVED** [review]
LGTM

**Review by arvindh123 — DISMISSED** [review]

File: certs/certs_test.go [hunk 11]
```diff
@@ -0,0 +1,91 @@
...
+	"fmt"
+	"testing"
+
+	"github.com/mainflux/mainflux/certs"
+	"github.com/mainflux/mainflux/pkg/errors"
+	"github.com/stretchr/testify/assert"
+)
+
+func TestLoadCertificates(t *testing.T) {
+
```
Comment (dborovcanin) [inline certs/certs_test.go]: Remove the empty line.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]

File: cli/policies.go
Comment (SammyOina) [reply cli/policies.go:1]: Or a root command policy and sub commands create and remove

**Review by drasko — APPROVED** [review]
LGTM
