### PR TITLE
NOISSUE - Unify shared code between users and things (clients and groups)

### LINKED ISSUE #1755: Go-Lint Warnings
**BUG REPORT**

1. What were you trying to achieve?

3. What are the expected results?
Package is imported more than once

5. What are the received results?
dual imports

7. What are the steps to reproduce the issue?

- Dual Import https://github.com/mainflux/mainflux/blob/f82d78a7c480c6fbfd96ee09ce19024b23d219fd/users/clients/service_test.go#L15-L16
- Dual import https://github.com/mainflux/mainflux/blob/f82d78a7c480c6fbfd96ee09ce19024b23d219fd/users/groups/service_test.go#L16-L17
- len can't be less than zero https://github.com/mainflux/mainflux/blob/f82d78a7c480c6fbfd96ee09ce19024b23d219fd/things/groups/api/requests.go#L39
- redundant type https://github.com/mainflux/mainflux/blob/f82d78a7c480c6fbfd96ee09ce19024b23d219fd/bootstrap/redis/producer/streams_test.go#L122

9. In what environment did you encounter the issue?
clients brach

11. Additional information you deem important:

### PR DESCRIPTION
**Pull request by SammyOina**
### What does this do?
Unify shared code between users and things services
### Which issue(s) does this PR fix/relate to?
Resolves #1755 

### List any changes that modify/break current functionality
Nil

### Have you included tests for your changes?
None

### Did you document any new/modified functionality?
None

### CODE REVIEW

**Comment by rodneyosodo** [comment]
image

Remove these commits as they are already merged in clients

File: internal/mainflux/clients/status.go [hunk 1]
```diff
@@ -1,6 +1,11 @@
 package clients
```
Comment (rodneyosodo) [inline internal/mainflux/clients/status.go]: You can move this to the root of `internal/mainflux` since in the current implementation clients and groups have the same status implementation

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Rebase

File: internal/mainflux/clients/errors.go [hunk 2]
```diff
@@ -0,0 +1,30 @@
...
+	ErrMissingResetToken = errors.New("missing reset token")
+
+	// ErrRecoveryToken indicates error in generating password recovery token.
+	ErrRecoveryToken = errors.New("failed to generate password recovery token")
+
+	// ErrGetToken indicates error in getting signed token.
+	ErrGetToken = errors.New("failed to fetch signed token")
+
+	// ErrPasswordFormat indicates weak password.
+	ErrPasswordFormat = errors.New("password does not meet the requirements")
```
Comment (rodneyosodo) [inline internal/mainflux/clients/errors.go]: We don't use this for things to validate its password hence it can remain under users

File: internal/mainflux/clients/errors.go [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+
+	// ErrDisableClient indicates error in disabling client.
+	ErrDisableClient = errors.New("failed to disable client")
+
+	// ErrStatusAlreadyAssigned indicated that the client or group has already been assigned the status.
+	ErrStatusAlreadyAssigned = errors.New("status already assigned")
+
+	// ErrMissingResetToken indicates malformed or missing reset token
+	// for reseting password.
+	ErrMissingResetToken = errors.New("missing reset token")
```
Comment (rodneyosodo) [inline internal/mainflux/clients/errors.go]: We don't use this for things hence it can remain under users

File: internal/mainflux/clients/errors.go [hunk 4]
```diff
@@ -0,0 +1,30 @@
...
+
+	// ErrRecoveryToken indicates error in generating password recovery token.
+	ErrRecoveryToken = errors.New("failed to generate password recovery token")
```
Comment (rodneyosodo) [inline internal/mainflux/clients/errors.go]: same

File: internal/mainflux/clients/errors.go [hunk 5]
```diff
@@ -0,0 +1,30 @@
...
+
+	// ErrGetToken indicates error in getting signed token.
+	ErrGetToken = errors.New("failed to fetch signed token")
```
Comment (rodneyosodo) [inline internal/mainflux/clients/errors.go]: same

File: internal/mainflux/groups/errors.go [hunk 6]
```diff
@@ -0,0 +1,17 @@
...
+	ErrInvalidStatus = errors.New("invalid groups status")
+
+	// ErrEnableGroup indicates error in enabling group.
+	ErrEnableGroup = errors.New("failed to enable group")
+
+	// ErrDisableGroup indicates error in disabling group.
+	ErrDisableGroup = errors.New("failed to disable group")
+
+	// ErrStatusAlreadyAssigned indicated that the group has already been assigned the status.
+	ErrStatusAlreadyAssigned = errors.New("status already assigned")
```
Comment (rodneyosodo) [inline internal/mainflux/groups/errors.go]: This is used for both client and groups. Can we unify it?

File: internal/mainflux/groups/groups.go [hunk 7]
```diff
@@ -0,0 +1,36 @@
...
+
+// Group represents the group of Clients.
+// Indicates a level in tree hierarchy. Root node is level 1.
+// Path in a tree consisting of group IDs
+// Paths are unique per owner.
+type Group struct {
+	ID          string           `json:"id"`
+	Owner       string           `json:"owner_id"`
+	Parent      string           `json:"parent_id,omitempty"`
+	Name        string           `json:"name"`
```
Comment (rodneyosodo) [inline internal/mainflux/groups/groups.go]:
```suggestion
	Name        string           `json:"name,omitempty"`
```

File: internal/mainflux/groups/groups.go [hunk 8]
```diff
@@ -0,0 +1,36 @@
...
+	Description string           `json:"description,omitempty"`
+	Metadata    Metadata         `json:"metadata,omitempty"`
+	Level       int              `json:"level"`
```
Comment (rodneyosodo) [inline internal/mainflux/groups/groups.go]:
```suggestion
	Level       int              `json:"level,omitempty"`
```

File: internal/mainflux/groups/groups.go [hunk 9]
```diff
@@ -0,0 +1,36 @@
...
+	Path        string           `json:"path"`
```
Comment (rodneyosodo) [inline internal/mainflux/groups/groups.go]:
```suggestion
	Path        string           `json:"path,omitempty"`
```

Comment (rodneyosodo) [reply internal/mainflux/groups/groups.go]: Use this a reference https://github.com/mainflux/mainflux/blob/4a76df6f27b2508cc2ea561c0ef592d6af6bbf57/users/groups/groups.go#L39

File: internal/mainflux/groups/groups.go (hunk 8 above)
Comment (rodneyosodo) [reply internal/mainflux/groups/groups.go]: Use this a reference https://github.com/mainflux/mainflux/blob/4a76df6f27b2508cc2ea561c0ef592d6af6bbf57/users/groups/groups.go#L39

File: internal/mainflux/groups/groups.go (hunk 7 above)
Comment (rodneyosodo) [reply internal/mainflux/groups/groups.go]: Use this a reference https://github.com/mainflux/mainflux/blob/4a76df6f27b2508cc2ea561c0ef592d6af6bbf57/users/groups/groups.go#L39

File: internal/mainflux/groups/groups.go [hunk 10]
```diff
@@ -0,0 +1,36 @@
...
+
+const (
+	// MaxLevel represents the maximum group hierarchy level.
+	MaxLevel = uint64(5)
+	// MinLevel represents the minimum group hierarchy level.
+	MinLevel = uint64(0)
+)
+
+// Metadata represents arbitrary JSON.
+type Metadata map[string]interface{}
```
Comment (rodneyosodo) [inline internal/mainflux/groups/groups.go]: This is also similar to clients Metadata, can we unify it?

File: internal/mainflux/status.go [hunk 11]
```diff
@@ -51,3 +56,16 @@ func ToStatus(status string) (Status, error) {
 	}
 	return Status(0), apiutil.ErrInvalidStatus
 }
+
+// Custom Marshaller for Client
```
Comment (rodneyosodo) [inline internal/mainflux/status.go]: Both client and group

File: internal/mainflux/status.go [hunk 12]
```diff
@@ -51,3 +56,16 @@ func ToStatus(status string) (Status, error) {
...
+func (s Status) MarshalJSON() ([]byte, error) {
+	return json.Marshal(s.String())
+}
+
+// Custom Unmarshaler for Client
```
Comment (rodneyosodo) [inline internal/mainflux/status.go]: same

File: provision/config.go [hunk 13]
```diff
@@ -5,11 +5,11 @@ package provision
 
 import (
 	"fmt"
-	"io/ioutil"
+	"os"
 
+	mfgroups "github.com/mainflux/mainflux/internal/mainflux/groups"
 	"github.com/mainflux/mainflux/pkg/errors"
 	"github.com/mainflux/mainflux/things/clients"
```
Comment (rodneyosodo) [inline provision/config.go]: Also change this

File: readers/api/transport.go [hunk 14]
```diff
@@ -15,7 +15,6 @@ import (
 	"github.com/mainflux/mainflux/pkg/errors"
 	"github.com/mainflux/mainflux/readers"
 	"github.com/mainflux/mainflux/things/policies"
-	tpolicies "github.com/mainflux/mainflux/things/policies"
```
Comment (rodneyosodo) [inline readers/api/transport.go:18]: Retain `tpolicies` and remove `policies`

File: internal/mainflux/groups/errors.go [hunk 15]
```diff
@@ -0,0 +1,17 @@
+package groups
```
Comment (rodneyosodo) [inline internal/mainflux/groups/errors.go]: You can unify `clients/errors.go` and `groups/errors.go`

File: things/groups/api/logging.go [hunk 16]
```diff
@@ -5,6 +5,7 @@ import (
 	"fmt"
 	"time"
 
+	mfgroups "github.com/mainflux/mainflux/internal/mainflux/groups"
 	mflog "github.com/mainflux/mainflux/logger"
 	"github.com/mainflux/mainflux/things/groups"
```
Comment (rodneyosodo) [inline things/groups/api/logging.go:10]: We can unify the `things/groups` service and `users/groups` service

File: things/groups/service.go [hunk 17]
```diff
@@ -6,9 +6,10 @@ import (
 
 	"github.com/mainflux/mainflux"
 	"github.com/mainflux/mainflux/internal/apiutil"
+	mfclients "github.com/mainflux/mainflux/internal/mainflux"
+	mfgroups "github.com/mainflux/mainflux/internal/mainflux/groups"
 	"github.com/mainflux/mainflux/pkg/errors"
 	"github.com/mainflux/mainflux/users/policies"
-	upolicies "github.com/mainflux/mainflux/users/policies"
```
Comment (rodneyosodo) [inline things/groups/service.go:11]: retain `upolicies` and remove `policies`

File: cmd/things/main.go [hunk 18]
```diff
@@ -103,7 +103,7 @@ func main() {
 	defer cacheClient.Close()
 
 	// Setup new auth grpc client
-	auth, authHandler, err := authClient.Setup(envPrefix, cfg.JaegerURL)
+	auth, authHandler, err := authClient.Setup(envPrefix, "localhost:6831")
```
Comment (rodneyosodo) [inline cmd/things/main.go]: Revert

File: cli/users.go [hunk 19]
```diff
@@ -250,9 +250,9 @@ var cmdUsers = []cobra.Command{
 		},
 	},
 	{
-		Use:   "password <old_password> <password> <user_auth_token>",
-		Short: "Update password",
-		Long:  `Update user password`,
+		Use:   "updatetags <user_id> <tags> <user_auth_token>",
+		Short: "Update user tags",
+		Long:  `Update user tags`,
```
Comment (rodneyosodo) [inline cli/users.go]: revert

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

File: things/groups/service.go (hunk 17 above)
Comment (SammyOina) [reply things/groups/service.go:11]: why use an aliases when one is not required

File: internal/mainflux/groups/errors.go (hunk 6 above)
Comment (SammyOina) [reply internal/mainflux/groups/errors.go]: it's just one variable hard to justify creating a file for it

File: readers/api/transport.go (hunk 14 above)
Comment (SammyOina) [reply readers/api/transport.go:18]: why use an alias when one is not required

Comment (SammyOina) [reply readers/api/transport.go:18]: why use an alias when one is not required

File: internal/mainflux/groups/errors.go (hunk 15 above)
Comment (SammyOina) [reply internal/mainflux/groups/errors.go]: only one error i similar so not really

File: things/groups/api/logging.go (hunk 16 above)
Comment (SammyOina) [reply things/groups/api/logging.go:10]: Page struct is a bit different and that would still result in two interfaces

File: bootstrap/api/endpoint_test.go [hunk 20]
```diff
@@ -34,7 +34,6 @@ import (
 	tpolicies "github.com/mainflux/mainflux/things/policies"
 	papi "github.com/mainflux/mainflux/things/policies/api/http"
 	"github.com/mainflux/mainflux/users/policies"
-	upolicies "github.com/mainflux/mainflux/users/policies"
```
Comment (rodneyosodo) [inline bootstrap/api/endpoint_test.go:37]: replace `policies` with `upolicies`

File: bootstrap/redis/producer/streams_test.go [hunk 21]
```diff
@@ -16,19 +16,20 @@ import (
...
+	mfgroups "github.com/mainflux/mainflux/internal/mainflux/groups"
 	mfsdk "github.com/mainflux/mainflux/pkg/sdk/go"
 	"github.com/mainflux/mainflux/things/clients"
 	capi "github.com/mainflux/mainflux/things/clients/api"
 	"github.com/mainflux/mainflux/things/groups"
 	gapi "github.com/mainflux/mainflux/things/groups/api"
 	tpolicies "github.com/mainflux/mainflux/things/policies"
 	papi "github.com/mainflux/mainflux/things/policies/api/http"
-	upolicies "github.com/mainflux/mainflux/users/policies"
+	"github.com/mainflux/mainflux/users/policies"
```
Comment (rodneyosodo) [inline bootstrap/redis/producer/streams_test.go]: same

File: things/groups/service.go (hunk 17 above)
Comment (rodneyosodo) [reply things/groups/service.go:11]: To differentiate between things policies and users policies

File: users/README.md [hunk 22]
```diff
@@ -1,5 +1,6 @@
 # Clients
 
+<<<<<<< HEAD
```
Comment (rodneyosodo) [inline users/README.md]: Fix

File: users/README.md [hunk 23]
```diff
@@ -94,4 +95,7 @@ If `MF_EMAIL_TEMPLATE` doesn't point to any file service will function but passw
 For more information about service capabilities and its usage, please check out
 the [API documentation](https://api.mainflux.io/?urls.primaryName=users-openapi.yml).
 
-[doc]: https://docs.mainflux.io
\ No newline at end of file
+[doc]: https://docs.mainflux.io
+=======
+Repository for Clients service for handling generic clients
+>>>>>>> 12a7bd753 (Move Things and Users to Clients)
```
Comment (rodneyosodo) [inline users/README.md]: Same

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

File: bootstrap/mocks/channels.go [hunk 24]
```diff
@@ -18,26 +20,26 @@ var _ groups.Service = (*mainfluxChannels)(nil)
...
-func NewChannelsService(channels map[string]groups.Group, auth upolicies.AuthServiceClient) groups.Service {
+func NewChannelsService(channels map[string]mfgroups.Group, auth upolicies.AuthServiceClient) groups.Service {
 	return &mainfluxChannels{
 		channels: channels,
 		auth:     auth,
 	}
 }
 
-func (svc *mainfluxChannels) CreateGroups(_ context.Context, token string, chs ...groups.Group) ([]groups.Group, error) {
+func (svc *mainfluxChannels) CreateGroups(_ context.Context, token string, chs ...mfgroups.Group) ([]mfgroups.Group, error) {
```
Comment (rodneyosodo) [inline bootstrap/mocks/channels.go]:
```suggestion
func (svc *mainfluxChannels) CreateGroups(ctx context.Context, token string, chs ...mfgroups.Group) ([]mfgroups.Group, error) {
```

File: bootstrap/mocks/channels.go [hunk 25]
```diff
@@ -18,26 +20,26 @@ var _ groups.Service = (*mainfluxChannels)(nil)
...
 	svc.mu.Lock()
 	defer svc.mu.Unlock()
 
 	userID, err := svc.auth.Identify(context.Background(), &upolicies.Token{Value: token})
```
Comment (rodneyosodo) [inline bootstrap/mocks/channels.go]:
```suggestion
	userID, err := svc.auth.Identify(ctx, &upolicies.Token{Value: token})
```

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
What about renaming `internal/mainflux` to `internal/entities`. `Mainflux` sounds misleading

File: bootstrap/mocks/channels.go (hunk 24 above)
Comment (SammyOina) [reply bootstrap/mocks/channels.go]: Not really part of this PR

File: bootstrap/mocks/channels.go (hunk 25 above)
Comment (SammyOina) [reply bootstrap/mocks/channels.go]: not really part of this PR

**Comment by rodneyosodo** [comment]
Rebase

**Review by dborovcanin — CHANGES_REQUESTED** [review]
@SammyOina Please resolve conflicts so we can review.

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Let's move `internal/mainflux/` to root `clients/`. Also, move Client structs from `things/clients` and `users/clients` to this new package.

File: pkg/clients/clients.go [hunk 26]
```diff
@@ -0,0 +1,184 @@
...
+	return json.Marshal(r.String())
+}
+
+func (r *Role) UnmarshalJSON(data []byte) error {
+	str := strings.Trim(string(data), "\"")
+	val, err := ToRole(str)
+	*r = val
+	return err
+}
+
```
Comment (dborovcanin) [inline pkg/clients/clients.go]: Move this to `roles.go`.

File: pkg/clients/clients.go [hunk 27]
```diff
@@ -0,0 +1,184 @@
...
+// MembersPage contains page related metadata as well as list of members that
+// belong to this page.
+type MembersPage struct {
+	Page
+	Members []Client
+}
+
+// ClientRepository specifies an account persistence API.
```
Comment (dborovcanin) [inline pkg/clients/clients.go]: Fix comment: ClientRepository -> Repository.

File: pkg/clients/page.go [hunk 28]
```diff
@@ -1,8 +1,5 @@
 package clients
 
-// Metadata represents arbitrary JSON.
```
Comment (dborovcanin) [inline pkg/clients/page.go:3]: Since the Groups page does not embed Page, you can move all the ClientsPage data here and use only this one.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
