### PR TITLE
NOISSUE - Fix OPC-UA adapter

### LINKED ISSUE #2037: Verify OPC-UA
Verify that OPC-UA adapter is functional. Enhance documentation with diagrams in [DrawIO](https://app.diagrams.net/).  Give some examples of usage.

### PR DESCRIPTION
**Pull request by WashingtonKK**
# What type of PR is this?

This is a bug fix because it fixes the opc-ua adapter and makes it fully functional.

## What does this do?

Rectifies the node-id parsing, modifies event handling to sync with things service events to allow the adapter to work as expected.

## Which issue(s) does this PR fix/relate to?

Resolves #2037

## Have you included tests for your changes?

No

## Did you document any new/modified feature?

Yes, documentation is updated.

### CODE REVIEW

**Comment by drasko** [comment]
@arvindh123 and @rodneyosodo please review this PR

File: opcua/adapter.go [hunk 1]
```diff
@@ -132,7 +134,26 @@ func (as *adapterService) ConnectThing(ctx context.Context, chanID, thingID stri
 }
 
 func (as *adapterService) Browse(ctx context.Context, serverURI, namespace, identifier string) ([]BrowsedNode, error) {
-	nodeID := fmt.Sprintf("%s;%s", namespace, identifier)
+	var nodeID string
```
Comment (arvindh123) [inline opcua/adapter.go]: @WashingtonKK 

At present , for browser request we have only Namespace and Identified ,
```go
type browseReq struct {
	ServerURI  string
	Namespace  string
	Identifier string
}
```
https://github.com/absmach/magistrala/blob/main/opcua/api/requests.go#L8-L12

Here Identifier is Node ID , In OPCUA Node ID can be integer, string , GUID or base64String of binary data   

In present version supports it supports only integer type

It is good to have support for different types , But  it can't be in config, 

Because server can have mixed type of Node ID

So better to have it in request  
```go
type browseReq struct {
	ServerURI  string
	Namespace  string
	Identifier string
	IdentifierType string
}
```

Comment (WashingtonKK) [reply opcua/adapter.go]: Fixed @arvindh123

File: internal/groups/events/events.go [hunk 2]
```diff
@@ -34,6 +38,42 @@ var (
...
+	groupID   string
+	createdAt time.Time
+}
+
+func (cge assignEvent) Encode() (map[string]interface{}, error) {
+	val := map[string]interface{}{
+		"operation":  groupAssign,
+		"member_id":  cge.memberID,
+		"group_id":   cge.groupID,
+		"created_at": cge.createdAt,
```
Comment (rodneyosodo) [inline internal/groups/events/events.go]: We don't need `created_at`

File: internal/groups/events/streams.go [hunk 3]
```diff
@@ -140,10 +141,39 @@ func (es eventStore) EnableGroup(ctx context.Context, token, id string) (groups.
...
 func (es eventStore) Assign(ctx context.Context, token, groupID, relation, memberKind string, memberIDs ...string) error {
-	return es.svc.Assign(ctx, token, groupID, relation, memberKind, memberIDs...)
+	if err := es.svc.Assign(ctx, token, groupID, relation, memberKind, memberIDs...); err != nil {
+		return err
+	}
+
+	event := assignEvent{
+		operation: "group.assign",
+		groupID:   groupID,
+		memberID:  memberIDs[0],
```
Comment (rodneyosodo) [inline internal/groups/events/streams.go]:
```suggestion
		memberIDs:  memberIDs...,
```

File: opcua/events/streams.go [hunk 4]
```diff
@@ -108,8 +109,12 @@ func (es *eventHandler) Handle(ctx context.Context, event events.Event) error {
 
 func decodeCreateThing(event map[string]interface{}) (createThingEvent, error) {
 	strmeta := read(event, "metadata", "{}")
+	meta, err := base64.StdEncoding.DecodeString(strmeta)
```
Comment (rodneyosodo) [inline opcua/events/streams.go:114]: events are not base64 encoded why are we decoding from base64?

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

File: opcua/events/streams.go (hunk 4 above)
Comment (WashingtonKK) [reply opcua/events/streams.go:114]: Metadata is base64 encoded since it is marshaled as a slice of bytes

Comment (WashingtonKK) [reply opcua/events/streams.go:114]: This is a special case

Comment (WashingtonKK) [reply opcua/events/streams.go:114]: image

File: internal/groups/events/events.go [hunk 5]
```diff
@@ -34,6 +38,38 @@ var (
...
+type assignEvent struct {
+	operation string
+	memberIDs []string
+	groupID   string
+}
+
+func (cge assignEvent) Encode() (map[string]interface{}, error) {
+	val := map[string]interface{}{
+		"operation": groupAssign,
+		"member_id": cge.memberIDs,
```
Comment (rodneyosodo) [inline internal/groups/events/events.go]:
```suggestion
		"member_ids": cge.memberIDs,
```

File: internal/groups/events/events.go [hunk 6]
```diff
@@ -34,6 +38,38 @@ var (
...
+type unassignEvent struct {
+	operation string
+	memberIDs []string
+	groupID   string
+}
+
+func (cge unassignEvent) Encode() (map[string]interface{}, error) {
+	val := map[string]interface{}{
+		"operation": groupUnassign,
+		"member_id": cge.memberIDs,
```
Comment (rodneyosodo) [inline internal/groups/events/events.go]:
```suggestion
		"member_ids": cge.memberIDs,
```

File: opcua/adapter.go [hunk 7]
```diff
@@ -102,37 +103,62 @@ func (as *adapterService) RemoveChannel(ctx context.Context, chanID string) erro
...
+	switch identifierType {
+	case "string":
+		nodeID = fmt.Sprintf("ns=%s;s=%s", namespace, identifier)
+	case "numeric":
+		numericIdentifier, err := strconv.Atoi(identifier) // Convert identifier to int
+		if err != nil {
+			nodeID = fmt.Sprintf("ns=%s;s=%s", namespace, identifier)
+			as.logger.Warn(fmt.Sprintf("failed to parse numeric nodeID format: %s, defaulting to string", err))
+			break
+		}
```
Comment (arvindh123) [inline opcua/adapter.go]: Please pass arguments to logger instead of fmt.Sprintf(), Arguements gives us json output.
For instance
```suggestion
		if err != nil {
			args := []any{
				slog.String("namespace", namespace),
				slog.String("identifier", identifier),
				slog.String("error", err.Error()),
			}
			as.logger.Warn("failed to parse numeric identifier", args...)
			break
		}
```

File: opcua/adapter.go [hunk 8]
```diff
@@ -102,37 +103,62 @@ func (as *adapterService) RemoveChannel(ctx context.Context, chanID string) erro
...
+			return err
+		}
 
-	go func() {
-		if err := as.subscriber.Subscribe(ctx, as.cfg); err != nil {
-			as.logger.Warn(fmt.Sprintf("subscription failed: %s", err))
+		go func() {
+			if err := as.subscriber.Subscribe(ctx, as.cfg); err != nil {
+				as.logger.Warn(fmt.Sprintf("subscription failed: %s", err))
+			}
```
Comment (arvindh123) [inline opcua/adapter.go:134]: Same here
```suggestion
				as.logger.Warn("subscription failed", slog.String("error", err.Error()))
```

File: internal/groups/events/streams.go [hunk 9]
```diff
@@ -140,10 +140,37 @@ func (es eventStore) EnableGroup(ctx context.Context, token, id string) (groups.
 }
 
 func (es eventStore) Assign(ctx context.Context, token, groupID, relation, memberKind string, memberIDs ...string) error {
-	return es.svc.Assign(ctx, token, groupID, relation, memberKind, memberIDs...)
+	if err := es.svc.Assign(ctx, token, groupID, relation, memberKind, memberIDs...); err != nil {
+		return err
+	}
+
+	event := assignEvent{
+		operation: "group.assign",
```
Comment (rodneyosodo) [inline internal/groups/events/streams.go]: The `operation` should be added when doing `event.Encode`

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

File: opcua/adapter.go [hunk 10]
```diff
@@ -33,24 +34,24 @@ type Service interface {
 	RemoveChannel(ctx context.Context, chanID string) error
 
 	// ConnectThing creates thingID:channelID route-map
-	ConnectThing(ctx context.Context, chanID, thingID string) error
+	ConnectThing(ctx context.Context, chanID string, thingIDs []string) error
 
 	// DisconnectThing removes thingID:channelID route-map
-	DisconnectThing(ctx context.Context, chanID, thingID string) error
+	DisconnectThing(ctx context.Context, chanID string, thingID []string) error
```
Comment (rodneyosodo) [inline opcua/adapter.go]:
```suggestion
	DisconnectThing(ctx context.Context, chanID string, thingIDs []string) error
```

File: opcua/adapter.go [hunk 11]
```diff
@@ -102,37 +103,67 @@ func (as *adapterService) RemoveChannel(ctx context.Context, chanID string) erro
...
 	serverURI, err := as.channelsRM.Get(ctx, chanID)
 	if err != nil {
 		return err
 	}
 
-	nodeID, err := as.thingsRM.Get(ctx, thingID)
-	if err != nil {
-		return err
-	}
+	for _, t := range thingIDs {
```
Comment (rodneyosodo) [inline opcua/adapter.go]:
```suggestion
	for _, thingID := range thingIDs {
```

File: opcua/adapter.go [hunk 12]
```diff
@@ -141,7 +172,12 @@ func (as *adapterService) Browse(ctx context.Context, serverURI, namespace, iden
 	return nodes, nil
 }
 
-func (as *adapterService) DisconnectThing(ctx context.Context, chanID, thingID string) error {
-	c := fmt.Sprintf("%s:%s", chanID, thingID)
-	return as.connectRM.Remove(ctx, c)
+func (as *adapterService) DisconnectThing(ctx context.Context, chanID string, thingIDs []string) error {
+	for _, t := range thingIDs {
```
Comment (rodneyosodo) [inline opcua/adapter.go]: same

File: opcua/api/logging.go [hunk 13]
```diff
@@ -134,12 +134,12 @@ func (lm loggingMiddleware) RemoveChannel(ctx context.Context, mgxChanID string)
...
 }
 
-func (lm loggingMiddleware) ConnectThing(ctx context.Context, mgxChanID, mgxThingID string) (err error) {
+func (lm loggingMiddleware) ConnectThing(ctx context.Context, mgxChanID string, mgxThingIDs []string) (err error) {
 	defer func(begin time.Time) {
 		args := []any{
 			slog.String("duration", time.Since(begin).String()),
 			slog.String("channel_id", mgxChanID),
-			slog.String("thing_id", mgxThingID),
+			slog.Any("thing_id", mgxThingIDs),
```
Comment (rodneyosodo) [inline opcua/api/logging.go]:
```suggestion
			slog.Any("thing_ids", mgxThingIDs),
```

File: opcua/api/logging.go [hunk 14]
```diff
@@ -149,15 +149,15 @@ func (lm loggingMiddleware) ConnectThing(ctx context.Context, mgxChanID, mgxThin
...
 }
 
-func (lm loggingMiddleware) DisconnectThing(ctx context.Context, mgxChanID, mgxThingID string) (err error) {
+func (lm loggingMiddleware) DisconnectThing(ctx context.Context, mgxChanID string, mgxThingIDs []string) (err error) {
 	defer func(begin time.Time) {
 		args := []any{
 			slog.String("duration", time.Since(begin).String()),
 			slog.String("channel_id", mgxChanID),
-			slog.String("thing_id", mgxThingID),
+			slog.Any("thing_id", mgxThingIDs),
```
Comment (rodneyosodo) [inline opcua/api/logging.go]: same

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

File: opcua/adapter.go [hunk 15]
```diff
@@ -102,37 +103,67 @@ func (as *adapterService) RemoveChannel(ctx context.Context, chanID string) erro
...
+		if err := as.connectRM.Save(ctx, c, c); err != nil {
+			return err
+		}
 
-	go func() {
-		if err := as.subscriber.Subscribe(ctx, as.cfg); err != nil {
-			as.logger.Warn(fmt.Sprintf("subscription failed: %s", err))
+		go func() {
+			if err := as.subscriber.Subscribe(ctx, as.cfg); err != nil {
+				as.logger.Warn("subscription failed", slog.String("error", err.Error()))
```
Comment (rodneyosodo) [inline opcua/adapter.go]:
```suggestion
				as.logger.Warn("subscription failed", slog.Any("error", err))
```

File: opcua/adapter.go [hunk 16]
```diff
@@ -102,37 +103,67 @@ func (as *adapterService) RemoveChannel(ctx context.Context, chanID string) erro
...
+	case "string":
+		nodeID = fmt.Sprintf("ns=%s;s=%s", namespace, identifier)
+	case "numeric":
+		numericIdentifier, err := strconv.Atoi(identifier) // Convert identifier to int
+		if err != nil {
+			nodeID = fmt.Sprintf("ns=%s;s=%s", namespace, identifier)
+			args := []any{
+				slog.String("namespace", namespace),
+				slog.String("identifier", identifier),
+				slog.String("error", err.Error()),
```
Comment (rodneyosodo) [inline opcua/adapter.go]: same

File: opcua/adapter.go [hunk 17]
```diff
@@ -102,37 +103,67 @@ func (as *adapterService) RemoveChannel(ctx context.Context, chanID string) erro
...
+func (as *adapterService) Browse(ctx context.Context, serverURI, namespace, identifier, identifierType string) ([]BrowsedNode, error) {
+	var nodeID string
+
+	switch identifierType {
+	case "string":
+		nodeID = fmt.Sprintf("ns=%s;s=%s", namespace, identifier)
+	case "numeric":
+		numericIdentifier, err := strconv.Atoi(identifier) // Convert identifier to int
+		if err != nil {
+			nodeID = fmt.Sprintf("ns=%s;s=%s", namespace, identifier)
```
Comment (rodneyosodo) [inline opcua/adapter.go]: Where is this used?

File: opcua/api/logging.go [hunk 18]
```diff
@@ -167,10 +167,10 @@ func (lm loggingMiddleware) DisconnectThing(ctx context.Context, mgxChanID, mgxT
 		lm.logger.Info("Disconnect thing from channel completed successfully", args...)
 	}(time.Now())
 
-	return lm.svc.DisconnectThing(ctx, mgxChanID, mgxThingID)
+	return lm.svc.DisconnectThing(ctx, mgxChanID, mgxThingIDs)
 }
 
-func (lm loggingMiddleware) Browse(ctx context.Context, serverURI, namespace, identifier string) (nodes []opcua.BrowsedNode, err error) {
+func (lm loggingMiddleware) Browse(ctx context.Context, serverURI, namespace, identifier, identifierType string) (nodes []opcua.BrowsedNode, err error) {
```
Comment (rodneyosodo) [inline opcua/api/logging.go:173]: Also log the identifier type

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

File: opcua/adapter.go (hunk 17 above)
Comment (WashingtonKK) [reply opcua/adapter.go]: It is returned in case there is an error when creating the numeric nodeID.

File: opcua/api/logging.go [hunk 19]
```diff
@@ -167,16 +167,17 @@ func (lm loggingMiddleware) DisconnectThing(ctx context.Context, mgxChanID, mgxT
...
 	defer func(begin time.Time) {
 		args := []any{
 			slog.String("duration", time.Since(begin).String()),
 			slog.String("server_uri", serverURI),
 			slog.String("namespace", namespace),
 			slog.String("identifier", identifier),
+			slog.String("identifierType", identifierType),
```
Comment (rodneyosodo) [inline opcua/api/logging.go]: Use snake case
```suggestion
			slog.String("identifier_type", identifierType),
```

File: opcua/adapter.go [hunk 20]
```diff
@@ -33,24 +34,24 @@ type Service interface {
...
 // Config OPC-UA Server.
 type Config struct {
 	ServerURI string
 	NodeID    string
-	Interval  string `env:"MG_OPCUA_ADAPTER_INTERVAL_MS"   envDefault:"1000"`
-	Policy    string `env:"MG_OPCUA_ADAPTER_POLICY"        envDefault:""`
-	Mode      string `env:"MG_OPCUA_ADAPTER_MODE"          envDefault:""`
-	CertFile  string `env:"MG_OPCUA_ADAPTER_CERT_FILE"     envDefault:""`
-	KeyFile   string `env:"MG_OPCUA_ADAPTER_KEY_FILE"      envDefault:""`
+	Interval  string `env:"MG_OPCUA_ADAPTER_INTERVAL_MS"     envDefault:"1000"`
```
Comment (rodneyosodo) [inline opcua/adapter.go:52]: Remove extra spaces in between
```suggestion
	Interval  string `env:"MG_OPCUA_ADAPTER_INTERVAL_MS" envDefault:"1000"`
```

File: opcua/events/streams.go [hunk 21]
```diff
@@ -144,8 +151,12 @@ func decodeRemoveThing(event map[string]interface{}) removeThingEvent {
 
 func decodeCreateChannel(event map[string]interface{}) (createChannelEvent, error) {
 	strmeta := read(event, "metadata", "{}")
+	meta, err := base64.StdEncoding.DecodeString(strmeta)
+	if err != nil {
+		return createChannelEvent{}, err
+	}
 	var metadata map[string]interface{}
-	if err := json.Unmarshal([]byte(strmeta), &metadata); err != nil {
+	if err := json.Unmarshal([]byte(meta), &metadata); err != nil {
```
Comment (rodneyosodo) [inline opcua/events/streams.go]:
```suggestion
	if err := json.Unmarshal(meta, &metadata); err != nil {
```

File: opcua/events/streams.go [hunk 22]
```diff
@@ -200,3 +211,19 @@ func read(event map[string]interface{}, key, def string) string {
...
+	}
+
+	for _, v := range val {
+		if str, ok := v.(string); ok {
+			memberIDs = append(memberIDs, str)
+		}
+	}
+
+	return memberIDs
+}
```
Comment (rodneyosodo) [inline opcua/events/streams.go:229]:
```go
func readMemberIDs(event map[string]interface{}, key string) []string {
	ids, ok := event[key].([]string)
	if !ok {
		return []string{}
	}

	return ids
}
```

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

File: opcua/events/streams.go (hunk 22 above)
Comment (WashingtonKK) [reply opcua/events/streams.go:229]: This doesn't work.

**Review by arvindh123 — DISMISSED** [review]

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Can you also use this PR to migrate to the latest version of the `github.com/gopcua/opcua` library?

File: opcua/adapter.go [hunk 23]
```diff
@@ -102,37 +103,67 @@ func (as *adapterService) RemoveChannel(ctx context.Context, chanID string) erro
...
-	return db.Save(serverURI, nodeID)
+	return nil
 }
 
-func (as *adapterService) Browse(ctx context.Context, serverURI, namespace, identifier string) ([]BrowsedNode, error) {
-	nodeID := fmt.Sprintf("%s;%s", namespace, identifier)
+func (as *adapterService) Browse(ctx context.Context, serverURI, namespace, identifier, identifierType string) ([]BrowsedNode, error) {
+	var nodeID string
+
+	switch identifierType {
```
Comment (dborovcanin) [inline opcua/adapter.go:148]: You can simplify a little bit with something like:
```go
func (as *adapterService) Browse(ctx context.Context, serverURI, namespace, identifier, identifierType string) ([]BrowsedNode, error) {
	idFormat := "s"
	switch identifierType {
	case "string": // Only for the sake of the efficiency, since the first case is the most likely to happen.
		break
	case "numeric":
		if _, err := strconv.Atoi(identifier); err != nil {
			args := []any{
				slog.String("namespace", namespace),
				slog.String("identifier", identifier),
				slog.Any("error", err),
			}
			as.logger.Warn("failed to parse numeric identifier", args...)
			break
		}
		idFormat = "i"
	case "guid":
		idFormat = "g"
	case "opaque":
		idFormat = "b"
	}
	nodeID := fmt.Sprintf("ns=%s;%s=%s", namespace, idFormat, identifier)
	nodes, err := as.browser.Browse(serverURI, nodeID)
	if err != nil {
		return nil, err
	}
	return nodes, nil
}
```

File: opcua/adapter.go [hunk 24]
```diff
@@ -102,37 +103,67 @@ func (as *adapterService) RemoveChannel(ctx context.Context, chanID string) erro
...
+			args := []any{
+				slog.String("namespace", namespace),
+				slog.String("identifier", identifier),
+				slog.Any("error", err),
+			}
+			as.logger.Warn("failed to parse numeric identifier", args...)
+			break
+		}
+		nodeID = fmt.Sprintf("ns=%s;i=%d", namespace, numericIdentifier)
+	case "guid":
```
Comment (dborovcanin) [inline opcua/adapter.go:162]: Does this format have any restrictions, so we can maybe do validation similar to `numeric` case?

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
