### PR TITLE
SMQ-3253 - Update CLI usage

### LINKED ISSUE #3253: Bug: Update CLI Usage
### What were you trying to achieve?

The currently the usage is not clear after changing the ordering of arguments. For example:

`usage: users <user_id_or_all> <operation> [args...]`

### What are the expected results?

I expect the user to get the commands that are also available:

`usage: users <user_id|all|create|token|refreshtoken|profile|resetpasswordrequest|resetpassword|password|search> [operation] [args...]`

### What are the received results?

`usage: users <user_id_or_all> <operation> [args...]`

### Steps To Reproduce

Run the CLI without all the commands.

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?

## Which issue(s) does this PR fix/relate to?

- Related Issue #3253
- Resolves #3253

### CODE REVIEW

File: cli/users.go [hunk 1]
```diff
@@ -83,25 +94,58 @@ Examples:
 				handleVerify(cmd, args[1])
 				return
 			case token:
-				handleUserToken(cmd, args[1], args[2:])
+				if len(args) < 2 {
+					handleUserToken(cmd, "", []string{})
+				} else {
+					handleUserToken(cmd, args[1], args[2:])
+				}
```
Comment (dborovcanin) [inline cli/users.go]: Previous approach was cleaner. Why do we need these checks, what's the reason for an empty first param?

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Since there are no cases where we need <2 args, can we avoid these checks by extracting them before `switch` and after zero check, like:
```go
			if len(args) < 2 {
				logUsageCmd(*cmd, args[0])
				return
			}
```

Also, please use this PR to fix camelcase - `refreshToken`, `ResetPasswordReq`, `ResetPassword`...

**Review by dborovcanin — APPROVED** [review]
