### PR TITLE
MF-1516 - Fix API key issuing

### LINKED ISSUE #1516: API key not saved in DB
**BUG REPORT**

1. What were you trying to achieve?
To get ID of created API key.
2. What are the expected results?
After creating API key in Location header should be key ID. 
3. What are the received results?
API key is created but it is not saved in AuthDB, and Location header is empty.
4. What are the steps to reproduce the issue?
```bash
curl -isSX POST  http://localhost/keys -H 'Content-Type: application/json' -d '{"type":0, "token":"<user_token>", "duration":100000}'
```
5. In what environment did you encounter the issue?
Docker
6. Additional information you deem important:
Because it is not saved, cant get key ID.
Revoke API key and get API key details endpoints could not be executed without key ID.

### PR DESCRIPTION
**Pull request by fbugarski**
Signed-off-by: Filip Bugarski <filipbugarski@gmail.com>

### What does this do?
This pull request fixes issue with storing Mainflux API keys.

### Which issue(s) does this PR fix/relate to?
Fixes #1516.

### List any changes that modify/break current functionality
The only API key can be created by the user HTTP API.

### Have you included tests for your changes?
Yes. Tests are fixed to match new changes.

### Did you document any new/modified functionality?
Yes.

### Notes
N/A

### CODE REVIEW

File: auth/service.go [hunk 1]
```diff
@@ -167,7 +167,15 @@ func (svc service) Identify(ctx context.Context, token string) (Identity, error)
 	}
 
 	switch key.Type {
-	case APIKey, RecoveryKey, UserKey:
+	case RecoveryKey, LoginKey:
+
```
Comment (dborovcanin) [inline auth/service.go]: Remove the empty line.

File: auth/service.go [hunk 2]
```diff
@@ -167,7 +167,15 @@ func (svc service) Identify(ctx context.Context, token string) (Identity, error)
...
+		return Identity{ID: key.IssuerID, Email: key.Subject}, nil
+	case APIKey:
+
```
Comment (dborovcanin) [inline auth/service.go]: Same here.

File: auth/api/logging.go [hunk 3]
```diff
@@ -1,6 +1,7 @@
 // Copyright (c) Mainflux
 // SPDX-License-Identifier: Apache-2.0
 
+//go:build !test
```
Comment (dborovcanin) [inline auth/api/logging.go:4]: What's this update?

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — DISMISSED** [review]

File: auth/api/http/keys/endpoint_test.go [hunk 4]
```diff
@@ -85,14 +85,14 @@ func toJSON(data interface{}) string {
...
-	assert.Nil(t, err, fmt.Sprintf("Issuing user key expected to succeed: %s", err))
+	_, loginSecret, err := svc.Issue(context.Background(), "", auth.Key{Type: auth.LoginKey, IssuedAt: time.Now(), IssuerID: id, Subject: email})
+	assert.Nil(t, err, fmt.Sprintf("Issuing login key expected to succeed: %s", err))
 
 	ts := newServer(svc)
 	defer ts.Close()
 	client := ts.Client()
 
-	uk := issueRequest{Type: auth.UserKey}
+	uk := issueRequest{Type: auth.LoginKey}
```
Comment (arvindh123) [inline auth/api/http/keys/endpoint_test.go]: `uk` can be changed to `lk`

File: auth/api/http/keys/endpoint_test.go [hunk 5]
```diff
@@ -104,11 +104,11 @@ func TestIssue(t *testing.T) {
 		status int
 	}{
 		{
```
Comment (arvindh123) [inline auth/api/http/keys/endpoint_test.go:106]: Status Created case is missing

File: auth/service_test.go [hunk 6]
```diff
@@ -58,7 +58,7 @@ func TestIssue(t *testing.T) {
 		{
 			desc: "issue user key",
```
Comment (arvindh123) [inline auth/service_test.go]: Description can be changed to `issue login key`

File: auth/service_test.go [hunk 7]
```diff
@@ -67,7 +67,7 @@ func TestIssue(t *testing.T) {
 		{
 			desc: "issue user key with no time",
```
Comment (arvindh123) [inline auth/service_test.go]: Description shall  be changed to `login key`

File: auth/service_test.go [hunk 8]
```diff
@@ -180,7 +180,7 @@ func TestRetrieve(t *testing.T) {
 		IssuedAt: time.Now(),
 	}
 
-	_, userToken, err := svc.Issue(context.Background(), "", auth.Key{Type: auth.UserKey, IssuedAt: time.Now(), IssuerID: id, Subject: email})
+	_, userToken, err := svc.Issue(context.Background(), "", auth.Key{Type: auth.LoginKey, IssuedAt: time.Now(), IssuerID: id, Subject: email})
 	assert.Nil(t, err, fmt.Sprintf("Issuing user key expected to succeed: %s", err))
```
Comment (arvindh123) [inline auth/service_test.go]: `user key` shall  be changed to `login key`
 and also in line number `187`

File: auth/api/http/keys/endpoint_test.go (hunk 5 above)
Comment (fbugarski) [reply auth/api/http/keys/endpoint_test.go:106]: https://github.com/mainflux/mainflux/pull/1530/files/239cd8e8bbbc46f76ea0f8da5c2a331c60c8a1a4#diff-855631aac9bb09a01068f36624d2f806e885c9e055b9a08f4c351d69adf16ccfR118

Comment (fbugarski) [reply auth/api/http/keys/endpoint_test.go:106]: Line 118

Comment (arvindh123) [reply auth/api/http/keys/endpoint_test.go:106]: Line 118 have test for `ak`  - `api key` 
But in `master` the there is test case for `user key` aka `login key` 
https://github.com/mainflux/mainflux/blob/ad8b7ddf5afac43699f7080d006dd40de0559222/auth/api/http/keys/endpoint_test.go#L107

Comment (fbugarski) [reply auth/api/http/keys/endpoint_test.go:106]: You cant create login key over HTTP API anymore.

**Review by dborovcanin — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM
