### PR TITLE
MF-1901 - Return `ThingID` on Authorize

### LINKED ISSUE #1901: Things Authorize Returns `ThingKey` Instead of `ThingID`
**BUG REPORT**

1. What were you trying to achieve?
During publshling from `coap`, `ws` and `http` adapters the publisher is the ThingID instead of ThingKey

2. What are the expected results?
Things Authorize to return `thingID` instead of `thingKey`

3. What are the received results?
Things Authorize sercive returns `thingKey` since it is the one on accessrequest `Subject` as depicted here https://github.com/mainflux/mainflux/blob/320921a63e541a92099ff563434ad08b69615f66/things/policies/service.go#L93

4. What are the steps to reproduce the issue?
Try publishing with `mqtt` and `coap` adapters seperately

5. In what environment did you encounter the issue?
master

6. Additional information you deem important:
Cache should return `thingID` as subject rather than `thingKey`

### PR DESCRIPTION
**Pull request by rodneyosodo**
### What does this do?
Change the policies cache signature to accept both policies action and `thingID`. `ThingID` is appended to actions

### Which issue(s) does this PR fix/relate to?
Resolves #1901 

### List any changes that modify/break current functionality
Listed above on what the PR does.

### Have you included tests for your changes?
Yes

### Did you document any new/modified functionality?
On code

### Notes
To be merged after https://github.com/mainflux/mainflux/pull/1899

### CODE REVIEW

File: things/policies/service.go [hunk 1]
```diff
@@ -285,3 +297,31 @@ func (svc service) usersAuthorize(ctx context.Context, subject, object, action,
...
+
+// separateActions is used to separate the actions from the cache values.
+func separateActions(actions string) []string {
+	return strings.Split(actions, kvSeparator)
+}
+
+// extractThingID is used to extract the thingID from the cache values.
+func extractThingID(actions string) string {
+	var lastIdx = strings.LastIndex(actions, kvSeparator)
+
```
Comment (dborovcanin) [inline things/policies/service.go]: Move this back to the `redis` implementation, even at the cost of creating an additional structure in the `redis` pkg used as a DTO to avoid circular imports.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: things/policies/redis/policies.go [hunk 2]
```diff
@@ -31,41 +30,77 @@ func NewCache(client *redis.Client, duration time.Duration) policies.Cache {
...
+	if thingID == "" {
+		return policies.Policy{}, "", errors.ErrNotFound
 	}
-	policy.Actions = strings.Split(actions, separator)
-	return policy, nil
+
+	policy.Actions = separateActions(val)
+
+	return policy, thingID, nil
+
```
Comment (dborovcanin) [inline things/policies/redis/policies.go]: Remove the empty line.

File: things/policies/policies.go [hunk 3]
```diff
@@ -98,10 +98,10 @@ type Service interface {
 // Cache contains channel-thing connection caching interface.
 type Cache interface {
 	// Put adds policy to cahce.
-	Put(ctx context.Context, policy Policy) error
+	Put(ctx context.Context, policy Policy, thingID string) error
```
Comment (dborovcanin) [inline things/policies/policies.go]: Let's create a struct for this specifically:
```go
type CachedPolicy struct {
	ThingID  string
	ThingKey string
	Actions  []string
}
```
and use it in the `Cache`:
```go
// Cache contains channel-thing connection caching interface.
type Cache interface {
	// Put adds policy to cahce.
	Put(ctx context.Context, policy CachedPolicy) error

	// Get retrieves policy from cache.
	Get(ctx context.Context, policy CachedPolicy) (CachedPolicy, error)

	// Remove deletes a policy from the cache.
	Remove(ctx context.Context, policy CachedPolicy) error
}
```

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: things/policies/policies.go [hunk 4]
```diff
@@ -95,16 +95,21 @@ type Service interface {
 	ListPolicies(ctx context.Context, token string, p Page) (PolicyPage, error)
 }
 
+type CachedPolicy struct {
+	Policy  Policy
```
Comment (dborovcanin) [inline things/policies/policies.go]: Let's keep it like this:
```go
type CachedPolicy struct {
    ThingID string
    ThingKey string
    ChannelID string
    Actions []string
}
```
It is cleaner and more self-explanatory.

File: things/policies/redis/policies.go [hunk 5]
```diff
@@ -79,12 +79,12 @@ func (pc pcache) Remove(ctx context.Context, policy policies.Policy) error {
 
 // kv is used to create a key-value pair for caching.
 // If thingID is not empty, it will be appended to the value.
-func kv(p policies.Policy, thingID string) (string, string) {
-	if thingID != "" {
-		return p.Subject + separator + p.Object, strings.Join(p.Actions, separator) + separator + thingID
+func kv(p policies.CachedPolicy) (string, string) {
+	if p.ThingID != "" {
+		return p.Policy.Subject + separator + p.Policy.Object, strings.Join(p.Policy.Actions, separator) + separator + p.ThingID
```
Comment (dborovcanin) [inline things/policies/redis/policies.go]: This looks a little more self-documenting:
```go
// kv is used to create a key-value pair for caching.
// If thingID is not empty, it will be appended to the value.
func kv(p policies.CachedPolicy) (string, string) {
	key := p.ThingKey + separator + p.ChannelID
	val := strings.Join(p.Policy.Actions, separator)
	if p.ThingID != "" {
		val += separator + p.ThingID
	}
	return key, val
}
```

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — DISMISSED** [review]

**Review by dborovcanin — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM
