### PR TITLE
SMQ-3050 - Fix PAT redis connection

### LINKED ISSUE #3050: Bug: Failed to add scope to PAT
### What were you trying to achieve?

I was trying to add scope to PAT

### What are the expected results?

Successfully add scope with status `200`

### What are the received results?

Got a status `400` with the message `connection refused  :6379` which is the redis store

### Steps To Reproduce

1. Create PAT
2. Add scope

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #3050 

## Which issue(s) does this PR fix/relate to?

- Related Issue #3050 
- Resolves #3050 

## Have you included tests for your changes?
Yes. I have tested manually

## Did you document any new/modified feature?
No

### CODE REVIEW

File: groups/middleware/authorization.go [hunk 1]
```diff
@@ -125,7 +127,7 @@ func (am *authorizationMiddleware) CreateGroup(ctx context.Context, session auth
 			Domain:      session.DomainID,
 			SubjectType: policies.UserType,
 			SubjectKind: policies.UsersKind,
-			Subject:     session.DomainUserID,
+			Subject:     subject,
```
Comment (felixgateru) [inline groups/middleware/authorization.go]: I still get an issue creating a group:

`2025-08-07 12:15:18 {"time":"2025-08-07T09:15:18.43624881Z","level":"INFO","msg":"Identify PAT completed successfully","duration":"34.120686ms"}

2025-08-07 12:15:18 {"time":"2025-08-07T09:15:18.437408645Z","level":"INFO","msg":"Authorize PAT completed successfully","duration":"219.531µs","entity_type":"groups","optional_domain_id":"683fec74-b060-4c08-8aef-8b042d80786f","operation":"create","entities":"*"}
2025-08-07 12:15:18 {"time":"2025-08-07T09:15:18.439258673Z","level":"WARN","msg":"Authorize failed","duration":"932.087µs","object":{"id":"683fec74-b060-4c08-8aef-8b042d80786f","type":"domain"},"subject":{"id":"78e1238e-a37d-4186-8328-db6a03783a8c","kind":"","type":"user"},"permission":"membership","error":"failed to perform authorization over the domain"}`

**Review by felixgateru — CHANGES_REQUESTED** [review]

File: auth/service.go [hunk 2]
```diff
@@ -369,6 +369,21 @@ func (svc service) checkUserRole(ctx context.Context, key Key) (err error) {
...
+		Subject:     userID,
+		SubjectType: policies.UserType,
+		Permission:  policies.AdminPermission,
+		Object:      policies.SuperMQObject,
+		ObjectType:  policies.PlatformType,
+	}); err == nil {
+		rl = AdminRole
+	}
+
+	return rl
```
Comment (arvindh123) [inline auth/service.go:384]: Instead of check authorization, We can use spicedb gRPC function `ReadRelationships`, which returns the relation ship name i.e `user` or `admin`  

This can be done in new PR, because `ReadRelationships` is not implemented , it can be added in Policy evaluator `pkg/policies.Evaluator` or Policy Service `pkg/policies.Service`  

Created ticket for this at here https://github.com/absmach/supermq/issues/3064

File: pkg/authn/authsvc/authn.go [hunk 3]
```diff
@@ -47,7 +47,7 @@ func (a authentication) Authenticate(ctx context.Context, token string) (authn.S
 			return authn.Session{}, errors.Wrap(errors.ErrAuthentication, err)
 		}
 
-		return authn.Session{Type: authn.PersonalAccessToken, PatID: res.GetId(), UserID: res.GetUserId()}, nil
+		return authn.Session{Type: authn.PersonalAccessToken, PatID: res.GetId(), UserID: res.GetUserId(), Role: authn.Role(res.GetUserRole())}, nil
```
Comment (arvindh123) [inline pkg/authn/authsvc/authn.go:50]: Why don't we return the Token Type in gRPC response ? 

May be in next PR not in this PR 

Return Token type in gRPC response of AuthenticatePAT and Authenticate

Then we can Combine Authentication and AuthenticationPAT to single gRPC endpoint and combine service functions
Created a ticket for this here https://github.com/absmach/supermq/issues/3063

**Review by arvindh123 — APPROVED** [review]

**Review by felixgateru — APPROVED** [review]
