### PR TITLE
MG-1977 - Check whether user is domain member before sending invitation

### LINKED ISSUE #1977: Bug: Sending invitations to members who have been assigned to the domain directly shouldn't be possible
### What were you trying to achieve?

While logged in as a super admin, I was able to assign a user to a domain directly. However, after the user is added to the domain, I am still able to send an invitation to the user to join the domain

### What are the expected results?

I should not have been able to send an invite to the user since they are already members of the domain

### What are the received results?

I was able to send an invite to a user who was already a member of the domain since they were assigned to the domain directly by the super admin, but this was not reflected in the invitations service.

### Steps To Reproduce

1. create a domain
2. log in with super admin user
3. create a user
4. assign a user to a domain
5. send an invitation to the same user to join the domain

### In what environment did you encounter the issue?

Magistrala invitations service

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by felixgateru**
Signed-off-by: Felix Gateru [1998-felix](mailto:felix.gateru@gmail.com)
# What type of PR is this?
This is a bug fix because it fixes the following issue: #1977

## What does this do?
This pr introduces a check for whether a user to be invited is already part of the domain before an invitation to the domain is sent.

## Which issue(s) does this PR fix/relate to?

- Resolves #1977

## Have you included tests for your changes?
Yes, I have updated tests for my changes.

## Did you document any new/modified feature?
No,

### Notes
None

### CODE REVIEW

**Comment by dborovcanin** [comment]
@1998-felix Is this ready?

**Comment by felixgateru** [comment]
> @1998-felix Is this ready?

Not yet

File: invitations/service.go [hunk 1]
```diff
@@ -29,6 +29,12 @@ func NewService(repo Repository, authClient magistrala.AuthServiceClient, sdk mg
 }
 
 func (svc *service) SendInvitation(ctx context.Context, token string, invitation Invitation) error {
+	domainUserId := auth.EncodeDomainUserID(invitation.DomainID, invitation.UserID)
+	if err := svc.authorize(ctx, domainUserId, auth.MembershipPermission, auth.DomainType, invitation.DomainID); err == nil {
+		// return error if the user is already a member of the domain
+		return svcerr.ErrConflict
```
Comment (WashingtonKK) [inline invitations/service.go]: Wrap this with an error that indicates that the user is already a member of the domain so that it is not mistaken for a situation where the invitation has already been sent to the user.

File: invitations/service.go [hunk 2]
```diff
@@ -29,6 +29,12 @@ func NewService(repo Repository, authClient magistrala.AuthServiceClient, sdk mg
 }
 
 func (svc *service) SendInvitation(ctx context.Context, token string, invitation Invitation) error {
+	domainUserId := auth.EncodeDomainUserID(invitation.DomainID, invitation.UserID)
+	if err := svc.authorize(ctx, domainUserId, auth.MembershipPermission, auth.DomainType, invitation.DomainID); err == nil {
```
Comment (rodneyosodo) [inline invitations/service.go]: Move this auth check after identify

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

**Review by rodneyosodo — DISMISSED** [review]
LGTM

File: invitations/service_test.go [hunk 3]
```diff
@@ -68,7 +85,8 @@ func TestSendInvitation(t *testing.T) {
 			req:         validInvitation,
 			err:         svcerr.ErrAuthentication,
 			authNErr:    svcerr.ErrAuthentication,
-			domainErr:   nil,
+			domainErr:   svcerr.ErrAuthorization,
+			domainErr1:  nil,
```
Comment (WashingtonKK) [inline invitations/service_test.go]: Make this error and the corresponding request more descriptive. e.g. `domainMembershipReq`.

**Review by WashingtonKK — APPROVED** [review]
LGTM

**Review by rodneyosodo — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]
