### PR TITLE
SMQ-2909 Allow different formats for user profile from different oauth providers

### LINKED ISSUE #2909: Bug: Handle SSO providers user profile info serialization more dynamically
### What were you trying to achieve?

Signing in with google

### What are the expected results?

User profile data from Google SSO (and other providers) should correctly serialize into the application's User struct, with given_name mapped to first_name and family_name mapped to last_name (or equivalent), ensuring seamless user creation or login.

### What are the received results?

Google SSO user profile serialization fails because of inconsistent field naming — given_name vs first_name and family_name vs last_name

### Steps To Reproduce

_No response_

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by dorcaslitunya**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #2909 

## What does this do?
User profile data from Google SSO (and other providers) should correctly serialize into the application's User struct even with variances in the user profile different providers give.

## Which issue(s) does this PR fix/relate to?
- Resolves #2909 

- Related Issue #
- Resolves #

## Have you included tests for your changes?
Yes, I have included tests for my changes.

## Did you document any new/modified feature?
No, I have not updated the documentation because it is a bug fix

### CODE REVIEW

File: pkg/oauth2/google/provider.go [hunk 1]
```diff
@@ -14,6 +13,7 @@ import (
 	svcerr "github.com/absmach/supermq/pkg/errors/service"
 	mgoauth2 "github.com/absmach/supermq/pkg/oauth2"
 	uclient "github.com/absmach/supermq/users"
+	"github.com/pkg/errors"
```
Comment (SammyOina) [inline pkg/oauth2/google/provider.go]: use supermq errors or std golang pkg errors
`"github.com/absmach/supermq/pkg/errors"`
`"errors"`

**Review by SammyOina — CHANGES_REQUESTED** [review]

**Review by SammyOina — DISMISSED** [review]

File: pkg/oauth2/normalize.go [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+		FirstName:      user.FirstName,
+		LastName:       user.LastName,
+		Email:          user.Email,
+		ProfilePicture: user.Picture,
+		Metadata:       users.Metadata{"oauth_provider": provider},
+	}, nil
+}
+
+func normalizeProfile(raw map[string]interface{}) map[string]interface{} {
+	normalized := make(map[string]interface{})
```
Comment (dborovcanin) [inline pkg/oauth2/normalize.go]: Use `any` instead of `interface{}`.

File: pkg/oauth2/normalize.go [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+		FirstName:      user.FirstName,
+		LastName:       user.LastName,
+		Email:          user.Email,
+		ProfilePicture: user.Picture,
+		Metadata:       users.Metadata{"oauth_provider": provider},
+	}, nil
+}
+
+func normalizeProfile(raw map[string]any) map[string]any {
+	normalized := make(map[string]interface{})
```
Comment (SammyOina) [inline pkg/oauth2/normalize.go]: any

**Review by SammyOina — CHANGES_REQUESTED** [review]

**Review by SammyOina — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]
