### PR TITLE
MF-1720 - Improve Test Reports

### LINKED ISSUE #1720: Improve test reports
**ENHANCEMENT**
1. Describe the enhancement you are requesting.
When testing listing API (list messages, Things, Users, Channels, whatever), in case of the test failing, currently we have something like:
```
              Error Trace:    /home/dusan/go/src/github.com/mainflux/mainflux/readers/mongodb/messages_test.go:379
                Error:          elements differ

                                extra elements in list A:
                                ([]interface {}) (len=1) {
                                 (senml.Message) {
                                  Channel: (string) (len=36) "6ea5ef3e-7f5a-4461-afe8-100ca0bd3144",
                                  Subtopic: (string) (len=8) "subtopic",
                                  Publisher: (string) (len=36) "22d328e8-5adc-4926-9402-6e6050f94620",
                                  Protocol: (string) (len=4) "http",
                                  Name: (string) (len=11) "temperature",
                                  Unit: (string) "",
                                  Time: (float64) 1.676016362e+09,
                                  UpdateTime: (float64) 0,
                                  Value: (*float64)(<nil>),
                                  StringValue: (*string)(<nil>),
                                  DataValue: (*string)(<nil>),
                                  BoolValue: (*bool)(<nil>),
                                  Sum: (*float64)(42)
                                 }
                                }
...
```
followed by something like:
```
: expected [{6ea5ef3e-7f5a-4461-afe8-100ca0bd3144 subtopic 22d328e8-5adc-4926-9402-6e6050f94620 http temperature  1.676016362e+09 0 <nil> <nil> <nil> <nil> 0x13f9630} {6ea5ef3e-7f5a-4461-afe8-100ca0bd3144  bf5466e0-ca09-41b6-9414-14d0c5da287c mqtt   1.676016361e+09 0 0x13f9638 <nil> <nil> <nil> <nil>} {6ea5ef3e-7f5a-4461-afe8-100ca0bd3144  bf5466e0-ca09-41b6-9414-14d0c5da287c mqtt   1.67601636e+09 0 <nil> <nil> <nil> 0x13f9316 <nil>} {6ea5ef3e-7f5a-4461-afe8-100ca0bd3144  bf5466e0-ca09-41b6-9414-14d0c5da287c mqtt   1.676016359e+09 0 <nil> 0x144fb60 <nil> <nil> <nil>} {6ea5ef3e-7f5a-4461-afe8-100ca0bd3144  bf5466e0-ca09-41b6-9414-14d0c5da287c mqtt   1.676016358e+09 0 <nil> <nil> 0x144fb50 <nil> <nil>} {6ea5ef3e-7f5a-4461-afe8-100ca0bd3144 subtopic 22d328e8-5adc-4926-9402-6e6050f94620 http temperature  1.676016357e+09 0 <nil> <nil> <nil> <nil> 0x13f9630} {6ea5ef3e-7f5a-4461-afe8-100ca0bd3144  bf5466e0-ca09-....
```
which is both useless and unreadable. It says almost nothing about the reasons the test has failed and makes it difficult to understand the content of the list. Not to mention that we don't need **both** these traces. We need to improve those logs so that it's easy to understand and it describes the error better.

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).
This is a should-have.

### PR DESCRIPTION
**Pull request by AryanGodara**
### What does this do?
Updates test files, for better test reports, and overall making test functions more uniform.
### Which issue(s) does this PR fix/relate to?
Resolves #1720

### CODE REVIEW

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Should we move to `assert.Nil` or stick to `require.Nil` ?

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
@AryanGodara move from `require.Nil` to `assert.Nil` where necessary. I am still seeing it under boostrap tests among others

**Review by dborovcanin — DISMISSED** [review]

File: auth/api/grpc/endpoint_test.go
Comment (rodneyosodo) [inline auth/api/grpc/endpoint_test.go:1]: - L132, L135, L138 should be require since we are using them downstream
- same to L201

File: auth/jwt/token_test.go [hunk 1]
```diff
@@ -54,18 +53,18 @@ func TestParse(t *testing.T) {
 	tokenizer := jwt.New(secret)
 
 	token, err := tokenizer.Issue(key())
-	require.Nil(t, err, fmt.Sprintf("issuing key expected to succeed: %s", err))
+	assert.Nil(t, err, fmt.Sprintf("issuing key expected to succeed: %s", err))
```
Comment (rodneyosodo) [inline auth/jwt/token_test.go]: This should be revert to require as the token variable is used downstream

File: auth/jwt/token_test.go [hunk 2]
```diff
@@ -54,18 +53,18 @@ func TestParse(t *testing.T) {
...
 
 	apiKey := key()
 	apiKey.Type = auth.APIKey
 	apiKey.ExpiresAt = time.Now().UTC().Add(-1 * time.Minute).Round(time.Second)
 	apiToken, err := tokenizer.Issue(apiKey)
-	require.Nil(t, err, fmt.Sprintf("issuing user key expected to succeed: %s", err))
+	assert.Nil(t, err, fmt.Sprintf("issuing user key expected to succeed: %s", err))
```
Comment (rodneyosodo) [inline auth/jwt/token_test.go]: This should be revert to require as the token variable is used downstream

File: auth/jwt/token_test.go [hunk 3]
```diff
@@ -54,18 +53,18 @@ func TestParse(t *testing.T) {
...
 
 	expKey := key()
 	expKey.ExpiresAt = time.Now().UTC().Add(-1 * time.Minute).Round(time.Second)
 	expToken, err := tokenizer.Issue(expKey)
-	require.Nil(t, err, fmt.Sprintf("issuing expired key expected to succeed: %s", err))
+	assert.Nil(t, err, fmt.Sprintf("issuing expired key expected to succeed: %s", err))
```
Comment (rodneyosodo) [inline auth/jwt/token_test.go]: This should be revert to require as the token variable is used downstream

File: auth/postgres/groups_test.go [hunk 4]
```diff
@@ -34,7 +34,7 @@ var (
 
 func generateGroupID(t *testing.T) string {
 	grpID, err := ulidProvider.ID()
-	require.Nil(t, err, fmt.Sprintf("got unexpected error: %s", err))
+	assert.Nil(t, err, fmt.Sprintf("got unexpected error: %s", err))
```
Comment (rodneyosodo) [inline auth/postgres/groups_test.go]: This should be reverted to `require`. As we want the groupID.

File: auth/postgres/groups_test.go [hunk 5]
```diff
@@ -44,10 +44,10 @@ func TestGroupSave(t *testing.T) {
 	groupRepo := postgres.NewGroupRepo(dbMiddleware)
 
 	usrID, err := idProvider.ID()
```
Comment (rodneyosodo) [inline auth/postgres/groups_test.go]: Use `generateGroupID`

File: auth/postgres/groups_test.go [hunk 6]
```diff
@@ -44,10 +44,10 @@ func TestGroupSave(t *testing.T) {
...
-	require.Nil(t, err, fmt.Sprintf("got unexpected error: %s", err))
+	assert.Nil(t, err, fmt.Sprintf("got unexpected error: %s", err))
 
 	wrongID, err := ulidProvider.ID()
```
Comment (rodneyosodo) [inline auth/postgres/groups_test.go]: Use `generateGroupID`

File: auth/postgres/groups_test.go [hunk 7]
```diff
@@ -139,8 +139,8 @@ func TestGroupRetrieveByID(t *testing.T) {
 
 	uid, err := idProvider.ID()
```
Comment (rodneyosodo) [inline auth/postgres/groups_test.go]: Use `generateGroupID`

File: auth/postgres/groups_test.go [hunk 8]
```diff
@@ -139,8 +139,8 @@ func TestGroupRetrieveByID(t *testing.T) {
...
 	require.Nil(t, err, fmt.Sprintf("got unexpected error: %s", err))
-
 	require.Nil(t, err, fmt.Sprintf("group id unexpected error: %s", err))
```
Comment (rodneyosodo) [inline auth/postgres/groups_test.go]: Remove one of them

File: bootstrap/api/endpoint_test.go [hunk 9]
```diff
@@ -1174,7 +1174,7 @@ func TestChangeState(t *testing.T) {
 	c := newConfig([]bootstrap.Channel{{ID: "1"}})
 
 	saved, err := svc.Add(context.Background(), validToken, c)
-	require.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
+	assert.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
```
Comment (rodneyosodo) [inline bootstrap/api/endpoint_test.go]: revert back to `require` as saved it used downstream

File: bootstrap/postgres/configs_test.go [hunk 10]
```diff
@@ -103,16 +106,16 @@ func TestRetrieveByID(t *testing.T) {
 	c := config
 	// Use UUID to prevent conflicts.
 	uid, err := uuid.NewV4()
-	require.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
+	assert.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
```
Comment (rodneyosodo) [inline bootstrap/postgres/configs_test.go]: revert as it is used downstream

File: bootstrap/postgres/configs_test.go [hunk 11]
```diff
@@ -103,16 +106,16 @@ func TestRetrieveByID(t *testing.T) {
...
 	c.MFKey = uid.String()
 	c.MFThing = uid.String()
 	c.ExternalID = uid.String()
 	c.ExternalKey = uid.String()
 	id, err := repo.Save(c, channels)
-	require.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
+	assert.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
```
Comment (rodneyosodo) [inline bootstrap/postgres/configs_test.go]: revert as it is used downstream

File: bootstrap/postgres/configs_test.go [hunk 12]
```diff
@@ -103,16 +106,16 @@ func TestRetrieveByID(t *testing.T) {
...
 
 	nonexistentConfID, err := uuid.NewV4()
-	require.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
+	assert.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
```
Comment (rodneyosodo) [inline bootstrap/postgres/configs_test.go]: revert as it is used downstream

File: bootstrap/postgres/configs_test.go [hunk 13]
```diff
@@ -158,10 +161,10 @@ func TestRetrieveAll(t *testing.T) {
 
 	for i := 0; i < numConfigs; i++ {
 		c := config
-		// Use UUID to prevent conflict errors.
 
+		// Use UUID to prevent conflict errors.
 		uid, err := uuid.NewV4()
-		require.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
+		assert.Nil(t, err, fmt.Sprintf("Got unexpected error: %s.\n", err))
```
Comment (rodneyosodo) [inline bootstrap/postgres/configs_test.go]: revert as it is used downstream

File: bootstrap/postgres/configs_test.go [hunk 14]
```diff
@@ -176,7 +179,7 @@ func TestRetrieveAll(t *testing.T) {
 		}
 
 		_, err = repo.Save(c, channels)
-		require.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
+		assert.Nil(t, err, fmt.Sprintf("Saving config expected to succeed: %s.\n", err))
```
Comment (rodneyosodo) [inline bootstrap/postgres/configs_test.go]: revert as it is used downstream

**Review by rodneyosodo — CHANGES_REQUESTED** [review]
Feel free to ignore comments on `auth` services. As it will change later on. My suggestion is if a variable is used downstream, for instance when we are testing `RetrieveAll` we need to used `require` when creating entities the later on when testing `RetrieveAll` we use `assert`

**Review by dborovcanin — DISMISSED** [review]

**Review by dborovcanin — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM
