### PR TITLE
SMQ-2609 - Enable superadmin to perform actions over entities

### LINKED ISSUE #2609: Bug: SuperAdmin could not perform actions over entities
### What were you trying to achieve?

Trying to perform some actions as super admin

### What are the expected results?

Perform action without authorization error

### What are the received results?

I could not preform the actions , Not Authorized

### Steps To Reproduce

_No response_

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

It is happened due to removal of domain login and the polici

At present in spicedb we have userid prefixed with domain
Example : `0c883527-8316-4711-b7e9-ded734bf96ed_84319f2a-046a-44d7-b24c-06b15d38ac74`
Here `0c883527-8316-4711-b7e9-ded734bf96ed`  is domain ID,
we should store without domain id prefix.

We should remove the `EncodeDomainUserID` at https://github.com/absmach/supermq/blob/e8e17f55304a13f5774311cd8a0a150d4f8ae027/internal/api/auth.go#L46
image

And then remove DomainUserID from authn.Session 
at https://github.com/absmach/supermq/blob/e8e17f55304a13f5774311cd8a0a150d4f8ae027/pkg/authn/authn.go#L33

Then we need to perform all authorization with `UserID`

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a refactor as it remove DomainUserID encoding.

## What does this do?
This pr removes DomainUserID encodinh and makes all authorization on entities to be performed with userID.

## Which issue(s) does this PR fix/relate to?

- Related Issue #
- Resolves #2609 

## Have you included tests for your changes?
Yes, I have updated tests.

## Did you document any new/modified feature?
No,

### Notes
None

### CODE REVIEW

File: pkg/authz/authsvc/authz.go [hunk 1]
```diff
@@ -55,6 +56,7 @@ func (a authorization) Authorize(ctx context.Context, pr authz.PolicyReq) error
 			domainID = pr.Object
 		}
 		if err := a.checkDomain(ctx, pr.SubjectType, pr.Subject, domainID); err != nil {
+			fmt.Println("Error thrwon here 0")
```
Comment (arvindh123) [inline pkg/authz/authsvc/authz.go]: @felixgateru Please remove debug prints in this file

File: groups/service.go [hunk 2]
```diff
@@ -183,7 +183,7 @@ func (svc service) RetrieveGroupHierarchy(ctx context.Context, session smqauthn.
 		return HierarchyPage{}, errors.Wrap(svcerr.ErrViewEntity, err)
 	}
 	hids := svc.getGroupIDs(hp.Groups)
-	ids, err := svc.filterAllowedGroupIDsOfUserID(ctx, session.DomainUserID, "read_permission", hids)
+	ids, err := svc.filterAllowedGroupIDsOfUserID(ctx, session.UserID, "read_permission", hids)
```
Comment (arvindh123) [inline groups/service.go]: This function logic need to be changed, because it is depend on SpiceDB for listing. 
Please create a new ticket for this task

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Comment by dborovcanin** [comment]
@arvindh123 @felixgateru  What's the status of this PR?

File: domains/middleware/authorization.go [hunk 3]
```diff
@@ -141,8 +150,7 @@ func (am *authorizationMiddleware) ListDomains(ctx context.Context, session auth
 }
 
 func (am *authorizationMiddleware) SendInvitation(ctx context.Context, session authn.Session, invitation domains.Invitation) (err error) {
-	domainUserId := auth.EncodeDomainUserID(invitation.DomainID, invitation.InviteeUserID)
```
Comment (arvindh123) [inline domains/middleware/authorization.go]: Why Invitations related authz middleware functions are removed ?

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Comment by arvindh123** [comment]
In this PR, we are changing the format from `<domain_id>_<user_id>` to just `<user_id>` in Spice DB for subjects.

One side effect/bug that occurs due to this PR is as follows:
I created `domain_1` with ID `88724ac6-a569-43c2-a895-d8d3e93ad3df` and `domain_2` with ID `716a571e-fbe7-4cd2-afdc-fa0780a24531`.

Then, I created a client, `client_1_of_domain_2`, with ID `1729828a-3c3d-4917-8678-b76abd28576a`, in `domain_2` (ID `716a571e-fbe7-4cd2-afdc-fa0780a24531`).

However, when I try to view client_1_of_domain_2 with domain_1 in the URL (e.g., `http://localhost/domain_1/clients/client_1_of_domain_2`),
it shows the details of client_1_of_domain_2 from domain_2. Ideally, I should see a "not found" message instead. (edited) 
image

**Comment by arvindh123** [comment]
> In this PR, we are changing the format from `<domain_id>_<user_id>` to just `<user_id>` in Spice DB for subjects.
> 
> One side effect/bug that occurs due to this PR is as follows: I created `domain_1` with ID `88724ac6-a569-43c2-a895-d8d3e93ad3df` and `domain_2` with ID `716a571e-fbe7-4cd2-afdc-fa0780a24531`.
> 
> Then, I created a client, `client_1_of_domain_2`, with ID `1729828a-3c3d-4917-8678-b76abd28576a`, in `domain_2` (ID `716a571e-fbe7-4cd2-afdc-fa0780a24531`).
> 
> However, when I try to view client_1_of_domain_2 with domain_1 in the URL (e.g., `http://localhost/domain_1/clients/client_1_of_domain_2`), it shows the details of client_1_of_domain_2 from domain_2. Ideally, I should see a "not found" message instead. (edited) image

I think we should find another way to solve  the issue.

File: internal/proto/token/v1/token.proto [hunk 4]
```diff
@@ -13,6 +13,7 @@ service TokenService {
 
 message IssueReq {
   string user_id = 1;
+  uint32 user_role = 2;
```
Comment (arvindh123) [inline internal/proto/token/v1/token.proto:16]: Why do we need `user_role` in `IssueReq` ?

File: journal/middleware/authorization.go [hunk 5]
```diff
@@ -39,7 +39,7 @@ func (am *authorizationMiddleware) RetrieveAll(ctx context.Context, session smqa
 	permission := readPermission
 	objectType := page.EntityType.String()
 	object := page.EntityID
-	subject := session.DomainUserID
+	subject := session.Subject
```
Comment (arvindh123) [inline journal/middleware/authorization.go]: Why this was changed to `Subject`

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: internal/proto/token/v1/token.proto (hunk 4 above)
Comment (felixgateru) [reply internal/proto/token/v1/token.proto:16]: This is to send the user role to auth when creating the token.

File: journal/middleware/authorization.go (hunk 5 above)
Comment (felixgateru) [reply journal/middleware/authorization.go]: I changed this to Subject as it can be just the userID or the domainUserId. Should I revert this?

File: internal/proto/token/v1/token.proto (hunk 4 above)
Comment (arvindh123) [reply internal/proto/token/v1/token.proto:16]: DomainUserID means id of user within the domain, which is different from actual user id for platform ,
In each domain, user should have unquie id .
So just we are adding prefix domain_id to user id to get the unqiue user id for user per domain , which is called domain user id

File: journal/middleware/authorization.go (hunk 5 above)
Comment (arvindh123) [reply journal/middleware/authorization.go]: DomainUserID means id of user within the domain, which is different from actual user id for platform ,
In each domain, user should have unquie id .
So just we are adding prefix domain_id to user id to get the unqiue user id for user per domain , which is called domain user id

File: auth/service.go [hunk 6]
```diff
@@ -330,11 +320,8 @@ func (svc service) refreshKey(ctx context.Context, token string, key Key) (Token
 	}
 	key.User = k.User
 	key.Type = AccessKey
-
-	key.Subject, err = svc.checkUserDomain(ctx, key)
-	if err != nil {
-		return Token{}, errors.Wrap(svcerr.ErrAuthorization, err)
-	}
+	key.Subject = k.Subject
+	key.Role = k.Role
```
Comment (arvindh123) [inline auth/service.go:331]: Don't put the role directly, 
Please check the user have the claimed role.

File: auth/service.go [hunk 7]
```diff
@@ -352,34 +339,6 @@ func (svc service) refreshKey(ctx context.Context, token string, key Key) (Token
 	return Token{AccessToken: access, RefreshToken: refresh}, nil
 }
 
-func (svc service) checkUserDomain(ctx context.Context, key Key) (subject string, err error) {
-	if key.Domain != "" {
```
Comment (arvindh123) [inline auth/service.go:352]: This function will be usefull to check the claimed role by request(user) service.

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: auth/jwt/tokenizer.go [hunk 8]
```diff
@@ -141,8 +145,22 @@ func toKey(tkn jwt.Token) (auth.Key, error) {
 		return auth.Key{}, errInvalidType
 	}
 
+	tRole, ok := tkn.Get(RoleField)
+	if !ok {
+		return auth.Key{}, errInvalidRole
+	}
+	kRole, err := strconv.ParseInt(fmt.Sprintf("%v", tRole), 10, 64)
```
Comment (arvindh123) [inline auth/jwt/tokenizer.go]: It's better to use type casting instead of `fmt.Sprintf("%v", tRole)`.

File: domains/middleware/authorization.go [hunk 9]
```diff
@@ -127,22 +132,16 @@ func (am *authorizationMiddleware) FreezeDomain(ctx context.Context, session aut
...
 		session.SuperAdmin = true
 	}
 
 	return am.svc.ListDomains(ctx, session, page)
 }
 
 func (am *authorizationMiddleware) SendInvitation(ctx context.Context, session authn.Session, invitation domains.Invitation) (err error) {
-	domainUserId := auth.EncodeDomainUserID(invitation.DomainID, invitation.InviteeUserID)
-	if err := am.extAuthorize(ctx, domainUserId, policies.MembershipPermission, policies.DomainType, invitation.DomainID); err == nil {
+	Subject := auth.EncodeDomainUserID(invitation.DomainID, invitation.InviteeUserID)
```
Comment (arvindh123) [inline domains/middleware/authorization.go]: Can we revert back  this variable to `domainUserId` ?

File: auth/keys.go [hunk 10]
```diff
@@ -57,13 +57,36 @@ func (kt KeyType) String() string {
...
+}
+
 // Key represents API key.
 type Key struct {
 	ID        string    `json:"id,omitempty"`
 	Type      KeyType   `json:"type,omitempty"`
 	Issuer    string    `json:"issuer,omitempty"`
 	Subject   string    `json:"subject,omitempty"` // user ID
 	User      string    `json:"user,omitempty"`
+	Role      Role      `json:"role,omitempty"`
```
Comment (arvindh123) [inline auth/keys.go:88]: Lets remove `Domain` and `User`
The `Subject` will hold `user_id`.

File: pkg/authn/authn.go [hunk 11]
```diff
@@ -27,13 +27,21 @@ func (t TokenType) String() string {
...
+const (
+	UserRole Role = iota + 1
+	AdminRole
+)
+
 type Session struct {
 	Type         TokenType
 	PatID        string
-	DomainUserID string
 	UserID       string
```
Comment (arvindh123) [inline pkg/authn/authn.go:40]: UserID will hold the `sub` field in JWT Token

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: api/http/authn.go [hunk 12]
```diff
@@ -40,6 +40,9 @@ func AuthenticateMiddleware(authn smqauthn.Authentication, domainCheck bool) fun
 				resp.DomainID = domain
```
Comment (arvindh123) [inline api/http/authn.go:40]: Can we have something like this ? 
```suggestion
				resp.DomainID = domain
				switch resp.Role {
				case smqauthn.AdminRole:
					resp.DomainUserID = resp.UserID
				case smqauthn.UserRole:
					resp.DomainUserID = auth.EncodeDomainUserID(domain, resp.UserID)
				} 
```

File: internal/proto/auth/v1/auth.proto [hunk 13]
```diff
@@ -23,7 +23,7 @@ message AuthNReq {
 message AuthNRes {
   string id    = 1;     // id
```
Comment (arvindh123) [inline internal/proto/auth/v1/auth.proto]:
```suggestion
  string id    = 1;     // token id
```

File: domains/middleware/authorization.go [hunk 14]
```diff
@@ -58,6 +58,11 @@ func (am *authorizationMiddleware) CreateDomain(ctx context.Context, session aut
 }
 
 func (am *authorizationMiddleware) RetrieveDomain(ctx context.Context, session authn.Session, id string, withRoles bool) (domains.Domain, error) {
+	if err := am.checkSuperAdmin(ctx, session.UserID); err == nil {
+		session.SuperAdmin = true
+		return am.svc.RetrieveDomain(ctx, session, id, withRoles)
+	}
```
Comment (arvindh123) [inline domains/middleware/authorization.go:64]: Could you please explain why this check is needed here

Comment (felixgateru) [reply domains/middleware/authorization.go:64]: I had included this because we have retrieving the domain with superadmin context here:
https://github.com/absmach/supermq/blob/878860d249d79765399b220f1f8bda8f3d7ab699/domains/service.go#L103-L113

Comment (arvindh123) [reply domains/middleware/authorization.go:64]: Got it

**Review by dborovcanin — APPROVED** [review]
@arvindh123 Please re-review.

**Review by arvindh123 — APPROVED** [review]
LGTM
