### PR TITLE
MG-2296 - Domain creation allowed with nil alias

### LINKED ISSUE #2296: Bug: domain creation allowed with nil alias
### What were you trying to achieve?

Create `domain` with NULL alias

### What are the expected results?

Domain should not create

### What are the received results?

Domain created

### Steps To Reproduce

REST API To create domain with null domain

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by JeffMboya**
# What type of PR is this?
This is a bug fix

## What does this do?
This PR modifies the `alias` field in the `auth` table to be NOT NULL and/or empty and UNIQUE. This prevents the creation of a domain with a NULL or empty alias, which was previously allowed.

## Which issue(s) does this PR fix/relate to?

- Resolves #2296 

## Have you included tests for your changes?
Yes, I have included tests for my changes.

### CODE REVIEW

File: auth/postgres/init.go [hunk 1]
```diff
@@ -30,7 +30,7 @@ func Migration() *migrate.MemoryMigrationSource {
                         name        VARCHAR(254),
                         tags        TEXT[],
                         metadata    JSONB,
-                        alias       VARCHAR(254) NULL UNIQUE,
+                        alias       VARCHAR(254) NOT NULL UNIQUE,
```
Comment (rodneyosodo) [inline auth/postgres/init.go]: It should also be not empty

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

File: auth/postgres/init.go [hunk 2]
```diff
@@ -51,6 +51,14 @@ func Migration() *migrate.MemoryMigrationSource {
 					`DROP TABLE IF EXISTS keys`,
 				},
 			},
+			{
+				Id: "auth_2",
+				Up: []string{
+					`ALTER TABLE domains 
+                     ALTER COLUMN alias SET NOT NULL, 
+                     ADD CONSTRAINT alias_not_empty CHECK (alias <> '');`,
```
Comment (dborovcanin) [inline auth/postgres/init.go]: There is a need for this constraint. It makes sense, but for consistency with the rest of the codebase, let's have this check on API or svc layers.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: auth/postgres/init.go (hunk 2 above)
Comment (arvindh123) [reply auth/postgres/init.go]: Additonal to this constraint, we can add the this check in API Layer, where we do data validation.

**Review by arvindh123 — CHANGES_REQUESTED** [review]

File: auth/postgres/init.go (hunk 2 above)
Comment (dborovcanin) [reply auth/postgres/init.go]: Since you have added API validation, please remove it from the DB for the sake of consistency with the rest of the codebase.

Comment (JeffMboya) [reply auth/postgres/init.go]: Okay

**Review by arvindh123 — APPROVED** [review]

**Review by dborovcanin — APPROVED** [review]
