### PR TITLE
SMQ-2866 - MQTT auth fails with identical secrets across different domains

### LINKED ISSUE #2866: Bug: MQTT auth fails with identical secrets across different domains
### What were you trying to achieve?

Was using MQTT to send message.

### What are the expected results?

Clients should send message via MQTT

### What are the received results?

`{"time":"2025-05-12T04:44:17.98368156Z","level":"WARN","msg":"failed to proxy from MQTT broker to client with id 19eef5c7-d2ef-456b-84b7-336f596a78d3-pub with error: invalid user id"}`

### Steps To Reproduce

1. Create `client1` in `domain1`  with `secret1`
2. Create `channel1` in `domain1` and connect `client1` and `channel1`
3. Create `client2` in `domain2`  with `secret1`
4. Create `channel2` in `domain2` and connect `client2` and `channel2`
5. Send a message via `MQTT` with either client

### In what environment did you encounter the issue?

Docker supermq

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by dborovcanin**
# What type of PR is this?
This is a bugfix.

## What does this do?
This pull request enables messaging for multiple clients with the same key in different domains.

## Which issue(s) does this PR fix/relate to?

- Resolves #2866

## Have you included tests for your changes?
Yes.

## Did you document any new/modified feature?
N/A

### Notes
N/A

### CODE REVIEW

File: pkg/authn/authn.go [hunk 1]
```diff
@@ -48,3 +51,57 @@ type Session struct {
...
+	}
+	return "Unknown"
+}
+
+// ErrNotEncoded acts similarly to EOF - it does indicate there is no suffix in
+// the token, but that does not have to be treated as the error in some cases.
+// If token is not base64-encoded, the token is returned as a key alongside with the error.
+var ErrNotEncoded = errors.New("token is not encoded with domain ID suffix")
+
+func AuthUnpack(token string) (AuthPrefix, string, string, error) {
```
Comment (arvindh123) [inline pkg/authn/authn.go:84]: **Why don't we handle this at the protocol layer, like in HTTP or CoAP headers?**
HTTP supports basic authentication, so we can perform this at the HTTP layer and send the ID and key to the Clients service for verification.
We can do the same with CoAP, since it functions similarly to an HTTP server.

Comment (dborovcanin) [reply pkg/authn/authn.go:84]: Backward compatibility is the only reason for the time being. We can switch to basic Auth, but then we will break the API - `Client` prefix will make no sense anymore.

**Review by nyagamunene — DISMISSED** [review]
LGTM
