### PR TITLE
MF-1833 - Fix spelling of bootstrap on SDK

### LINKED ISSUE #1833: Parameters are not passed correctly in `authClient.Setup`
**BUG REPORT**
In  `internal/clients/grpc/auth/client.go` ,  `Setup` function parameter are not passed in same order in all the `cmd/<svc?/main.go`

Here the function 
https://github.com/mainflux/mainflux/blob/55e09c1921aecdda10980b716caaabf1a8801ac4/internal/clients/grpc/auth/client.go#L18-L30

All `cmd/<svc>/main.go` where `authClinet.Setup` function is called
```
cmd/bootstrap/main.go:
  85  	// Create new auth grpc client api
  86: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  87: 	if err != nil {
  88  		logger.Fatal(err.Error())

cmd/cassandra-reader/main.go:
  67  	// Create new auth grpc client
  68: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  69: 
  69  	if err != nil {

cmd/certs/main.go:
  92  
  93: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  94: 	if err != nil {
  95  		logger.Fatal(err.Error())

cmd/influxdb-reader/main.go:
  65  
  66: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  67: 
  67  	if err != nil {

cmd/mongodb-reader/main.go:
  71  
  72: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  73: 
  73  	if err != nil {

cmd/postgres-reader/main.go:
  64  
  65: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  66: 
  66  	if err != nil {

cmd/smpp-notifier/main.go:
   99  
  100: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  101: 
  101  	if err != nil {

cmd/smtp-notifier/main.go:
  100  
  101: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  102: 
  102  	if err != nil {

cmd/timescale-reader/main.go:
  69  
  70: 	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  71: 
  71  	if err != nil {

cmd/twins/main.go:
  101  	default:
  102: 		authServiceClient, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
  103: 
  103  		if err != nil {
```

1. What were you trying to achieve?

2. What are the expected results?

3. What are the received results?

4. What are the steps to reproduce the issue?

5. In what environment did you encounter the issue?

6. Additional information you deem important:

**ENHANCEMENT**
1. Describe the enhancement you are requesting. Enhancements include:
   - tests
   - code refactor
   - documentation
   - research
   - tooling

2. Indicate the importance of this enhancement to you (must-have, should-have, nice-to-have).

### PR DESCRIPTION
**Pull request by SammyOina**
### What does this do?
Fixes spelling in sdk

### Which issue(s) does this PR fix/relate to?
Resolves #1833 

### List any changes that modify/break current functionality
None

### Have you included tests for your changes?
No

### Did you document any new/modified functionality?
No

### CODE REVIEW

File: cmd/bootstrap/main.go [hunk 1]
```diff
@@ -83,7 +83,7 @@ func main() {
 	defer esClient.Close()
 
 	// Create new auth grpc client api
-	auth, authHandler, err := authClient.Setup(envPrefix, svcName, cfg.JaegerURL)
+	auth, authHandler, err := authClient.Setup(envPrefix, cfg.JaegerURL, svcName)
```
Comment (rodneyosodo) [inline cmd/bootstrap/main.go]: why not change `authClient.Setup` to accept `svcName` first then `JaegerURL`?

Comment (SammyOina) [reply cmd/bootstrap/main.go]: Some of the implementations had the correct order of parameters

Comment (rodneyosodo) [reply cmd/bootstrap/main.go]: That was only one service `things`

Comment (arvindh123) [reply cmd/bootstrap/main.go]: @rodneyosodo 
In Auth gRPC client its defined as 
```go
func Setup(envPrefix, jaegerURL, svcName string)
```
https://github.com/mainflux/mainflux/blob/master/internal/clients/grpc/auth/client.go#L19

In things gRPC client defined as 
```go
func Setup(envPrefix, jaegerURL string)
```
https://github.com/mainflux/mainflux/blob/master/internal/clients/grpc/things/client.go#L19

Because of this alignment, `svcName` went last

File: internal/clients/grpc/connect.go [hunk 2]
```diff
@@ -84,8 +85,13 @@ func Setup(config Config, svcName, jaegerURL string) (*Client, ClientHandler, er
 		return nil, nil, errors.Wrap(errGrpcConnect, err)
 	}
 
+	jURL, err := url.Parse(jaegerURL)
+	if err != nil {
```
Comment (arvindh123) [inline internal/clients/grpc/connect.go]: Nice to have this check 

Could you return error with error message something like below code 
```go 
	jURL, err := url.Parse(jaegerURL)
	if err != nil {
		return nil, nil, errors.Wrap(ErrFailedToParseJagerUrl,err)
	}
```

File: cmd/bootstrap/main.go (hunk 1 above)
Comment (dborovcanin) [reply cmd/bootstrap/main.go]: I'd also prefer `svc` name before JaegerURL.  Please fix it in `/internal/clients/grpc` as well.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Comment by SammyOina** [comment]
https://github.com/mainflux/mainflux/pull/1849 removed jaeger URL from setup so this PR is now repurposed

**Review by rodneyosodo — APPROVED** [review]
LGTM

**Review by dborovcanin — APPROVED** [review]

**Review by drasko — APPROVED** [review]
LGTM
