### PR TITLE
MG-2125 - Unable to enable thing using bootstrap

### LINKED ISSUE #2125: Bug: Unable to enable thing using bootstrap
### What were you trying to achieve?

I was trying to connect a thing to the channels by using  curl request to the things service.

### What are the expected results?

The expected result is a successful response indicating that the thing has been connected to the channel.

### What are the received results?

This was the received results. When setting the state to 1 this is the result. 
image
And this is the logs from the bootstrap service.
image
And this is the logs from the things service.
image

### Steps To Reproduce

1. Run Magistrala using command `make run`
2. Run Bootstrap service using command `make run_addons bootstrap`
3. Created new thing and channel.
4. Create bootstrap configuration of the thing and channel
5. Connect the thing to the channels using the following request:
`curl -s -S -i -X PUT -H "Authorization: Bearer <user_token>" -H "Content-Type: application/json" http://localhost:9013/things/state/<thing_id> -d '{"state": 1}'`

### In what environment did you encounter the issue?

Docker

### Additional information you deem important

This issue is preventing the thing from being connected to the channels, which is a critical functionality.For more details, Please refer below bootstrap doc
https://docs.magistrala.abstractmachines.fr/bootstrap/

### PR DESCRIPTION
**Pull request by JeffMboya**
# What type of PR is this?

This is a bug fix.

## What does this do?

This PR introduces ```svcerr.ErrConflict``` into the `Connect` function. The ```svcerr.ErrConflict``` error is triggered when an attempt is made to establish a connection that already exists. In this case, instead of halting the process, the `Connect` function skips the current iteration and returns ```HTTP/1.1 200 OK``` (because the desired end state - a connection existing- is already true for the current channel) and moves on to the next channel. This ensures that all channels in ```conIDs``` are processed, and any existing connections do not interrupt the operation. 

## Which issue(s) does this PR fix/relate to?

- Related Issue #2125 
- Resolves #2125

## Have you included tests for your changes?

No

## Did you document any new/modified feature?

No, I have not updated the documentation because the changes are related to error handling and do not introduce new functionality.

### CODE REVIEW

File: bootstrap/service.go [hunk 1]
```diff
@@ -25,6 +25,9 @@ var (
 	// ErrExternalKey indicates a non-existent bootstrap configuration for given external key.
 	ErrExternalKey = errors.New("failed to get bootstrap configuration for given external key")
 
+	// ErrConflict indicates that the entity that the client is trying to create already exists.
```
Comment (arvindh123) [inline bootstrap/service.go]: Are we going to use this error `ErrConflict` ?
I see in code we are using svcerr.ErrConflict not `ErrConflict`

File: bootstrap/service.go [hunk 2]
```diff
@@ -25,6 +25,9 @@ var (
...
+	ErrConflict = errors.New("Entity already exists")
```
Comment (felixgateru) [inline bootstrap/service.go]: What is the use of this definition here

**Review by felixgateru — CHANGES_REQUESTED** [review]

File: bootstrap/service.go (hunk 1 above)
Comment (JeffMboya) [reply bootstrap/service.go]: We are not using it. That was an oversight.

**Review by arvindh123 — DISMISSED** [review]

**Review by felixgateru — DISMISSED** [review]

File: bootstrap/service.go [hunk 3]
```diff
@@ -325,6 +325,9 @@ func (bs bootstrapService) ChangeState(ctx context.Context, token, id string, st
 				ThingID:   cfg.ThingID,
 			}
 			if err := bs.sdk.Connect(conIDs, token); err != nil {
+				if errors.Contains(err, svcerr.ErrConflict) {
+					continue
+				}
```
Comment (dborovcanin) [inline bootstrap/service.go:331]: Please add a comment explaining why we are ignoring the conflicts.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — DISMISSED** [review]
