### PR TITLE
MG-1981 - Fix bug on list groups wth subject returning subject group.

### LINKED ISSUE #1981: Bug: List group parents and children returning the group that is the subject
### What were you trying to achieve?

To list the children and parents of the group with a given group ID

### What are the expected results?

Return a list of group(s) that are children or parents of the group with the given ID

### What are the received results?

Returns a list of group(s) that includes the group with the group ID being queried

### Steps To Reproduce

1. create a group with a parent ID
2. list the parents of the group created
3. list the children of the group that was added as the parent of the group created

### In what environment did you encounter the issue?

Magistrala groups

### Additional information you deem important

for this request: `http://localhost:9002/groups/312314e9-a3f4-475b-9e94-a2063ef7da8c/parents` we get this response:
```
{
    "limit": 0,
    "offset": 0,
    "total": 8,
    "groups": [
        {
            "id": "fd422be0-0e14-4ef9-a494-bd6ddcb82d51",
            "owner_id": "c06712e8-df2b-4449-80cb-3638a7ddbfa3",
            "name": "myGroup",
            "level": -1,
            "created_at": "2023-12-15T11:56:03.838685Z",
            "updated_at": "2023-12-15T11:56:22.723821Z",
            "status": "enabled"
        },
        {
            "id": "312314e9-a3f4-475b-9e94-a2063ef7da8c",
            "owner_id": "c06712e8-df2b-4449-80cb-3638a7ddbfa3",
            "parent_id": "fd422be0-0e14-4ef9-a494-bd6ddcb82d51",
            "name": "myGroup's group",
            "created_at": "2023-12-15T13:02:21.857174Z",
            "updated_at": "0001-01-01T00:00:00Z",
            "status": "enabled"
        }
    ]
}
```

for this request: `http://localhost:9002/groups/fd422be0-0e14-4ef9-a494-bd6ddcb82d51/children` we get this response: 

```
{
    "limit": 0,
    "offset": 0,
    "total": 8,
    "groups": [
        {
            "id": "fd422be0-0e14-4ef9-a494-bd6ddcb82d51",
            "owner_id": "c06712e8-df2b-4449-80cb-3638a7ddbfa3",
            "name": "myGroup",
            "path": "fd422be0-0e14-4ef9-a494-bd6ddcb82d51",
            "created_at": "2023-12-15T11:56:03.838685Z",
            "updated_at": "2023-12-15T11:56:22.723821Z",
            "status": "enabled"
        },
        {
            "id": "312314e9-a3f4-475b-9e94-a2063ef7da8c",
            "owner_id": "c06712e8-df2b-4449-80cb-3638a7ddbfa3",
            "parent_id": "fd422be0-0e14-4ef9-a494-bd6ddcb82d51",
            "name": "myGroup's group",
            "level": 1,
            "path": "fd422be0-0e14-4ef9-a494-bd6ddcb82d51.312314e9-a3f4-475b-9e94-a2063ef7da8c",
            "created_at": "2023-12-15T13:02:21.857174Z",
            "updated_at": "0001-01-01T00:00:00Z",
            "status": "enabled"
        },
        {
            "id": "f3dc7f00-d401-491b-9a58-07b06afcec5a",
            "owner_id": "c06712e8-df2b-4449-80cb-3638a7ddbfa3",
            "parent_id": "fd422be0-0e14-4ef9-a494-bd6ddcb82d51",
            "name": "myGroup's other Group",
            "level": 1,
            "path": "fd422be0-0e14-4ef9-a494-bd6ddcb82d51.f3dc7f00-d401-491b-9a58-07b06afcec5a",
            "created_at": "2023-12-15T13:11:21.974904Z",
            "updated_at": "0001-01-01T00:00:00Z",
            "status": "enabled"
        }
    ]
}
```

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a bug fix because it fixes the following issue: #1981 

## What does this do?
This pr fixes the bug  on list group parents and children returning the group that is the subject.

## Which issue(s) does this PR fix/relate to?

- Resolves #1981

## Have you included tests for your changes?
No, I have not included test because the part of the code is already covered by tests.

## Did you document any new/modified feature?
No

### Notes
N/A

### CODE REVIEW

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Can you add some tests for this fix?

File: internal/groups/api/endpoints.go [hunk 1]
```diff
@@ -262,7 +263,7 @@ func toViewGroupRes(group groups.Group) viewGroupRes {
 	return view
 }
 
-func buildGroupsResponse(gp groups.Page) groupPageRes {
+func buildGroupsResponse(gp groups.Page, fbid bool) groupPageRes {
```
Comment (rodneyosodo) [inline internal/groups/api/endpoints.go]:
```suggestion
func buildGroupsResponse(gp groups.Page, filterByID bool) groupPageRes {
```

**Review by rodneyosodo — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
