### PR TITLE
MF-1006 - Password recovery endpoint is not working

### LINKED ISSUE #1006: Password recovery endpoint is not working
**BUG REPORT**

1. What were you trying to achieve?
I forgot my password and I'm trying to recover.

2. What are the expected results?
I expect an email with a recovery link.

3. What are the received results?
I got status code 400 with info that the user is not found.

4. What are the steps to reproduce the issue?
Run Docker composition. Register. Try to recover the forgotten password.

5. In what environment did you encounter the issue?
I use Docker-compose version 1.25.0, the `latest` version of Mainflux containers. I also faced the same bug with tagged version `0.10.0`.

6. Additional information you deem important:
Issuing a recovery token with `Authentication` service seems to be the problem.

### PR DESCRIPTION
**Pull request by dborovcanin**
### What does this do?
This pull request fixes password recovery.

### Which issue(s) does this PR fix/relate to?
Fixes #1006.

### List any changes that modify/break current functionality
There are no such changes.

### Have you included tests for your changes?
Yes.

### Did you document any new/modified functionality?
Yes.

### CODE REVIEW

**Review by drasko — APPROVED** [review]
LGTM

**Review by blokovi — APPROVED** [review]

File: authn/service.go [hunk 1]
```diff
@@ -10,9 +10,9 @@ import (
 )
 
 const (
-	loginDuration = 10 * time.Hour
-	resetDuration = 5 * time.Minute
-	issuerName    = "mainflux.authn"
+	loginDuration    = 10 * time.Hour
+	recoveryDuration = 5 * time.Minute
+	issuerName       = "mainflux.authn"
 )
```
Comment (nmarcetic) [inline authn/service.go:16]: Can we use this as default values and provide env variables? IMHO 5min is to short for recovery token, I would set at least 15+ min
