### PR TITLE
MF-1079 - Add MQTT forwarder

### LINKED ISSUE #1079: Add MQTT forwarder
**BUG REPORT**

1. What were you trying to achieve?
I am trying to publish messages using HTTP or Websocket so a device using MQTT subscribe can receive messages.

2. What are the expected results?
When publishing messages using HTTP or Websocket over a channel, a device subscribe to that channel using MQTT should receive messages.

3. What are the received results?
MQTT sub are not receiving messages published by HTTP or Websocket.

4. What are the steps to reproduce the issue?
- Create two things and a channel and connect both things to that channel.
- Subscribe to the channel using thing-1-id and thing-1-key. 
- Publish a message using thing-2-id and thing-2-key over the channel using HTTP or Websocket

5. In what environment did you encounter the issue?
- Latest Docker images deployed using docker-compose.
- Tried everything on one Linux machine, or separate pub and sub into two Linux machines.

6. Additional information you deem important:
- MQTT sub receives MQTT pub without any issues.
- Websocket receives HTTP, Websocket and MQTT published messages without any issues.
- Subscribe using mosquitto
```mosquitto_sub -u 7287b133-942c-45f1-a19f-ff77167db47b -P ebd001f4-a6ec-4c03-b0fb-6f78bd16608c -t channels/434b9b66-94be-4f99-913d-6de7bb1c2008/messages/ct/application_senml-json -h localhost```
- Subscribe using Paho
Created a Java program using Paho library to subscribe to the same channel.
- Publish using CURL 
```curl -s -S -X POST -H "Content-Type: application/senml+json" -H "Authorization: 0250e814-deca-4cca-8201-9ab535ed32a9" http://localhost/http/channels/434b9b66-94be-4f99-913d-6de7bb1c2008/messages -d '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]'```
- Publish using CLI
```docker run -it --rm mainflux/cli -m http://<host ip> messages send 434b9b66-94be-4f99-913d-6de7bb1c2008 '[{"bn":"some-base-name:","bt":1.276020076001e+09, "bu":"A","bver":5, "n":"voltage","u":"V","v":120.1}, {"n":"current","t":-5,"v":1.2}, {"n":"current","t":-4,"v":1.3}]' 0250e814-deca-4cca-8201-9ab535ed32a9```
- Publish using Websocket
Created a JS page and published same message using Websocket.

### PR DESCRIPTION
**Pull request by dborovcanin**
### What does this do?
This pull request introduces MQTT forwarder for multi-protocol support explained in #1079.

### Which issue(s) does this PR fix/relate to?
This pull request fixes #1079.

### List any changes that modify/break current functionality
Messages published from other protocols will be received on MQTT subs.

### Have you included tests for your changes?
No.

### Did you document any new/modified functionality?
This fix will make the MQTT adapter work as intended.

### CODE REVIEW

File: messaging/mqtt/subscriber.go [hunk 1]
```diff
@@ -0,0 +1,81 @@
+// Copyright (c) Mainflux
+// SPDX-License-Identifier: Apache-2.0
+
+package mqtt
+
+import (
+	"errors"
```
Comment (blokovi) [inline messaging/mqtt/subscriber.go]: why not `"github.com/mainflux/mainflux/errors"` ?

File: cmd/mqtt/main.go [hunk 2]
```diff
@@ -130,6 +136,22 @@ func main() {
...
+		logger.Error(fmt.Sprintf("Failed to connect to NATS: %s", err))
+		os.Exit(1)
+	}
+	defer ps.Close()
+	mqttPub, err := mqttpub.NewPublisher(fmt.Sprintf("%s:%s", cfg.mqttTargetHost, cfg.mqttTargetPort), cfg.mqttForwarderTimeout)
+	if err != nil {
+		logger.Error(fmt.Sprintf("Failed to create MQTT publisher: %s", err))
+		os.Exit(1)
+	}
+	if err := mqtt.Forward(nats.SubjectAllChannels, ps, mqttPub); err != nil {
```
Comment (manuio) [inline cmd/mqtt/main.go:150]: `nats.SubjectAllChannels` should be used as arg here `nats.NewPubSub(cfg.natsURL, "mqtt", logger)`

Comment (manuio) [inline cmd/mqtt/main.go]: should we configure `nats.SubjectAllChannels` from pubsub?

File: mqtt/forwarder.go [hunk 3]
```diff
@@ -0,0 +1,33 @@
...
+func Forward(topic string, sub messaging.Subscriber, pub messaging.Publisher) error {
+	return sub.Subscribe(topic, handle(pub))
+}
+
+func handle(pub messaging.Publisher) messaging.MessageHandler {
+	return func(msg messaging.Message) error {
+		if msg.Protocol == protocol {
+			return nil
+		}
+		topic := fmt.Sprintf("%s.%s.%s.%s", channels, msg.Channel, messages, msg.Subtopic)
```
Comment (manuio) [inline mqtt/forwarder.go]: Is `topic` ok if `Subtopic` is empty?

**Review by manuio — CHANGES_REQUESTED** [review]

File: cmd/mqtt/main.go [hunk 4]
```diff
@@ -130,6 +136,22 @@ func main() {
 
 	cc := thingsapi.NewClient(conn, thingsTracer, cfg.thingsAuthTimeout)
 
+	ps, err := nats.NewPubSub(cfg.natsURL, "mqtt", logger)
```
[the remark this answers is not in the document]
Comment (drasko) [reply cmd/mqtt/main.go]: Maybe `nps` can be a good compromise? Also `mqttPub` can become `mp` and `pub` below can become `np`.

In any case, using long or short names - we should be consistent - which is not currently the case.

File: messaging/mqtt/pubsub.go [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+
+func newClient(address string, timeout time.Duration) (mqtt.Client, error) {
+	opts := mqtt.NewClientOptions().
+		AddBroker(address).
+		SetUsername(id).
+		SetPassword(id).
+		SetClientID(id).
+		SetCleanSession(false)
+	client := mqtt.NewClient(opts)
+	tkn := client.Connect()
```
Comment (drasko) [inline messaging/mqtt/pubsub.go]: What does `tkn` stand for?

File: messaging/mqtt/subscriber.go [hunk 6]
```diff
@@ -0,0 +1,81 @@
...
+	"fmt"
+
```
Comment (drasko) [inline messaging/mqtt/subscriber.go]: Kill this white line

**Review by drasko — CHANGES_REQUESTED** [review]

File: messaging/mqtt/pubsub.go (hunk 5 above)
Comment (dborovcanin) [reply messaging/mqtt/pubsub.go]: It stands for `token`. That's the construct Paho internally returns on the async operations.

Comment (manuio) [reply messaging/mqtt/pubsub.go]: Why not `token`?

Comment (drasko) [reply messaging/mqtt/pubsub.go]: It is bit confusing IMHO, maybe comment could help?

Comment (manuio) [reply messaging/mqtt/pubsub.go]: @drasko why a comment?

Comment (mteodor) [reply messaging/mqtt/pubsub.go]: why not `token` than?

**Review by drasko — DISMISSED** [review]
LGTM

File: messaging/mqtt/publisher.go [hunk 7]
```diff
@@ -0,0 +1,48 @@
...
+		client:  client,
+		timeout: timeout,
+	}
+	return ret, nil
+}
+
+func (pub publisher) Publish(topic string, msg messaging.Message) error {
+	token := pub.client.Publish(topic, qos, false, msg.Payload)
+	ok := token.WaitTimeout(pub.timeout)
+	if ok && token.Error() != nil {
```
Comment (manuio) [inline messaging/mqtt/publisher.go:43]: What if `token.Error() != nil` in the previous line?

**Review by manuio — CHANGES_REQUESTED** [review]

File: mqtt/forwarder.go [hunk 8]
```diff
@@ -0,0 +1,51 @@
...
+		if msg.Protocol == protocol {
+			return nil
+		}
+		// Use concatenation instead of mft.Sprintf for the
+		// sake of simplicity and performance.
+		topic := channels + "." + msg.Channel + "." + messages
+		if msg.Subtopic != "" {
+			topic += "." + msg.Subtopic
+		}
+		topic = strings.ReplaceAll(topic, ".", "/")
```
Comment (manuio) [inline mqtt/forwarder.go]: why not simply use `/`? 
Also, use fmt.Sprint() to concatenate strings

**Review by manuio — CHANGES_REQUESTED** [review]

File: mqtt/forwarder.go (hunk 8 above)
Comment (dborovcanin) [reply mqtt/forwarder.go]: Changed to `/`. String buffer would be an overkill here, and the comment explains why I don't want to use `Sprintf`.

File: messaging/mqtt/publisher.go (hunk 7 above)
Comment (mteodor) [reply messaging/mqtt/publisher.go:43]: dont you like this `if token.Wait() && token.Error() != nil {` better ?

File: messaging/mqtt/subscriber.go [hunk 9]
```diff
@@ -0,0 +1,80 @@
...
+		logger:  logger,
+	}
+	return ret, nil
+}
+
+func (sub subscriber) Subscribe(topic string, handler messaging.MessageHandler) error {
+	token := sub.client.Subscribe(topic, qos, sub.mqttHandler(handler))
+	ok := token.WaitTimeout(sub.timeout)
+	if ok && token.Error() != nil {
+		return token.Error()
```
Comment (mteodor) [inline messaging/mqtt/subscriber.go:52]: if we return `token.Error()` on multiple places it would be good to wrap with another error so that exact place can be more easily detected

File: mqtt/forwarder.go (hunk 8 above)
Comment (drasko) [reply mqtt/forwarder.go]: Makes sense, and I think we should consider avoiding `sprintf` in general where `+` string concatenation can bring simplicity. We need to sync internally and understand when to use one and when another.

File: messaging/mqtt/subscriber.go (hunk 9 above)
Comment (dborovcanin) [reply messaging/mqtt/subscriber.go:52]: I would leave error wrapping for the layer above MQTT Publisher or Subscriber. We only use it as a wrapper around MQTT client, so returning the real error is sufficient, IMHO. However, I'll improve the message of the errors we return if token is expired to be more specific ("failed to subscribe/unsubscribe due to timeout reached" is better than just "failed to subscribe/unsubscribe").

File: cmd/mqtt/main.go [hunk 10]
```diff
@@ -16,6 +16,7 @@ import (
 	"github.com/mainflux/mainflux"
 	"github.com/mainflux/mainflux/logger"
 	"github.com/mainflux/mainflux/messaging"
+	mqttpub "github.com/mainflux/mainflux/messaging/mqtt"
 	"github.com/mainflux/mainflux/messaging/nats"
 	mqtt "github.com/mainflux/mainflux/mqtt"
 	mr "github.com/mainflux/mainflux/mqtt/redis"
```
Comment (manuio) [inline cmd/mqtt/main.go]: I would use `mqttRedis` here.

File: messaging/mqtt/pubsub.go [hunk 11]
```diff
@@ -0,0 +1,39 @@
...
+
+func newClient(address string, timeout time.Duration) (mqtt.Client, error) {
+	opts := mqtt.NewClientOptions().
+		AddBroker(address).
+		SetUsername(id).
+		SetPassword(id).
+		SetClientID(id).
+		SetCleanSession(false)
+	client := mqtt.NewClient(opts)
+	token := client.Connect()
```
Comment (manuio) [inline messaging/mqtt/pubsub.go:29]: Should we add a check here?

**Review by manuio — CHANGES_REQUESTED** [review]

File: messaging/mqtt/pubsub.go (hunk 11 above)
Comment (dborovcanin) [reply messaging/mqtt/pubsub.go:29]: I added the check.

**Review by manuio — APPROVED** [review]
LGTM

File: cmd/mqtt/main.go (hunk 10 above)
Comment (drasko) [reply cmd/mqtt/main.go]: Why Redis? How is this MQTT forwarding related to Redis?

**Review by mteodor — APPROVED** [review]
